### ISSUE TITLE
SIGSEGV in rsyslog-8.19.0 imfile with invalid regex statement

### ISSUE THREAD

**Issue by kortemik** [rsyslog/rsyslog#1072]
Following configuration seems to cause imfile to SIGSEGV on exit

```
input
(
        type="imfile"
        File="/opt/rsyslog-imfile/var/test.log"
        Tag="test-01688"
        Severity="info"
        Facility="local0"
        startmsg.regex="{ROR.*|HOR.*"
)

```

```
(gdb) signal 15
Continuing with signal SIGTERM.
2059.674196029:imfile.c       : imfile: error during inotify: Interrupted system call
2059.674211105:main thread    : DoDie called.
2059.674224227:main thread    : exiting on signal 15
2059.674229400:main thread    : Terminating input threads...
2059.674234923:main thread    : request term via SIGTTIN for input thread 'imfile' 0xf58a0700

Program received signal SIGTTIN, Stopped (tty input).
[Switching to Thread 0x7ffff58a0700 (LWP 30651)]
0x00007ffff79b882d in read () from /lib64/libpthread.so.0
(gdb) cont
Continuing.
2061.552217777:imfile.c       : imfile: error during inotify: Interrupted system call
2061.552244354:imfile.c       : imfile: terminating upon request of rsyslog core
2061.552249598:imfile.c       : thrdStarter: usrThrdMain imfile - 0x7ffff58a0700 returned with iRet 0, exiting now.
2061.552401891:main thread    : non-cancel input thread termination succeeded for thread imfile 0xf58a0700
2061.554084841:imfile.c       : destructor for debug call stack 0x7ffff00008c0 called
2061.554541294:main thread    : imfile: lstnDel called for /opt/rsyslog-imfile/var/test.log
2061.554549389:main thread    : imfile: persisting state for '/opt/rsyslog-imfile/var/test.log' to file 'imfile-state:-opt-rsyslog-imfile-var-test.log'
2061.554557482:main thread    : file stream imfile-state:-opt-rsyslog-imfile-var-test.log params: flush interval 0, async write 0
[Thread 0x7ffff58a0700 (LWP 30651) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7feb740 (LWP 30648)]
0x000000000043d879 in strmSerialize (pThis=0xffffffffffffffff, pStrm=0x6e7bb0) at stream.c:1975
1975        ISOBJ_TYPE_assert(pThis, strm);
(gdb) bt full
#0  0x000000000043d879 in strmSerialize (pThis=0xffffffffffffffff, pStrm=0x6e7bb0) at stream.c:1975
        iRet = RS_RET_OK
        i = 0
        l = 140737488347184
        __PRETTY_FUNCTION__ = "strmSerialize"
#1  0x00007ffff65e899f in persistStrmState (pLstn=0x6dfed0) at imfile.c:1966
        iRet = RS_RET_OK
        psSF = 0x6e7bb0
        lenDir = 26
        statefile = "imfile-state:-opt-rsyslog-imfile-var-test.log\000\000\000\020\000\000\000\060\000\000\000@\341\377\377\377\177\000\000\200\340\377\377\377\177\000\000<\000\000\000\000\000\000\000P~k\000\000\000\000\000@\215m\000\000\000\000\000&\212^\366\377\177\000\000P\"\274\367\377\177\000\000\000\000\000\000\000\000\000\000r thread\005", '\000' <repeats 23 times>, "8\302\232\367\377\177", '\000' <repeats 19 times>, "\a\212\365\377\177\000\000\304\"\233\367\377\177\000\000@\344\377\377\377\177\000"
        statefn = 0x7fffffffe030 "imfile-state:-opt-rsyslog-imfile-var-test.log"
#2  0x00007ffff65e53b2 in lstnDel (pLstn=0x6dfed0) at imfile.c:872
No locals.
#3  0x00007ffff65e8a4a in afterRun () at imfile.c:1993
        iRet = RS_RET_OK
#4  0x0000000000458564 in thrdDestruct (pThis=0x6e6ca0) at ../threads.c:87
        iRet = RS_RET_OK
        __PRETTY_FUNCTION__ = "thrdDestruct"
#5  0x00000000004266d2 in llDestroyElt (pList=0x6c1a80, pElt=0x6e6fa0) at linkedlist.c:77
        iRet = RS_RET_OK
        __PRETTY_FUNCTION__ = "llDestroyElt"
#6  0x0000000000426795 in llDestroy (pThis=0x6c1a80) at linkedlist.c:108
        iRet = RS_RET_OK
        pElt = 0x6e6fa0
        __PRETTY_FUNCTION__ = "llDestroy"
#7  0x00000000004588a6 in thrdTerminateAll () at ../threads.c:173
        iRet = RS_RET_OK
#8  0x00000000004651fe in deinitAll () at rsyslogd.c:1576
        buf = '\000' <repeats 80 times>"\310, \342\377\377\377\177\000\000(\250\237\366\377\177", '\000' <repeats 18 times>, "@\343\377\377\377\177\000\000\340\357@\000\000\000\000\000@\344\377\377\377\177\000\000\325\031\337\367\377\177\000\000 \343\377\377\377\177", '\000' <repeats 26 times>, "\001\000\000\000\000\000\000\000 \343\377\377\377\177\000\000g to reg/U\255\366\377\177\000\000\000\000\000\000\000\000\000\000\341PF", '\000' <repeats 13 times>, "n\000\000\000\000\000\000\000V\002\000\000\000\000\000\000\060\061\v\000\000\000\000"
#9  0x00000000004653fc in main (argc=6, argv=0x7fffffffe448) at rsyslogd.c:1655
No locals.
(gdb) 
```

**Comment by mostolog** [comment]
Using 8.22 with debugging enabled I'm unable to reproduce this issue. Maybe it worth saying I'm using MaxMessageSize="32k".

Could you also try with 8.22?

**Comment by asuwarnapati** [comment]
Hi,

Upgrade to rsyslogd 8.22 solves this issue.

Thanks!

**Comment by mostolog** [comment]
Glad to hear. :)
