### ISSUE TITLE
rsyslog crash reading empty lines / rsyslogd: stringbuf.c:287: rsCStrAppendStrWithLen: Assertion `psz != NULL' failed.

### ISSUE THREAD

**Issue by mostolog** [rsyslog/rsyslog#1240]
While trying to fix https://github.com/rsyslog/rsyslog/issues/1221 I have found the following problem:

Running rsyslog compiled with debug and the attached file, I'm getting:
```
1666.637012577:imfile.c       : strm 0x7f50300059d0: file 8 read 59 bytes
rsyslogd: stringbuf.c:287: rsCStrAppendStrWithLen: Assertion `psz != NULL' failed.
Aborted (core dumped)
```

Don't hesitate to request any information you may need.

[file.log.txt](https://github.com/rsyslog/rsyslog/files/566718/file.log.txt)

**Comment by mostolog** [comment]
Similar to the other issue, here's the trace:
```
8236.377772445:imfile.c       : imfile: working in inotify mode
8236.377776916:main thread    : rsyslogd: writing pidfile '/var/run/rsyslogd.pid.tmp'.
8236.377788743:imfile.c       : imfile: added to dirs table: '/logs/apps/app'
8236.377803348:imfile.c       : imfile: inotify fd 7
8236.377822247:imfile.c       : imfile: enter into wdmap[0]: wd 1, dir 0, lstn DIRECTORY:/logs/apps/app
8236.377828525:imfile.c       : imfile: watch 1 added for dir /logs/apps/app
8236.377833316:imfile.c       : imfile: adding file '/logs/apps/app/app.log' to configured table
8236.377839439:imfile.c       : imfile: associated file [/logs/apps/app/app.log] to directory 0[/logs/apps/app], Active = 0
8236.377850155:imfile.c       : ratelimit:imfile[/logs/apps/app/app.log]:new ratelimiter:bReduceRepeatMsgs 0
8236.377875255:imfile.c       : imfile: enter into wdmap[1]: wd 2, dir -1, lstn FILE:/logs/apps/app/app.log
8236.377881959:imfile.c       : imfile: watch 2 added for file /logs/apps/app/app.log
8236.377887634:imfile.c       : imfile: associated file [/logs/apps/app/app.log] to directory 0[/logs/apps/app], Active = 1
8236.377897263:imfile.c       : imfile: trying to open state for '/logs/apps/app/app.log', state file 'imfile-state:-logs-apps-app-app.log'
8236.377906932:imfile.c       : imfile: clean startup, state file for '/logs/apps/app/app.log'
8236.377914045:imfile.c       : file stream /logs/apps/app/app.log params: flush interval 0, async write 0
8236.377931506:main thread    : rsyslogd: initialization completed, transitioning to regular run mode
8236.377959361:imfile.c       : file '/logs/apps/app/app.log' opened as #6 with mode 384
8236.377975066:imfile.c       : strm 0x7ffff00059d0: opened file '/logs/apps/app/app.log' for READ as 6
8236.377983424:imfile.c       : strm 0x7ffff00059d0: file 6 read 59 bytes
rsyslogd: stringbuf.c:287: rsCStrAppendStrWithLen: Assertion `psz != NULL' failed.

Thread 2 "in:imfile" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff4cac700 (LWP 20621)]
0x00007ffff69e8428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

(gdb) thread apply all bt full

Thread 2 (Thread 0x7ffff4cac700 (LWP 20621)):
#0  0x00007ffff69e8428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
        resultvar = 0
        pid = 20617
        selftid = 20621
#1  0x00007ffff69ea02a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x4, sa_sigaction = 0x4}, sa_mask = {__val = {0, 0, 140737300304848, 107374182400, 
              140737354092544, 4713151, 287, 4713840, 4, 0, 140737331292556, 140737332389464, 140737332403120, 3761414122575114801, 
              140737332389464, 4713151}}, sa_flags = -134262784, sa_restorer = 0x47eabf}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff69e0bd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x47eabf "psz != NULL", 
    file=file@entry=0x47ea75 "stringbuf.c", line=line@entry=287, 
    function=function@entry=0x47ed70 <__PRETTY_FUNCTION__.8919> "rsCStrAppendStrWithLen") at assert.c:92
        str = 0x7ffff000e9d0 ""
        total = 4096
#3  0x00007ffff69e0c82 in __GI___assert_fail (assertion=assertion@entry=0x47eabf "psz != NULL", file=file@entry=0x47ea75 "stringbuf.c", 
    line=line@entry=287, function=function@entry=0x47ed70 <__PRETTY_FUNCTION__.8919> "rsCStrAppendStrWithLen") at assert.c:101
---Type <return> to continue, or q <return> to quit---
No locals.
#4  0x0000000000424929 in rsCStrAppendStrWithLen (pThis=0x7ffff000e7d0, psz=0x0, iStrLen=0) at stringbuf.c:287
        pdbgFuncDB = 0x7ffff000e830
        dbgCALLStaCK_POP_POINT = <optimized out>
        __func__ = "rsCStrAppendStrWithLen"
        iRet = RS_RET_OK
        __PRETTY_FUNCTION__ = "rsCStrAppendStrWithLen"
#5  0x00000000004249ad in cstrAppendCStr (pThis=<optimized out>, pstrAppend=<optimized out>) at stringbuf.c:319
No locals.
#6  0x0000000000439d85 in strmReadMultiLine (pThis=0x7ffff00059d0, ppCStr=ppCStr@entry=0x7ffff4ca9600, preg=preg@entry=0x7ffff0002f18, 
    bEscapeLF=1 '\001') at stream.c:919
        isMatch = <optimized out>
        c = 10 '\n'
        finished = 0 '\000'
        thisLine = 0x7ffff00084f0
        readCharRet = <optimized out>
        pdbgFuncDB = 0x7ffff0005c90
        dbgCALLStaCK_POP_POINT = 4
        __func__ = "strmReadMultiLine"
---Type <return> to continue, or q <return> to quit---
        iRet = RS_RET_OK
        __PRETTY_FUNCTION__ = "strmReadMultiLine"
#7  0x00007ffff4cb1c7e in pollFile (pLstn=pLstn@entry=0x7ffff0002ea0, pbHadFileData=pbHadFileData@entry=0x0) at imfile.c:627
        nProcessed = 0
        __cancel_buf = {__cancel_jmp_buf = {{__cancel_jmp_buf = {140737219931808, 5277590373889246899, 140737300306224, 140737300306216, 
                7361328, 140737300339376, -5277605310514297165, -5277605315136813389}, __mask_was_saved = 0}}, __pad = {0x7ffff4cabef0, 0x0, 
            0x7ffff4cb0a55 <dirsAddFile+309>, 0x2}}
        __cancel_routine = 0x7ffff4cb08c0 <pollFileCancelCleanup>
        __not_first_call = <optimized out>
        pCStr = 0x0
        pdbgFuncDB = 0x7ffff0005ea0
        dbgCALLStaCK_POP_POINT = 3
        __func__ = "pollFile"
        iRet = RS_RET_OK
#8  0x00007ffff4cb24a8 in startLstnFile (pLstn=0x7ffff0002ea0) at imfile.c:1507
        localRet = <optimized out>
        wd = 2
#9  0x00007ffff4cb31f8 in in_setupFileWatchStatic (pLstn=0x7ffff0002ea0) at imfile.c:1632
No locals.
---Type <return> to continue, or q <return> to quit---
#10 in_setupInitialWatches () at imfile.c:1649
        i = <optimized out>
        pLstn = 0x705330
#11 do_inotify () at imfile.c:1872
        iobuf = '\000' <repeats 7240 times>...
        ev = <optimized out>
        rd = <optimized out>
        currev = <optimized out>
        pdbgFuncDB = 0x7ffff0002300
        dbgCALLStaCK_POP_POINT = 2
        __func__ = "do_inotify"
        iRet = <optimized out>
#12 0x00007ffff4cb343c in runInput (pThrd=<optimized out>) at imfile.c:1918
        pdbgFuncDB = 0x7ffff00021b0
        dbgCALLStaCK_POP_POINT = 1
        __func__ = "runInput"
        iRet = RS_RET_OK
#13 0x00000000004544e8 in thrdStarter (arg=0x711480) at ../threads.c:221
        pdbgFuncDB = 0x7ffff0002080
---Type <return> to continue, or q <return> to quit---
        dbgCALLStaCK_POP_POINT = 0
        __func__ = "thrdStarter"
        iRet = RS_RET_OK
        pThis = 0x711480
        thrdName = "in:imfile", '\000' <repeats 22 times>
        __PRETTY_FUNCTION__ = "thrdStarter"
        sigSet = {__val = {1048576, 0 <repeats 15 times>}}
#14 0x00007ffff79a770a in start_thread (arg=0x7ffff4cac700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7ffff4cac700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737300317952, 5277590373889509043, 1, 140737488347471, 140737300318656, 
                140737300339376, -5277605309669144909, -5277608193475836237}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, 
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
---Type <return> to continue, or q <return> to quit---
#15 0x00007ffff6ab982d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 1 (Thread 0x7ffff7feb780 (LWP 20617)):
#0  0x00007ffff6aaf9e3 in select () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x000000000040e129 in mainloop () at rsyslogd.c:1522
        tvSelectTimeout = {tv_sec = 599, tv_usec = 998835}
        tTime = 7013176
        dbgCALLStaCK_POP_POINT = 0
        pdbgFuncDB = 0x711880
#2  main (argc=<optimized out>, argv=<optimized out>) at rsyslogd.c:1664
        log_dflt = <optimized out>
```

**Comment by mostolog** [comment]
This issue was opened because I had several crashes when reading files which contained empty/blank lines.

Processing same files with 8.23 doesn't seem to have those errors. Sadly, I'm still getting a few "queue messages lost".

I'll keep you updated.

**Comment by mostolog** [comment]
@rgerhards I think this might be solved, as we haven’t seen any other errors in the last months
