### ISSUE TITLE
segmentation fault with broken queue files on 8.24

### ISSUE THREAD

**Issue by kortemik** [rsyslog/rsyslog#1469]
Hello,

We had a crash on the process and therefore the queue files are in inconsistent state. However the startup does not recognize them as broken as there is no usual "rsyslogd: fatal error on disk queue 'queue name here' , emergency switch to direct mode [v8.24.0 try http://www.rsyslog.com/e/2040 ]"

I managed to reproduce this so here is the back trace from gdb.

```
#0  0x0000555555581355 in rsCStrDestruct (ppThis=0x7fffc4012c88) at stringbuf.c:216
        pThis = 0x6342e12100302
#1  0x00005555555981cc in varDestruct (ppThis=0x7fffe15b4930) at var.c:72
        iRet = RS_RET_OK
        pThis = 0x7fffc4012c60
        __PRETTY_FUNCTION__ = "varDestruct"
#2  0x0000555555577097 in MsgDeserialize (pMsg=0x7fffc4012920, pStrm=0x5555559282a0) at msg.c:1405
        myProp = 0x55582379
        propRcvFrom = 0x0
        propRcvFromIP = 0x0
        tokener = 0x7fffe15b4970
        pVar = 0x7fffc4012c60
        iRet = RS_RET_INVALID_DELIMITER
        __PRETTY_FUNCTION__ = "MsgDeserialize"
#3  0x000055555558b6cf in objDeserializeWithMethods (ppObj=0x7fffe15b4a80, pszTypeExpected=0x5555555eb306 "msg", lenTypeExpected=3, pStrm=0x5555559282a0, fFixup=0x0, pUsr=0x0, 
    objConstruct=0x555555575517 <msgConstructForDeserializer>, objConstructFinalize=0x0, objDeserialize=0x5555555764e4 <MsgDeserialize>) at obj.c:915
        iRet = RS_RET_OK
        iRetLocal = RS_RET_OK
        pObj = 0x7fffc4012920
        oVers = 1
        pstrID = 0x7fffc400d560
        __PRETTY_FUNCTION__ = "objDeserializeWithMethods"
#4  0x000055555559d9c3 in qDeqDisk (pThis=0x555555877a00, ppMsg=0x7fffe15b4a80) at queue.c:988
        iRet = RS_RET_OK
#5  0x000055555559dbf4 in qqueueDeq (pThis=0x555555877a00, ppMsg=0x7fffe15b4a80) at queue.c:1115
        iRet = RS_RET_OK
#6  0x000055555559f1c4 in DequeueConsumableElements (pThis=0x555555877a00, pWti=0x55555592aa60, piRemainingQueueSize=0x7fffe15b4b08, pSkippedMsgs=0x7fffe15b4b70) at queue.c:1713
        rd_fd = 1
        rd_offs = 265987
        wr_fd = 1
        wr_offs = 266412
        nDequeued = 0
        nDiscarded = 0
        nDeleted = 1
        iQueueSize = 1
        pMsg = 0x55555592baf0
        localRet = RS_RET_OK
        iRet = RS_RET_OK
#7  0x000055555559f39f in DequeueConsumable (pThis=0x555555877a00, pWti=0x55555592aa60, pSkippedMsgs=0x7fffe15b4b70) at queue.c:1767
        iRet = RS_RET_OK
        iQueueSize = 0
---Type <return> to continue, or q <return> to quit---
#8  0x000055555559f7eb in DequeueForConsumer (pThis=0x555555877a00, pWti=0x55555592aa60, pSkippedMsgs=0x7fffe15b4b70) at queue.c:1919
        iRet = RS_RET_OK
        __PRETTY_FUNCTION__ = "DequeueForConsumer"
#9  0x000055555559fa91 in ConsumerReg (pThis=0x555555877a00, pWti=0x55555592aa60) at queue.c:1975
        iCancelStateSave = 0
        bNeedReLock = 0
        skippedMsgs = 0
        iRet = RS_RET_OK
        __PRETTY_FUNCTION__ = "ConsumerReg"
#10 0x000055555559ab53 in wtiWorker (pThis=0x55555592aa60) at wti.c:365
        __cancel_buf = {__cancel_jmp_buf = {{__cancel_jmp_buf = {140736974247680, -8834310304474543541, 1, 140736974248384, 140736974247680, 140737152844000, -8834310304283702709, 
                -3444319609500939701}, __mask_was_saved = 0}}, __pad = {0x7fffe15b4c90, 0x0, 0x0, 0x0}}
        __cancel_routine = 0x55555559a706 <wtiWorkerCancelCleanup>
        __cancel_arg = 0x55555592aa60
        __not_first_call = 0
        pWtp = 0x55555592a8d0
        pAction = 0x0
        bInactivityTOOccured = 0
        localRet = RS_RET_OK
        terminateRet = RS_RET_OK
        wrkrInfo = 0x0
        iCancelStateSave = 0
        i = 32767
        j = -514110208
        k = 0
        iRet = RS_RET_OK
#11 0x000055555559958f in wtpWorker (arg=0x55555592aa60) at wtp.c:410
        __cancel_buf = {__cancel_jmp_buf = {{__cancel_jmp_buf = {140736974247680, -8834310304487126453, 1, 140736974248384, 140736974247680, 140737152844000, -8834310304447280565, 
                -3444319610538636725}, __mask_was_saved = 0}}, __pad = {0x7fffe15b4df0, 0x0, 0x0, 0x0}}
        __cancel_routine = 0x55555559914d <wtpWrkrExecCancelCleanup>
        __cancel_arg = 0x55555592aa60
        __not_first_call = 0
        pWti = 0x55555592aa60
        pThis = 0x55555592a8d0
        sigSet = {__val = {1048576, 0 <repeats 15 times>}}
        pszDbgHdr = 0x55555592aa20 "action 36 queue:Reg"
        thrdName = "rs:action 36 queue:Reg\000\000\000\000\000\000\000\000\000"
        __PRETTY_FUNCTION__ = "wtpWorker"
```

**Comment by rgerhards** [comment]
The queue code in 8.25 has even further been improved in regard to reliability. If possible, it would be good if you could try to reproduce. I close the tracker for the time being, but if you can reproduce, please let us know.
