### ISSUE TITLE
Extremely Emergency: Rsyslog 8.29.0 crashes in template.c frequently

### ISSUE THREAD

**Issue by zacharyzhao** [rsyslog/rsyslog#1730]
## Runtime Environment

- OS: CentOS release 6.6 (Final)
- Rsyslog Version: v8.29.0

## Case Description

Rsyslog plays the role of `collecter` and `forwarder` in our case, `rsyslog collecter` collects logs on clients' host, and transfers them to `rsyslog forwarder` through `omrelp` with TLS.

Exactly, `Rsyslog forwarder` is a cluster behind `haproxy`, thousands of `rsyslog collecter`s send messages to `haproxy` and `haproxy` distributes messages to `rsyslog forwarder` instances.

We supervise `rsyslog forwarder` instances by `runit`, which will boot `rsyslog forwarder` instance up as soon as it crashes, so we haven`t found the problem for a long time. But finally it was discovered.

### Core Dump File

Core dump file and binary file `rsyslogd` are shared on dropbox:

[core dump file](https://www.dropbox.com/s/g61fwd9ril28tyo/core.1730.tar.gz?dl=0)
[rsyslogd](https://www.dropbox.com/s/r27lldrjhhv4azp/rsyslogd.tar.gz?dl=0)

### Back Trace Overview

```
#0  0x0000003f0d689691 in memcpy () from /lib64/libc.so.6
#1  0x000000000046f159 in tplToString (pTpl=0x15a6ab0, pMsg=0x7fd87413a040, iparam=0x15b73f0,
    ttNow=0x7fd861510bd0) at ../template.c:227
#2  0x0000000000466a94 in prepareDoActionParams (pAction=0x15a88a0, pWti=0x15b7310,
    pMsg=0x7fd87413a040, ttNow=0x7fd861510bd0) at ../action.c:981
#3  processMsgMain (pAction=0x15a88a0, pWti=0x15b7310, pMsg=0x7fd87413a040, ttNow=0x7fd861510bd0)
    at ../action.c:1372
#4  0x0000000000467348 in processBatchMain (pVoid=0x15a88a0, pBatch=0x15b7348, pWti=0x15b7310)
    at ../action.c:1416
#5  0x000000000045ab4c in ConsumerReg (pThis=0x15a8af0, pWti=0x15b7310) at queue.c:2005
#6  0x0000000000454a81 in wtiWorker (pThis=0x15b7310) at wti.c:365
#7  0x00000000004535bc in wtpWorker (arg=0x15b7310) at wtp.c:417
#8  0x0000003f0da079d1 in start_thread () from /lib64/libpthread.so.0
#9  0x0000003f0d6e89dd in clone () from /lib64/libc.so.6
```

### Frame 1

```
(gdb) f 1
#1  0x000000000046f159 in tplToString (pTpl=0x15a6ab0, pMsg=0x7fd87413a040, iparam=0x15b73f0,
    ttNow=0x7fd861510bd0) at ../template.c:227
227                             memcpy(iparam->param + iBuf, pVal, iLenVal);
(gdb) p iparam->param
$29 = (uchar *) 0x0
(gdb)
```
We can see base address `iparam->param` is 0x0, an invalid address.

### Frame 2

```
(gdb) f 2
#2  0x0000000000466a94 in prepareDoActionParams (pAction=0x15a88a0, pWti=0x15b7310,
    pMsg=0x7fd87413a040, ttNow=0x7fd861510bd0) at ../action.c:981
981                                     CHKiRet(tplToString(pAction->ppTpl[i], pMsg,
(gdb) p pAction->iNumTpls
$32 = 2
(gdb) p pWrkrInfo->p.nontx.actParams[0]
$33 = {
  param = 0x7fd8340026e0 "XXXXXXXXXXXX",
  lenBuf = 256, lenStr = 173}
(gdb) p pWrkrInfo->p.nontx.actParams[1]
$34 = {param = 0x0, lenBuf = 128, lenStr = 10}
(gdb)
```
Here `pWrkrInfo->p.nontx.actParams[0]` is ok, but `pWrkrInfo->p.nontx.actParams[1]` is not.

### Frame 7

```
(gdb) f 7
#7  0x00000000004535bc in wtpWorker (arg=0x15b7310) at wtp.c:417
417     wtp.c: No such file or directory.
        in wtp.c
(gdb) p pWti
$44 = (wti_t *) 0x15b7310
(gdb) p *pWti->actWrkrInfo
$45 = {pAction = 0x15a88a0, actWrkrData = 0x0, uResumeOKinRow = 0, iNbrResRtry = 0, flags = {
    actState = 0, bJustResumed = 0}, p = {tx = {iparams = 0x7fd8340026e0, currIParam = 256,
      maxIParams = 173}, nontx = {actParams = {{
          param = 0x7fd8340026e0 "hb-pub-dns1-01,17-Aug-2017 15:10:09.793 client 172.19.7.3#29868 (www.zkproxy.jcloud.com): view view_internals_huabei: query: www.zkproxy.jcloud.com IN AAAA +E (172.19.0.252)",lenBuf = 256, lenStr = 173}, {param = 0x0, lenBuf = 128, lenStr = 10}, {param = 0x0, lenBuf = 0,
          lenStr = 0}, {param = 0x0, lenBuf = 0, lenStr = 0}, {param = 0x0, lenBuf = 0, lenStr = 0}}}}}
(gdb)
```

## Online Configuration Template

```
$WorkDirectory __RUNTIME_DIR__

template(name="format_raw" type="list") {
            property(name="rawmsg")
}

template(name="format_raw_with_fold" type="list") {
            property(name="rawmsg")
            constant(value="\n")
}

module(load="imrelp")
module(load="omkafka")

main_queue(
           queue.type="LinkedList"
           queue.size="65536000"
           queue.spoolDirectory="__RUNTIME_DIR__"
           queue.saveonshutdown="on"
           queue.dequeuebatchsize="1024"
           queue.dequeueslowdown="0"
           queue.highwatermark="49152000"
           queue.lowwatermark="32768000"
           queue.maxfilesize="8G"
           queue.maxdiskspace="256G"
           queue.workerthreads="256"
           queue.workerthreadminimummessages="32"
)

ruleset(name="fwd-deeplog-kafka-lb") {
           action(type="omkafka"
           template="format_raw"
           broker=["__KAFKA_BROKER_LIST__"]
           partitions.auto="on"
           topic="__KAFKA_TOPIC__"
           errorFile="__INSTALL_DIR__/var/log/kafka_error.log"
           confParam=["topic.metadata.refresh.sparse=true",
                      "queued.max.messages.kbytes=100000000",
                      "message.send.max.retries=10",
                      "receive.message.max.bytes=100000000",
                      "socket.send.buffer.bytes=10000000",
                      "socket.receive.buffer.bytes=10000000",
                      "socket.keepalive.enable=true",
                      "batch.num.messages=1000000",
                      "fetch.wait.max.ms=0",
                      "fetch.message.max.bytes=100000000",
                      "compression.codec=snappy",
                      "broker.version.fallback=0.8.2.1"]
           action.resumeRetryCount="-1"
           queue.type="LinkedList"
           queue.size="6553600"
           queue.saveonshutdown="on"
           queue.dequeuebatchsize="1024"
           queue.dequeueslowdown="0"
           queue.workerthreads="256"
           queue.workerthreadminimummessages="32"
          )
}

ruleset(name="handle-imrelp-lb") {
        call fwd-deeplog-kafka-lb
}

input(
        type="imrelp"
        name="lb"
        port="30000"
        ruleset="handle-imrelp-lb"
        KeepAlive="on"
        tls="on"
        tls.compression="on"
        tls.authMode="name"
        tls.dhbits="2048"
        tls.caCert="__INSTALL_DIR__/cert/ca_public_certificate.pem"
        tls.myCert="__INSTALL_DIR__/cert/fwd.public.pem"
        tls.myPrivKey="__INSTALL_DIR__/cert/fwd.private.key.pem"
        tls.permittedpeer=["lb"]
)

```

## Summary

It seems that an worker thread instance was created with an incorrect argument, which had only one valid `actParam`, other `actParam`'s member variable `param` was 0x0, and this illegal base address causes `rsyslog`'s segment fault crash.

Probably, this is a serious bug, I will follow this issue and try to fix it. However I hope it could be solved by official **ASAP**.

**Comment by zacharyzhao** [comment]
@rgerhards 

Your attention to the issue is much appreciated. 

Thanks in advance.

**Comment by rgerhards** [comment]
> Your prompt attention to the issue is much appreciated.

Sorry, I am currently very limited in my time. I just wrote it up so that everyone knows what's going on: http://blog.gerhards.net/2017/08/busy-at-moment.html

Nevertheless, I'll try to look at this ASAP, but I can't promise on the timeframe :-(

Can you run rsyslog under valgrind? Can you also enable debug log, so that I can see what happened before it aborts?

**Comment by rgerhards** [comment]
@zacharyzhao did you try valgrind? or is this solved?

**Comment by rgerhards** [comment]
I assume it's solved by now given that we have no response and a couple of fixes went into rsyslog in the interim which could be solutions. If it still persists, let me know and I will re-open.
