### ISSUE TITLE
lookup tables: issues detected by UBSan

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#2295]
### Brief summary (in order of potential importance):
```
lookup.c:304:29: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/stdlib.h:757:6: note: nonnull attribute specified here

lookup.c:286:24: runtime error: unsigned integer overflow: 0 - 3 cannot be represented in type 'unsigned int'
lookup.c:259:42: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned int'
```
### Full log (in order of appearance):
```
===============================================================================
[array_lookup_table.sh]: test for array lookup-table and HUP based reloading of it
------------------------------------------------------------
Test: ./array_lookup_table.sh
------------------------------------------------------------
rsyslogd: lookup table named: 'xlate' doesn't specify version (will use default value: 1) [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
rsyslogd started, start msg not yet seen, pid  23080
rsyslogd startup msg seen, pid  23080
injecting 3 messages
imdiag[13500]: 3 messages injected
imdiag[13500]: mainqueue empty
rsyslogd: lookup table named: 'xlate' doesn't specify version (will use default value: 1) [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
lookup.c:259:42: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned int'
    #0 0x4d829a in qs_arrcmp_uint32_index_val /home/travis/build/rgerhards/rsyslog/runtime/lookup.c:259:42
    #1 0x2ba1af6a8294 in msort_with_tmp /build/eglibc-SvCtMH/eglibc-2.19/stdlib/msort.c:105
    #2 0x2ba1af6a8187 in msort_with_tmp /build/eglibc-SvCtMH/eglibc-2.19/stdlib/msort.c:45
    #3 0x2ba1af6a8187 in msort_with_tmp /build/eglibc-SvCtMH/eglibc-2.19/stdlib/msort.c:54
    #4 0x2ba1af6a86cb in msort_with_tmp /build/eglibc-SvCtMH/eglibc-2.19/stdlib/msort.c:45
    #5 0x2ba1af6a86cb in qsort_r /build/eglibc-SvCtMH/eglibc-2.19/stdlib/msort.c:297
    #6 0x4d6963 in build_ArrayTable /home/travis/build/rgerhards/rsyslog/runtime/lookup.c:460:3
    #7 0x4d6963 in lookupBuildTable_v1 /home/travis/build/rgerhards/rsyslog/runtime/lookup.c:611
    #8 0x4d6963 in lookupBuildTable /home/travis/build/rgerhards/rsyslog/runtime/lookup.c:644
    #9 0x4d6963 in lookupReadFile /home/travis/build/rgerhards/rsyslog/runtime/lookup.c:923
    #10 0x4d7fc1 in lookupReloadOrStub /home/travis/build/rgerhards/rsyslog/runtime/lookup.c:691:3
    #11 0x4d7cea in lookupDoReload /home/travis/build/rgerhards/rsyslog/runtime/lookup.c:799:9
    #12 0x4d7cea in lookupTableReloader /home/travis/build/rgerhards/rsyslog/runtime/lookup.c:818
    #13 0x2ba1ae51b183 in start_thread /build/eglibc-SvCtMH/eglibc-2.19/nptl/pthread_create.c:312
    #14 0x2ba1af76affc in clone /build/eglibc-SvCtMH/eglibc-2.19/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:111
FAIL: sparse_array_lookup_table.sh
==================================
Linux
===============================================================================
[sparse_array_lookup_table.sh]: test for sparse-array lookup-table and HUP based reloading of it
rsyslog.pid exists, trying to shut down rsyslogd process 23080.
./killrsyslog.sh: line 6: kill: (23080) - No such process
------------------------------------------------------------
Test: ./sparse_array_lookup_table.sh
------------------------------------------------------------
rsyslogd: lookup table named: 'xlate' doesn't specify version (will use default value: 1) [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
lookup.c:286:24: runtime error: unsigned integer overflow: 0 - 3 cannot be represented in type 'unsigned int'
rsyslogd started, start msg not yet seen, pid  23214
    #0 0x4d85e6 in bs_arrcmp_sprsArrtab /home/travis/build/rgerhards/rsyslog/runtime/lookup.c:286:24
    #1 0x4d85e6 in bsearch_lte /home/travis/build/rgerhards/rsyslog/runtime/lookup.c:345
    #2 0x4d85e6 in lookupKey_sprsArr /home/travis/build/rgerhards/rsyslog/runtime/lookup.c:366
    #3 0x4d53e8 in lookupKey /home/travis/build/rgerhards/rsyslog/runtime/lookup.c:865:9
    #4 0x45e60d in doFuncCall /home/travis/build/rgerhards/rsyslog/grammar/rainerscript.c:2345:18
    #5 0x4580f9 in cnfexprEval /home/travis/build/rgerhards/rsyslog/grammar/rainerscript.c:3113:3
    #6 0x4d1dc0 in execSet /home/travis/build/rgerhards/rsyslog/runtime/ruleset.c:228:2
    #7 0x4d1dc0 in scriptExec /home/travis/build/rgerhards/rsyslog/runtime/ruleset.c:600
    #8 0x4d07f9 in processBatch /home/travis/build/rgerhards/rsyslog/runtime/ruleset.c:658:14
    #9 0x42d547 in msgConsumer /home/travis/build/rgerhards/rsyslog/tools/rsyslogd.c:698:2
    #10 0x4c5984 in ConsumerReg /home/travis/build/rgerhards/rsyslog/runtime/queue.c:2016:2
    #11 0x4be271 in wtiWorker /home/travis/build/rgerhards/rsyslog/runtime/wti.c:366:14
    #12 0x4bab75 in wtpWorker /home/travis/build/rgerhards/rsyslog/runtime/wtp.c:415:2
    #13 0x2b4cd4488183 in start_thread /build/eglibc-SvCtMH/eglibc-2.19/nptl/pthread_create.c:312
    #14 0x2b4cd56d7ffc in clone /build/eglibc-SvCtMH/eglibc-2.19/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:111
ABORT! rsyslog pid no longer active during startup!
FAIL: lookup_table_bad_configs.sh
=================================
Linux
===============================================================================
[lookup_table_bad_configs.sh]: test for sparse-array lookup-table and HUP based reloading of it
rsyslog.pid exists, trying to shut down rsyslogd process 23214.
./killrsyslog.sh: line 6: kill: (23214) - No such process
------------------------------------------------------------
Test: ./lookup_table_bad_configs.sh
------------------------------------------------------------
empty file...
rsyslogd: lookup table file 'xlate.lkp_tbl' json parsing error [v8.32.0.master try http://www.rsyslog.com/e/2303 ]
rsyslogd started, start msg not yet seen, pid  23292
rsyslogd startup msg seen, pid  23292
injecting 5 messages
imdiag[13500]: 5 messages injected
imdiag[13500]: mainqueue empty
table with invalid-json...
rsyslogd: lookup table file 'xlate.lkp_tbl' json parsing error [v8.32.0.master try http://www.rsyslog.com/e/2303 ]
rsyslogd: lookup table 'xlate' could not be reloaded from file 'xlate.lkp_tbl' [v8.32.0.master try http://www.rsyslog.com/e/2175 ]
imdiag[13500]: no pending lookup-table reloads found
injecting 5 messages
imdiag[13500]: 5 messages injected
imdiag[13500]: mainqueue empty
string-table with no index-key...
rsyslogd: 'string' lookup table named: 'xlate' has record(s) without 'index' field [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
rsyslogd: lookup table 'xlate' could not be reloaded from file 'xlate.lkp_tbl' [v8.32.0.master try http://www.rsyslog.com/e/2175 ]
imdiag[13500]: no pending lookup-table reloads found
injecting 5 messages
imdiag[13500]: 5 messages injected
imdiag[13500]: mainqueue empty
array-table with no index-key...
rsyslogd: 'array' lookup table named: 'xlate' has record(s) without 'index' field [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
rsyslogd: lookup table 'xlate' could not be reloaded from file 'xlate.lkp_tbl' [v8.32.0.master try http://www.rsyslog.com/e/2175 ]
imdiag[13500]: no pending lookup-table reloads found
injecting 5 messages
imdiag[13500]: 5 messages injected
imdiag[13500]: mainqueue empty
sparse-array-table with no index-key...
rsyslogd: 'sparseArray' lookup table named: 'xlate' has record(s) without 'index' field [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
rsyslogd: lookup table 'xlate' could not be reloaded from file 'xlate.lkp_tbl' [v8.32.0.master try http://www.rsyslog.com/e/2175 ]
imdiag[13500]: no pending lookup-table reloads found
injecting 5 messages
imdiag[13500]: 5 messages injected
imdiag[13500]: mainqueue empty
string-table with no value...
rsyslogd: 'string' lookup table named: 'xlate' has record(s) without 'value' field [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
rsyslogd: lookup table 'xlate' could not be reloaded from file 'xlate.lkp_tbl' [v8.32.0.master try http://www.rsyslog.com/e/2175 ]
imdiag[13500]: no pending lookup-table reloads found
injecting 5 messages
imdiag[13500]: 5 messages injected
imdiag[13500]: mainqueue empty
array-table with no value...
rsyslogd: 'array' lookup table named: 'xlate' has record(s) without 'value' field [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
rsyslogd: lookup table 'xlate' could not be reloaded from file 'xlate.lkp_tbl' [v8.32.0.master try http://www.rsyslog.com/e/2175 ]
imdiag[13500]: no pending lookup-table reloads found
injecting 5 messages
imdiag[13500]: 5 messages injected
imdiag[13500]: mainqueue empty
sparse-array-table with no value...
rsyslogd: 'sparseArray' lookup table named: 'xlate' has record(s) without 'value' field [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
rsyslogd: lookup table 'xlate' could not be reloaded from file 'xlate.lkp_tbl' [v8.32.0.master try http://www.rsyslog.com/e/2175 ]
imdiag[13500]: no pending lookup-table reloads found
injecting 5 messages
imdiag[13500]: 5 messages injected
imdiag[13500]: mainqueue empty
incorrect-version in lookup-table...
rsyslogd: lookup table named: 'xlate' uses unsupported version: 3 [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
rsyslogd: lookup table 'xlate' could not be reloaded from file 'xlate.lkp_tbl' [v8.32.0.master try http://www.rsyslog.com/e/2175 ]
imdiag[13500]: no pending lookup-table reloads found
injecting 5 messages
imdiag[13500]: 5 messages injected
imdiag[13500]: mainqueue empty
incorrect-type in lookup-table...
rsyslogd: lookup table named: 'xlate' uses unupported type: 'quux' [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
rsyslogd: lookup table 'xlate' could not be reloaded from file 'xlate.lkp_tbl' [v8.32.0.master try http://www.rsyslog.com/e/2175 ]
imdiag[13500]: no pending lookup-table reloads found
injecting 5 messages
imdiag[13500]: 5 messages injected
imdiag[13500]: mainqueue empty
string-table with no table...
rsyslogd: lookup table named: 'xlate' has invalid table definition [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
rsyslogd: lookup table 'xlate' could not be reloaded from file 'xlate.lkp_tbl' [v8.32.0.master try http://www.rsyslog.com/e/2175 ]
imdiag[13500]: no pending lookup-table reloads found
injecting 5 messages
imdiag[13500]: 5 messages injected
imdiag[13500]: mainqueue empty
array-table with no table...
rsyslogd: lookup table named: 'xlate' has invalid table definition [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
rsyslogd: lookup table 'xlate' could not be reloaded from file 'xlate.lkp_tbl' [v8.32.0.master try http://www.rsyslog.com/e/2175 ]
imdiag[13500]: no pending lookup-table reloads found
injecting 5 messages
imdiag[13500]: 5 messages injected
imdiag[13500]: mainqueue empty
sparse-array-table with no table...
rsyslogd: lookup table named: 'xlate' has invalid table definition [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
rsyslogd: lookup table 'xlate' could not be reloaded from file 'xlate.lkp_tbl' [v8.32.0.master try http://www.rsyslog.com/e/2175 ]
imdiag[13500]: no pending lookup-table reloads found
injecting 5 messages
imdiag[13500]: 5 messages injected
imdiag[13500]: mainqueue empty
string-table with empty table...
rsyslogd: lookup table 'xlate' reloaded from file 'xlate.lkp_tbl' [v8.32.0.master try http://www.rsyslog.com/e/0 ]
lookup.c:304:29: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/stdlib.h:757:6: note: nonnull attribute specified here
    #0 0x4d8881 in lookupKey_str /home/travis/build/rgerhards/rsyslog/runtime/lookup.c:304:10
    #1 0x4d53e8 in lookupKey /home/travis/build/rgerhards/rsyslog/runtime/lookup.c:865:9
    #2 0x45e60d in doFuncCall /home/travis/build/rgerhards/rsyslog/grammar/rainerscript.c:2345:18
    #3 0x4580f9 in cnfexprEval /home/travis/build/rgerhards/rsyslog/grammar/rainerscript.c:3113:3
    #4 0x4d1dc0 in execSet /home/travis/build/rgerhards/rsyslog/runtime/ruleset.c:228:2
    #5 0x4d1dc0 in scriptExec /home/travis/build/rgerhards/rsyslog/runtime/ruleset.c:600
    #6 0x4d07f9 in processBatch /home/travis/build/rgerhards/rsyslog/runtime/ruleset.c:658:14
    #7 0x42d547 in msgConsumer /home/travis/build/rgerhards/rsyslog/tools/rsyslogd.c:698:2
    #8 0x4c5984 in ConsumerReg /home/travis/build/rgerhards/rsyslog/runtime/queue.c:2016:2
    #9 0x4be271 in wtiWorker /home/travis/build/rgerhards/rsyslog/runtime/wti.c:366:14
    #10 0x4bab75 in wtpWorker /home/travis/build/rgerhards/rsyslog/runtime/wtp.c:415:2
    #11 0x2b3face3e183 in start_thread /build/eglibc-SvCtMH/eglibc-2.19/nptl/pthread_create.c:312
    #12 0x2b3fae08dffc in clone /build/eglibc-SvCtMH/eglibc-2.19/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by rgerhards** [comment]
The NULL pointer use is inside a bsearch:
```
static es_str_t*
lookupKey_str(lookup_t *pThis, lookup_key_t key) {
	lookup_string_tab_entry_t *entry;
	const char *r;
	entry = bsearch(key.k_str, pThis->table.str->entries, pThis->nmemb, sizeof(lookup_string_tab_entry_t),
	bs_arrcmp_strtab);
```
This definitely is a bug, albeit it is properly handled on "the usual platform" - whatever that means.

**Comment by rgerhards** [comment]
@janmejay can you comment on the unsigned integer overflows?

They are
```
static int
qs_arrcmp_strtab(const void *s1, const void *s2)
{
	return ustrcmp(((lookup_string_tab_entry_t*)s1)->key, ((lookup_string_tab_entry_t*)s2)->key);
}
```
and
```
qs_arrcmp_sprsArrtab
```
It looks like unsigned arithmetic was deliberately chosen. So I wonder if that's a real bug or not. The bsearch I have fixed (PR upcoming).

**Comment by janmejay** [comment]
Its definitely a bug. #2302 fixes the unsigned underflow part of this issue.

**Comment by rgerhards** [comment]
Thx for the quick response! I'll merge later today. After that, I can also add UBSan to trust testbench runs.

Do you think this could be related to the bug that's not reproducible by us? I don't think so, but...

**Comment by janmejay** [comment]
It was a somewhat delayed response, sorry for that :-).

Atleast intuitively it doesn't seem related.

**Comment by rgerhards** [comment]
So let's see if the other changes we made will have good effect. I am positive about it, but we'll note I've folks use the new version. Thx again!

**Comment by rgerhards** [comment]
@janmejay sorry, another one after the merge:
```
FAIL: array_lookup_table.sh
===========================
Linux
===============================================================================
[array_lookup_table.sh]: test for array lookup-table and HUP based reloading of it
------------------------------------------------------------
Test: ./array_lookup_table.sh
------------------------------------------------------------
rsyslogd: lookup table named: 'xlate' doesn't specify version (will use default value: 1) [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
rsyslogd started, start msg not yet seen, pid  19234
rsyslogd startup msg seen, pid  19234
injecting 3 messages
imdiag[13500]: 3 messages injected
imdiag[13500]: mainqueue empty
rsyslogd: lookup table named: 'xlate' doesn't specify version (will use default value: 1) [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
rsyslogd: lookup table 'xlate' reloaded from file 'xlate_array.lkp_tbl' [v8.32.0.master try http://www.rsyslog.com/e/0 ]
imdiag[13500]: no pending lookup-table reloads found
injecting 3 messages
imdiag[13500]: 3 messages injected
imdiag[13500]: mainqueue empty
rsyslogd: lookup table named: 'xlate' doesn't specify version (will use default value: 1) [v8.32.0.master try http://www.rsyslog.com/e/2009 ]
rsyslogd: lookup table 'xlate' reloaded from file 'xlate_array.lkp_tbl' [v8.32.0.master try http://www.rsyslog.com/e/0 ]
lookup.c:337:26: runtime error: unsigned integer overflow: 0 - 2 cannot be represented in type 'unsigned int'
    #0 0x4d8445 in lookupKey_arr /home/travis/build/rgerhards/rsyslog/runtime/lookup.c:337:26
    #1 0x4d54d8 in lookupKey /home/travis/build/rgerhards/rsyslog/runtime/lookup.c:884:9
    #2 0x45e706 in doFuncCall /home/travis/build/rgerhards/rsyslog/grammar/rainerscript.c:2368:18
    #3 0x4580f9 in cnfexprEval /home/travis/build/rgerhards/rsyslog/grammar/rainerscript.c:3136:3
    #4 0x4d1eb0 in execSet /home/travis/build/rgerhards/rsyslog/runtime/ruleset.c:228:2
    #5 0x4d1eb0 in scriptExec /home/travis/build/rgerhards/rsyslog/runtime/ruleset.c:600
    #6 0x4d08e9 in processBatch /home/travis/build/rgerhards/rsyslog/runtime/ruleset.c:658:14
    #7 0x42d547 in msgConsumer /home/travis/build/rgerhards/rsyslog/tools/rsyslogd.c:698:2
    #8 0x4c5a74 in ConsumerReg /home/travis/build/rgerhards/rsyslog/runtime/queue.c:2016:2
    #9 0x4be361 in wtiWorker /home/travis/build/rgerhards/rsyslog/runtime/wti.c:366:14
    #10 0x4bac65 in wtpWorker /home/travis/build/rgerhards/rsyslog/runtime/wtp.c:415:2
    #11 0x2ae3870f9183 in start_thread /build/eglibc-SvCtMH/eglibc-2.19/nptl/pthread_create.c:312
    #12 0x2ae388348ffc in clone /build/eglibc-SvCtMH/eglibc-
```

**Comment by janmejay** [comment]
#2304 fixes it

**Comment by rgerhards** [comment]
@janmejay thx for the fixes, all is integrated and well now!
