### ISSUE TITLE
mmdblookup: improve code

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#2332]
untangling this from https://github.com/rsyslog/rsyslog/issues/1885 so that we get back to a focussed effort. @ycflash I would appreciate if you could subscribe to this issue here as well.

Quoting the posting from @horgh at https://github.com/rsyslog/rsyslog/issues/1885#issuecomment-346968052:

Yeah, the output from MMDB_dump_entry_data_list() has similarities to JSON but it's not valid JSON. It's mainly for debugging. The function str_split() in the plugin appears to try to turn it into JSON. I don't know how successful it would be. There are separate data lookup functions that would probably be better to use (once this is all figured out of course!).

**Comment by rgerhards** [comment]
We should also check if the result return code is properly passed. IIRC, @horgh said we should check same result status field for errors, but I right now cannot find the relevant posting. Maybe my memory is wrong .. definitely something to check in libmaxmindb doc.

**Comment by horgh** [comment]
There is a `found_entry` field that can be checked. The additional error check you mention may be checking the result of `MMDB_dump_entry_data_list()` (although if you plan to switch away from that function, that's not too important!). I think the [libmaxminddb issue](https://github.com/maxmind/libmaxminddb/issues/151#issuecomment-346459839) includes everything I noticed.

**Comment by ycflash** [comment]
Sure, @rgerhards .
If any test works needed, pls give me a word.

**Comment by frikilax** [comment]
Thought I would put that here instead of opening a new issue, but mmdblookup doesn't close properly when trying to open a non-existing file: this module juste continues on until libmaxminddb throws an assert fail()
![image](https://user-images.githubusercontent.com/33118448/70514902-b8bf1000-1b34-11ea-826c-5aa8bae4d824.png)

```
rsyslogd: maxminddb.c:1003: record_info_for_database: Assertion `false' failed.

Thread 1 "rsyslogd" received signal SIGTTOU, Stopped (tty output).
0x00007ffff6c9d03f in __GI___select (nfds=1, readfds=0x0, writefds=0x0, exceptfds=0x0, timeout=0x7fffffffe370)
    at ../sysdeps/unix/sysv/linux/select.c:41
41      ../sysdeps/unix/sysv/linux/select.c: Aucun fichier ou dossier de ce type.
(gdb) bt
#0  0x00007ffff6c9d03f in __GI___select (nfds=1, readfds=0x0, writefds=0x0, exceptfds=0x0, timeout=0x7fffffffe370) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x000055555556a124 in wait_timeout () at rsyslogd.c:1915
#2  mainloop () at rsyslogd.c:1946
#3  main (argc=<optimized out>, argv=<optimized out>) at rsyslogd.c:2134
(gdb) c
Continuing.
8668.835415859:main thread    : janitor.c: janitorRun() called

Thread 4 "rs:main Q:Reg" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffeffff700 (LWP 14631)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: Aucun fichier ou dossier de ce type.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6bc6801 in __GI_abort () at abort.c:79
#2  0x00007ffff6bb639a in __assert_fail_base (fmt=0x7ffff6d3d7d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7ffff5ecfb35 "false", file=file@entry=0x7ffff5ecfbe9 "maxminddb.c", line=line@entry=1003,
    function=function@entry=0x7ffff5ecfd30 "record_info_for_database") at assert.c:92
#3  0x00007ffff6bb6412 in __GI___assert_fail (assertion=0x7ffff5ecfb35 "false", file=0x7ffff5ecfbe9 "maxminddb.c", line=1003, function=0x7ffff5ecfd30 "record_info_for_database") at assert.c:101
#4  0x00007ffff5ecce03 in ?? () from /usr/lib/x86_64-linux-gnu/libmaxminddb.so.0
#5  0x00007ffff5ece466 in MMDB_lookup_sockaddr () from /usr/lib/x86_64-linux-gnu/libmaxminddb.so.0
#6  0x00007ffff5ece50e in MMDB_lookup_string () from /usr/lib/x86_64-linux-gnu/libmaxminddb.so.0
#7  0x00007ffff60d4c75 in doAction (pMsgData=<optimized out>, pWrkrData=0x7fffe4000b40) at mmdblookup.c:507
#8  0x00005555555c9d4b in actionCallDoAction (pWti=0x55555582c4b0, iparams=<optimized out>, pThis=0x55555582f450) at ../action.c:1266
#9  actionProcessMessage (pThis=0x55555582f450, actParams=0x55555582c580, pWti=0x55555582c4b0) at ../action.c:1308
#10 0x00005555555cb66f in processMsgMain (pAction=pAction@entry=0x55555582f450, pWti=pWti@entry=0x55555582c4b0, pMsg=pMsg@entry=0x7fffe80029a0, ttNow=ttNow@entry=0x7fffefffe9e0) at ../action.c:1657
#11 0x00005555555cba62 in doSubmitToActionQ (pAction=0x55555582f450, pWti=0x55555582c4b0, pMsg=0x7fffe80029a0) at ../action.c:1824
#12 0x00005555555c2c66 in execAct (stmt=0x55555582eff0, pWti=0x55555582c4b0, pMsg=0x7fffe80029a0) at ruleset.c:209
#13 scriptExec (root=<optimized out>, pMsg=pMsg@entry=0x7fffe80029a0, pWti=pWti@entry=0x55555582c4b0) at ruleset.c:599
#14 0x00005555555c353a in processBatch (pBatch=0x55555582c4e8, pWti=0x55555582c4b0) at ruleset.c:660
#15 0x000055555556aad1 in msgConsumer (notNeeded=<optimized out>, pBatch=0x55555582c4e8, pWti=0x55555582c4b0) at rsyslogd.c:693
#16 0x00005555555bd11a in ConsumerReg (pThis=0x55555582c010, pWti=0x55555582c4b0) at queue.c:2145
#17 0x00005555555b7d82 in wtiWorker (pThis=pThis@entry=0x55555582c4b0) at wti.c:428
#18 0x00005555555b5038 in wtpWorker (arg=0x55555582c4b0) at wtp.c:435
#19 0x00007ffff79a06db in start_thread (arg=0x7fffeffff700) at pthread_create.c:463
#20 0x00007ffff6ca788f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I tested quickly on Ubuntu 18.04, with gdb 8.1.0.20180409-git, and VultureProject/Rsyslog master (commit 55ea4e6e8 from rsyslog/rsyslog + some unrelated commits)

**Comment by rgerhards** [comment]
@frikilax I would actually prefer a dedicted issue as this requires a different fix.

**Comment by frikilax** [comment]
> @frikilax I would actually prefer a dedicted issue as this requires a different fix.

done

**Comment by rgerhards** [comment]
thx! will now delete the messages to clean up this tracker.
