### ISSUE TITLE
send multiline messages or exception errors using JSON template Help Wanted 

### ISSUE THREAD

**Issue by WarrenOpus** [rsyslog/rsyslog#2844]
Issue, I have multiline messages or exception errors / stack traces that I wish to send using Rsyslog to  #Logstash

### Expected behavior
Use Rsyslog template to split exception errors or multiline message at a character e.g. '\n' into different objects to look something like this... {message line 1},{message line 2},{message line x}

### Actual behavior
Message is sent as single string in a json object

### Background
I am shipping laravel logs using the rsyslog imfile module. I use the startmsg.regex to deal with multiline messages. These work great.
```
input(type="imfile"
      File="laravel.log"
      Tag="laravel_app"
      startmsg.regex="[[:digit:]]{4}-[[:digit:]]{1,2}-[[:digit:]]{1,2} [[:digit:]]{1,2}:[[:digit:]]{1,2}:[[:digit:]]{1,2}"
)
```

I am shipping laravel logs using the rsyslog imfile module. I use the startmsg.regex to deal with multiline messages. These work great.

input(type="imfile"
      File="laravel.log"
      Tag="laravel_app"
      startmsg.regex="[[:digit:]]{4}-[[:digit:]]{1,2}-[[:digit:]]{1,2} [[:digit:]]{1,2}:[[:digit:]]{1,2}:[[:digit:]]{1,2}"
)

I then ship the logs out to Logstash (and then use them in Elastic Search, and Kibana) I ship the logs using a Rsyslog template
```
template(name="json-template"
type="list") {
constant(value="{")
constant(value="\"@timestamp\":\"") property(name="timereported" dateFormat="rfc3339")
constant(value="\",\"@version\":\"1")
constant(value="\",\"message\":\"") property(name="msg" format="json")
constant(value="\",\"sysloghost\":\"") property(name="hostname")
constant(value="\",\"severity\":\"") property(name="syslogseverity-text")
constant(value="\",\"facility\":\"") property(name="syslogfacility-text")
constant(value="\",\"programname\":\"") property(name="programname")
constant(value="\",\"procid\":\"") property(name="procid")
constant(value="\"}\n")
}

```
My RSyslog look like this, where line-breaks are marked with \n

[2018-06-07 11:02:33] testing.ERROR: Class 'App\Http\Controllers\Deal' not found {"exception":"[object] (Symfony\Component\Debug\Exception\FatalThrowableError(code: 0): Class 'App\Http\Controllers\Deal' not found at /app/Http/Controllers/TestingSyslogController.php:13)\n[stacktrace]\n#0 [internal function]: App\Http\Controllers\TestingSyslogController->index()\n#1 /vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)\n#2 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('index', Array)\n#3 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\TestingSyslogController), 'index')\n#4 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()\n#5

So the entire message is in a single line {message}
How can I use the rsyslog template to split the message at '\n' into different objects to look something like this... {message line 1},{message line 2},{message line x}

I've investigated Property Replacement, but I am not sure this is the correct approach.

**Comment by tamer-hassan** [comment]
I tried, but unfortunately mmnormalize/liblognorm always re-escapes the backslashes, and fails to match the literal newline already escaped by imfile module.

example:

```
# cat /tmp/test.log 
[2018-08-16 21:20:40] ENV.ERROR: some error\\nDETAIL: some detail\\Stack trace:\\n#0 ....\\n

# cat /services/laravel.rulebase 
version=2
rule=:%[ {"type":"literal", "text":"["},
         {"type":"date-iso", "name":"date"},
         {"type":"whitespace"},
         {"type":"time-24hr", "name":"time"},
         {"type":"literal", "text":"] "},
         {"type":"char-to", "name":"env", "extradata":"."},
         {"type":"literal", "text":"."},
         {"type":"char-to", "name":"severity", "extradata":":"},
         {"type":"literal", "text":": "},
         {"type":"repeat", "name":"message", "parser":{"type":"string-to", "extradata":"\\n"}, "while":{"type":"literal", "text":"\\n"} }
        ]%

# head -1 /tmp/test.log | /usr/lib/lognorm/lognormalizer -r /services/laravel.rulebase -e json | jq
{
  "originalmsg": "[2018-08-16 21:20:40] ENV.ERROR: some error\\\\nDETAIL: some detail\\\\Stack trace:\\\\n#0 ....\\\\n",
  "unparsed-data": "some error\\\\nDETAIL: some detail\\\\Stack trace:\\\\n#0 ....\\\\n"
}

# apt policy liblognorm5
liblognorm5:
  Installed: 2.0.4-0adiscon1xenial1
  Candidate: 2.0.4-0adiscon1xenial1
```

**Comment by tamer-hassan** [comment]
I think there's some inconsistency in how newlines are handled in liblognorm. Example: The behaviour is different when using "string-to" type alone (not inside a "repeat" type).

```
# tail /services/laravel.rulebase 
         {"type":"date-iso", "name":"date"},
         {"type":"whitespace"},
         {"type":"time-24hr", "name":"time"},
         {"type":"literal", "text":"] "},
         {"type":"char-to", "name":"env", "extradata":"."},
         {"type":"literal", "text":"."},
         {"type":"char-to", "name":"severity", "extradata":":"},
         {"type":"literal", "text":": "},
         {"type":"string-to", "name":"message", "extradata":"\\n"}
        ]%


# cat /services/laravel.rulebase 
version=2
rule=:%[ {"type":"literal", "text":"["},
         {"type":"date-iso", "name":"date"},
         {"type":"whitespace"},
         {"type":"time-24hr", "name":"time"},
         {"type":"literal", "text":"] "},
         {"type":"char-to", "name":"env", "extradata":"."},
         {"type":"literal", "text":"."},
         {"type":"char-to", "name":"severity", "extradata":":"},
         {"type":"literal", "text":": "},
         {"type":"string-to", "name":"message", "extradata":"\\n"}
        ]%


# cat /tmp/test.log 
[2018-08-16 21:20:40] ENV.ERROR: some error\\nDETAIL: some detail\\nStack trace:\\n#0 ....\\n


# head -1 /tmp/test.log | /usr/lib/lognorm/lognormalizer -r /services/laravel.rulebase -e json | jq
{
  "originalmsg": "[2018-08-16 21:20:40] ENV.ERROR: some error\\\\nDETAIL: some detail\\\\nStack trace:\\\\n#0 ....\\\\n",
  "unparsed-data": "\\nDETAIL: some detail\\\\nStack trace:\\\\n#0 ....\\\\n"
}
```

And even noticed how the first newline in the unparsed-data field is with only 2 backslashes, while the others on the same value have added two more backslashes...

**Comment by rgerhards** [comment]
well, liblognorm is meant to operate on typical log lines, which means
"single line". Details:
https://www.researchgate.net/publication/310545144_Efficient_Normalization_of_IT_Log_Messages_under_Realtime_Conditions

Most importantly it treats chars literally, so it does not unescape \n to a
single character inside the input data. I have not yet have a deeper look
at the problem here, but it sounds this is where it is rooted. If you think
that's not the case, let me know.

Rainer

2018-08-18 19:07 GMT+02:00 Tamer Hassan <notifications@github.com>:
