### ISSUE TITLE
Rsyslog crash in imfile during rotation

### ISSUE THREAD

**Issue by pcullen65** [rsyslog/rsyslog#3021]
### Expected behavior
The imfile plugin should handle log rotation, finishing reads from the current inode and moving on to the next one.

### Actual behavior
Often, but not always, we see rsyslog crash (SIGSEGV) during rotation of log files. This happens with both polling and inotify modes, but seems easier to reproduce using polling. This occurred with 8.37.0. I re-built rsyslog from master but still encountered the crash.

Here's the backtrace from the coredump

(gdb) bt
#0  0x00007fb4064d2927 in getMSGLen (pM=0x3109353231373109) at msg.c:1716
#1  0x00007fb4065020c5 in doLastMessageRepeatedNTimes (ratelimit=0x7fb3fc19d420, pMsg=0x7fb3fc181360, ppRepMsg=0x7fb401737818)
    at ratelimit.c:83
#2  ratelimitMsg (ratelimit=0x7fb3fc19d420, pMsg=0x7fb3fc181360, ppRepMsg=0x7fb401737818) at ratelimit.c:235
#3  0x00007fb406502326 in ratelimitAddMsg (ratelimit=<value optimized out>, pMultiSub=0x7fb3fc088d88, pMsg=0x7fb3fc181360)
    at ratelimit.c:265
#4  0x00007fb402354acf in enqLine (act=0x7fb3fc088d20) at imfile.c:1324
#5  pollFileReal (act=0x7fb3fc088d20) at imfile.c:1547
#6  pollFile (act=0x7fb3fc088d20) at imfile.c:1578
#7  0x00007fb402355f1e in act_obj_destroy (act=0x7fb3fc088d20, is_deleted=<value optimized out>) at imfile.c:920
#8  0x00007fb4023563f1 in detect_updates (edge=0x7fb4083c2b00) at imfile.c:737
#9  0x00007fb40235645e in poll_tree (chld=0x7fb4083c2b00) at imfile.c:818
#10 0x00007fb40235176d in fs_node_walk (node=<value optimized out>, f_usr=0x7fb402356430 <poll_tree>) at imfile.c:1040
#11 0x00007fb402351779 in fs_node_walk (node=<value optimized out>, f_usr=0x7fb402356430 <poll_tree>) at imfile.c:1041
#12 0x00007fb402351779 in fs_node_walk (node=<value optimized out>, f_usr=0x7fb402356430 <poll_tree>) at imfile.c:1041
#13 0x00007fb402351779 in fs_node_walk (node=<value optimized out>, f_usr=0x7fb402356430 <poll_tree>) at imfile.c:1041
#14 0x00007fb402351779 in fs_node_walk (node=<value optimized out>, f_usr=0x7fb402356430 <poll_tree>) at imfile.c:1041
#15 0x00007fb402351779 in fs_node_walk (node=<value optimized out>, f_usr=0x7fb402356430 <poll_tree>) at imfile.c:1041
#16 0x00007fb402351779 in fs_node_walk (node=<value optimized out>, f_usr=0x7fb402356430 <poll_tree>) at imfile.c:1041
#17 0x00007fb402351779 in fs_node_walk (node=<value optimized out>, f_usr=0x7fb402356430 <poll_tree>) at imfile.c:1041
#18 0x00007fb402351779 in fs_node_walk (node=<value optimized out>, f_usr=0x7fb402356430 <poll_tree>) at imfile.c:1041
#19 0x00007fb402355cf1 in doPolling (pThrd=<value optimized out>) at imfile.c:2118
#20 runInput (pThrd=<value optimized out>) at imfile.c:2471
#21 0x00007fb40650a258 in thrdStarter (arg=0x7fb4083ea160) at ../threads.c:239
#22 0x00007fb405e46aa1 in start_thread () from /lib64/libpthread.so.0
#23 0x00007fb404f7293d in clone () from /lib64/libc.so.6
(gdb) 

The value of pM at #0 is invalid. That comes from ratelimit->pMsg at #1. In fact, everything in ratelimit looked invalid. Walking back up the stack to act_obj_destroy(), I found the following code:

```

        if(act->ratelimiter != NULL) {
                ratelimitDestruct(act->ratelimiter);
        }
        if(act->pStrm != NULL) {
                const instanceConf_t *const inst = act->edge->instarr[0];// TODO: same file, multiple instances?
                pollFile(act); /* get any left-over data */
                if(inst->bRMStateOnDel) {
                        statefn = getStateFileName(act, statefile, sizeof(statefile));
                        getFullStateFileName(statefn, "", toDel, sizeof(toDel)); // TODO: check!
                        statefn = toDel;
                }
                persistStrmState(act);
                strm.Destruct(&act->pStrm);
                /* we delete state file after destruct in case strm obj initiated a write */
                if(is_deleted && !act->in_move && inst->bRMStateOnDel) {
                        DBGPRINTF("act_obj_destroy: deleting state file %s\n", statefn);
                        unlink((char*)statefn);
                }
        } 
```

I see ratelimitDestruct() is being called before pollFile(). When pollFile() is called we go back down the stack to getMSGLen() where ratelimit->pMsg is referenced (after being destructed) and causes the segmentation fault.

### Steps to reproduce the behavior
We're reading about 16 log files using imfile and sending the logs out via omkafka. Triggering a rotation of all log files caused the segmentation fault.

Moving the block containing ratelimitDestruct() to after the block containing pollFile() seems to resolve the issue - at least in our own internal testing. But, there may be other dependencies or issues in doing so. The patch I applied was this:

```
diff -Naur rsyslog-8.38.0/plugins/imfile/imfile.c rsyslog-8.38.0-ratelimitDestruct-patch/plugins/imfile/imfile.c
--- rsyslog-8.38.0/plugins/imfile/imfile.c    2018-09-11 14:19:55.000000000 -0400
+++ rsyslog-8.38.0-ratelimitDestruct-patch/plugins/imfile/imfile.c    2018-09-12 21:42:47.524992691 -0400
@@ -912,9 +912,6 @@
            }
        }
    }
-    if(act->ratelimiter != NULL) {
-        ratelimitDestruct(act->ratelimiter);
-    }
    if(act->pStrm != NULL) {
        const instanceConf_t *const inst = act->edge->instarr[0];// TODO: same file, multiple instances?
        pollFile(act); /* get any left-over data */
@@ -931,6 +928,9 @@
            unlink((char*)statefn);
        }
    }
+        if(act->ratelimiter != NULL) {
+                ratelimitDestruct(act->ratelimiter);
+        }
    #ifdef HAVE_INOTIFY_INIT
    if(act->wd != -1) {
        wdmapDel(act->wd);

```

Happy to supply any other details or output from the core file.

### Environment
- rsyslog version: 8.37.0 and master
- platform: CentOS 6

**Comment by rgerhards** [comment]
Could you reproduce this under valgrind and provide the output? Rsyslog should be compiled with -g flag.

**Comment by rgerhards** [comment]
That's interesting!

**Comment by rgerhards** [comment]
Not yet 100% sure, but I may be able to reproduce this now in integration testing.

**Comment by pcullen65** [comment]
That sounds promising. Let me know if you need anything else. Thanks!

**Comment by rgerhards** [comment]
> That sounds promising. Let me know if you need anything else. Thanks!

It would be great if you could apply https://github.com/rsyslog/rsyslog/pull/3052 locally and check the outcome - just to be sure.

**Comment by pcullen65** [comment]
I've been testing the same change since last week and have not seen any crashes. I ran a longer term test over the weekend and it's still going. Looks good.
