### ISSUE TITLE
testbench: kafka test cause hang

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#3045]
It looks like topic creation is racy: it seems it can happen if the brokers have not been synced. This seems to cause follow-on errors and ultimately causes the test to hang in rsyslog shutdown.

Sample instance: https://build.rsyslog.com/#/builders/113/builds/1128

Relevant part of test output:
```
Test: ../../tests/sndrcv_kafka_multi_topics.sh
------------------------------------------------------------
testbench: TZ env var not set, setting it to UTC
===============================================================================
Check and Stop previous instances of kafka/zookeeper
ZooKeeper JMX enabled by default
Using config: /worker/rsyslog_docker-centos7_rsyslog/build/rsyslog-8.39.0.master/_build/tests/.dep_wrk/zk/bin/../conf/zoo.cfg
Stopping zookeeper ... STOPPED
Stopping Kafka instance 
Create kafka/zookeeper instance and topics
ZooKeeper JMX enabled by default
Using config: /worker/rsyslog_docker-centos7_rsyslog/build/rsyslog-8.39.0.master/_build/tests/.dep_wrk/zk/bin/../conf/zoo.cfg
Stopping zookeeper ... no zookeeper to stop (could not find file zk_data_dir/zookeeper_server.pid)
Starting Zookeeper instance 
ZooKeeper JMX enabled by default
Using config: /worker/rsyslog_docker-centos7_rsyslog/build/rsyslog-8.39.0.master/_build/tests/.dep_wrk/zk/bin/../conf/zoo.cfg
Starting zookeeper ... STARTED
Starting Kafka instance kafka-server.properties
Kafka instance kafka-server.properties started with PID buildbot
buildbot
Error while executing topic command : Replication factor: 1 larger than available brokers: 0.
[2018-09-21 21:37:17,710] ERROR org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 1 larger than available brokers: 0.
 (kafka.admin.TopicCommand$)
Error while executing topic command : Topic Ri4E19EZ does not exist on ZK path localhost:22181/kafka
[2018-09-21 21:37:19,926] ERROR java.lang.IllegalArgumentException: Topic Ri4E19EZ does not exist on ZK path localhost:22181/kafka
	at kafka.admin.TopicCommand$.alterTopic(TopicCommand.scala:124)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:65)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
 (kafka.admin.TopicCommand$)
```

**Comment by rgerhards** [comment]
I can reproduce this issue when runing the test under `loop.sh` script - but only pretty seldom.

**Comment by rgerhards** [comment]
PR #3047 adds plumbing so that what I think is the root issue is discovered and does not cause a hang - at least that's the idea. Obviously, even if it works out, it is **not** a proper fix. We need to sync startup.
