### ISSUE TITLE
mmjsonparse: memory leak?

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#313]
Looks like there is a leak in processJSON if json is parsed, but there is extra data after it. Quickly seen while working on something else, needs to be looked at in more depth.

**Comment by rgerhards** [comment]
@PascalWithopf could you try to craft a (valgrind) test for this?

**Comment by PascalWithopf** [comment]
There is a memory leak even without the extra data.
Valgrind Output can be seen below:
```
==1215== 
==1215== HEAP SUMMARY:
==1215==     in use at exit: 18,170 bytes in 56 blocks
==1215==   total heap usage: 2,212 allocs, 2,156 frees, 1,083,708 bytes allocated
==1215== 
==1215== 8 bytes in 1 blocks are definitely lost in loss record 7 of 39
==1215==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1215==    by 0x5F25489: strdup (strdup.c:42)
==1215==    by 0x5A91E27: stdlog_open (in /usr/lib/x86_64-linux-gnu/liblogging-stdlog.so.0.0.0)
==1215==    by 0x434CDC: rsrtInit (rsyslog.c:144)
==1215==    by 0x40E9A2: rsyslogd_InitGlobalClasses (rsyslogd.c:572)
==1215==    by 0x410531: initAll (rsyslogd.c:1268)
==1215==    by 0x4116B1: main (rsyslogd.c:1923)
==1215== 
==1215== 9 bytes in 1 blocks are definitely lost in loss record 10 of 39
==1215==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1215==    by 0x5F25489: strdup (strdup.c:42)
==1215==    by 0x5A91DDF: stdlog_open (in /usr/lib/x86_64-linux-gnu/liblogging-stdlog.so.0.0.0)
==1215==    by 0x434CDC: rsrtInit (rsyslog.c:144)
==1215==    by 0x40E9A2: rsyslogd_InitGlobalClasses (rsyslogd.c:572)
==1215==    by 0x410531: initAll (rsyslogd.c:1268)
==1215==    by 0x4116B1: main (rsyslogd.c:1923)
==1215== 
==1215== 9 bytes in 1 blocks are definitely lost in loss record 11 of 39
==1215==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1215==    by 0x5A9250A: ??? (in /usr/lib/x86_64-linux-gnu/liblogging-stdlog.so.0.0.0)
==1215==    by 0x5A91E54: stdlog_open (in /usr/lib/x86_64-linux-gnu/liblogging-stdlog.so.0.0.0)
==1215==    by 0x434CDC: rsrtInit (rsyslog.c:144)
==1215==    by 0x40E9A2: rsyslogd_InitGlobalClasses (rsyslogd.c:572)
==1215==    by 0x410531: initAll (rsyslogd.c:1268)
==1215==    by 0x4116B1: main (rsyslogd.c:1923)
==1215== 
==1215== LEAK SUMMARY:
==1215==    definitely lost: 26 bytes in 3 blocks
==1215==    indirectly lost: 0 bytes in 0 blocks
==1215==      possibly lost: 0 bytes in 0 blocks
==1215==    still reachable: 18,144 bytes in 53 blocks
==1215==         suppressed: 0 bytes in 0 blocks
==1215== Reachable blocks (those to which a pointer was found) are not shown.
==1215== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==1215== 
==1215== For counts of detected and suppressed errors, rerun with: -v
==1215== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
rsyslogd run exited with 10
valgrind run FAILED with exceptions - terminating
```

**Comment by PascalWithopf** [comment]
Address Sanitizer shows a leak too.
```
==43946==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 17 byte(s) in 2 object(s) allocated from:
    #0 0x4c4878 in malloc (/home/pwithopf/rsyslog/tools/rsyslogd+0x4c4878)
    #1 0x7f6494fef489 in __strdup /build/glibc-bfm8X4/glibc-2.23/string/strdup.c:42

Direct leak of 9 byte(s) in 1 object(s) allocated from:
    #0 0x4c4878 in malloc (/home/pwithopf/rsyslog/tools/rsyslogd+0x4c4878)
    #1 0x7f6495c5a50a  (/usr/lib/x86_64-linux-gnu/liblogging-stdlog.so.0+0x150a)

SUMMARY: AddressSanitizer: 26 byte(s) leaked in 3 allocation(s).
```

**Comment by rgerhards** [comment]
@PascalWithopf did you verify with the latest version of liblogging-stdlog? If not, please do. I remeber I fixed something in that regard.

**Comment by PascalWithopf** [comment]
@rgerhards I did and the error still occurs.

**Comment by rgerhards** [comment]
The leak @PascalWithopf  reports is not related to mmjsonparse.

**Comment by rgerhards** [comment]
newly crafted test shows everything works well, my suspicion was wrong.
