### ISSUE TITLE
Yet another crash

### ISSUE THREAD

**Issue by amuhametov** [rsyslog/rsyslog#3152]
Got a random crash with SIGABRT.
rsyslog-8.38.0

```

 gdb /usr/sbin/rsyslogd -c in:imptcp.17475.core
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/rsyslogd...Reading symbols from /usr/lib/debug/usr/sbin/rsyslogd.debug...done.
done.
[New LWP 17484]
[New LWP 17487]
[New LWP 17485]
[New LWP 17496]
[New LWP 17500]
[New LWP 17498]
[New LWP 17499]
[New LWP 17501]
[New LWP 17509]
[New LWP 17504]
[New LWP 17506]
[New LWP 17479]
[New LWP 17508]
[New LWP 17503]
[New LWP 17480]
[New LWP 17478]
[New LWP 17488]
[New LWP 17476]
[New LWP 17482]
[New LWP 21145]
[New LWP 17514]
[New LWP 17477]
[New LWP 17481]
[New LWP 17483]
[New LWP 17502]
[New LWP 17486]
[New LWP 17505]
[New LWP 17512]
[New LWP 17507]
[New LWP 17510]
[New LWP 17497]
[New LWP 17513]
[New LWP 17511]
[New LWP 17475]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/sbin/rsyslogd -n -iNONE'.
Program terminated with signal 6, Aborted.
#0  0x00007fa9e3455277 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56        return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
(gdb) bt
#0  0x00007fa9e3455277 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fa9e3456968 in __GI_abort () at abort.c:90
#2  0x00007fa9e3497d37 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7fa9e35a9d58 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/unix/sysv/linux/libc_fatal.c:196
#3  0x00007fa9e349e5e4 in malloc_printerr (action=<optimized out>, str=0x7fa9e35a9f50 "malloc(): memory corruption (fast)", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5025
#4  0x00007fa9e34a1d00 in _int_malloc (av=av@entry=0x7fa9ac000020, bytes=bytes@entry=24) at malloc.c:3387
#5  0x00007fa9e34a484c in __GI___libc_malloc (bytes=bytes@entry=24) at malloc.c:2899
#6  0x000055922cb6cf2e in cstrConstruct (ppThis=ppThis@entry=0x7fa9ac0a8038) at stringbuf.c:68
#7  0x000055922cb66e91 in MsgSetAPPNAME (pMsg=pMsg@entry=0x7fa9ac0a7f70, pszAPPNAME=pszAPPNAME@entry=0x7fa9ac0640e0 "ok-grace") at msg.c:2194
#8  0x000055922cb4a1a1 in parse (pMsg=0x7fa9ac0a7f70) at pmrfc5424.c:272
#9  0x000055922cb633c9 in ParseMsg (pMsg=0x7fa9ac0a7f70) at parser.c:664
#10 0x000055922cb87926 in ratelimitMsg (ratelimit=0x55922ce8acf0, pMsg=pMsg@entry=0x7fa9ac0a7f70, ppRepMsg=ppRepMsg@entry=0x7fa9d7bcba50) at ratelimit.c:217
#11 0x000055922cb87c9b in ratelimitAddMsg (ratelimit=<optimized out>, pMultiSub=pMultiSub@entry=0x7fa9d7bcbb40, pMsg=0x7fa9ac0a7f70) at ratelimit.c:265
#12 0x00007fa9e0d20080 in doSubmitMsg (pThis=pThis@entry=0x7fa9b80cd260, stTime=stTime@entry=0x7fa9d7bcdbe0, ttGenTime=ttGenTime@entry=1540042237, pMultiSub=pMultiSub@entry=0x7fa9d7bcbb40) at imptcp.c:949
#13 0x00007fa9e0d20626 in processDataRcvd (pnMsgs=<synthetic pointer>, pMultiSub=0x7fa9d7bcbb40, ttGenTime=1540042237, stTime=0x7fa9d7bcdbe0, buffLen=<optimized out>, buff=<synthetic pointer>, pThis=0x7fa9b80cd260) at imptcp.c:1182
#14 DataRcvdUncompressed (pThis=pThis@entry=0x7fa9b80cd260,
    pData=0x7fa9d7bddd45 "\n<69>1 2018-10-20T16:30:36.998956+03:00 asdfghjk ok-grace - ********REST OF THE MESSAGE********"...,
    pData@entry=0x7fa9d7bddc00 "********OTHER PART********"..., iLen=iLen@entry=2896, stTime=stTime@entry=0x7fa9d7bcdbe0, ttGenTime=1540042237, ttGenTime@entry=0) at imptcp.c:1233
#15 0x00007fa9e0d20d3a in DataRcvd (iLen=2896,
    pData=0x7fa9d7bddc00 "********OTHER PART********"...,
    pThis=0x7fa9b80cd260) at imptcp.c:1309
#16 sessActivity (pSess=0x7fa9b80cd260, continue_polling=continue_polling@entry=0x7fa9d7bfdc94) at imptcp.c:1899
#17 0x00007fa9e0d22263 in processWorkItem (epd=0x7fa9b81f8840) at imptcp.c:1944
#18 0x00007fa9e0d229ab in wrkr (myself=0x7fa9cc002240) at imptcp.c:2098
#19 0x00007fa9e485fe25 in start_thread (arg=0x7fa9d7bfe700) at pthread_create.c:308
#20 0x00007fa9e351dbad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

```

**Comment by jgerhards** [comment]
could you also please add your rsyslog.conf file?

**Comment by amuhametov** [comment]
Here is it

```
module(load="impstats"
       interval="10"
       severity="6"
       log.syslog="off"
       format="json"
       ResetCounters="on"
       log.file="/var/log/rsyslog_stats.log")



global( net.enableDNS="off"
        action.reportSuspensionContinuation="on"
        oversizemsg.report="off"
        oversizemsg.errorfile="/var/log/rsyslog.oversize.log"
        janitor.interval="1"
)

template(name="kafkamsg" type="string" string="%TIMESTAMP:::date-unixtimestamp% %HOSTNAME% %msg%")

module(load="imptcp" threads="8" ProcessOnPoller="off")
module(load="omkafka")

input(
        type="imptcp"
        port="514"
        ruleset="ruleset 1"
        socketbacklog="65535"
        )


ruleset(name="ruleset 1"
        queue.size="4000000"
        queue.type="LinkedList"
        queue.timeoutenqueue="60"
        queue.workerThreads="16"
        queue.dequeuebatchsize="50000"
        queue.timeoutWorkerthreadShutdown="600000"
        queue.timeoutshutdown="5000"
        queue.timeoutActionCompletion="5000"

        queue.saveOnShutdown="on"
        queue.maxFileSize="16g"
        queue.spoolDirectory="/var/spool/rsyslog"
        queue.filename="rsyslog_imptcp_input"
        queue.checkpointInterval="5"
        queue.dequeueSlowDown="20000"
        ) {

    if $syslogfacility-text == 'uucp' then {

        action(
                type="omkafka"
                topic="topic"
                partitions.auto="on"
                partitions.number="128"
		broker=#7 brokers
                confParam=["batch.num.messages=10000","message.max.bytes=20000000","queue.buffering.max.ms=1000","queue.buffering.max.messages=1000000","socket.timeout.ms=10000","broker.address.ttl=60000","message.send.max.retries=3","queue.buffering.max.kbytes=2097151"]
                TopicConfParam=["request.required.acks=1", "request.timeout.ms=8000"]
                errorFile="/var/log/rsyslog_kafka_errors"
                closeTimeout="4000"
                resubmitOnFailure="on"
                KeepFailedMessages="on"
                failedMsgFile="/var/spool/rsyslog/rsyslog_kafka_failed_msg"

                queue.type="LinkedList"
                queue.timeoutenqueue="60"
                queue.size="8000000"
                queue.dequeuebatchsize="50000"
                queue.workerthreads="16"
                queue.timeoutWorkerthreadShutdown="600000"
                queue.timeoutshutdown="6000"
                queue.timeoutActionCompletion="6000"

                queue.saveOnShutdown="on"
                queue.maxFileSize="16g"
                queue.spoolDirectory="/var/spool/rsyslog"
                queue.filename="rsyslog_action_omkafka"
                queue.checkpointInterval="5"
                queue.dequeueSlowDown="20000"

                action.resumeretrycount="-1"
                template="kafkamsg"
                action.errorFile="/var/log/rsyslog_kafka_action_error.log"
        )

        action(
                type="omfwd"
                Target="mirror host"
                Port="514"
                Protocol="tcp"

                queue.type="LinkedList"
                queue.timeoutenqueue="60"
                queue.size="8000000"
                queue.dequeuebatchsize="50000"
                queue.workerthreads="4"
                queue.timeoutWorkerthreadShutdown="600000"
                queue.timeoutshutdown="6000"
                queue.timeoutActionCompletion="6000"

                queue.saveonshutdown="on"
                queue.maxFileSize="16g"
                queue.spoolDirectory="/var/spool/rsyslog"
                queue.filename="rsyslog_mirror"
                queue.checkpointInterval="5"
                queue.dequeueSlowDown="20000"

                action.resumeretrycount="-1"
                template="kafkamsg"
                action.errorFile="/var/log/rsyslog_mirror_action_error.log"
        )

        if ($msg contains "sample_msg") then {
          action( type="omfile" file="/var/log/rsyslog_debug.log")
        }

        stop
    }
}
```

**Comment by rgerhards** [comment]
Can you reproduce this? The stack Trace is after the fact, so it does not
have really useful info.

Sent from phone, thus brief.

Anes Mukhametov <notifications@github.com> schrieb am Mo., 22. Okt. 2018,
15:26:

**Comment by amuhametov** [comment]
It has happened only once for now. I'll let you know if it happens again.

**Comment by rgerhards** [comment]
thx
