### ISSUE TITLE
imfile: segfault on two imfile inputs with one listens to a log folder which log files are symlink and the other uses start_regex

### ISSUE THREAD

**Issue by fivesheep** [rsyslog/rsyslog#3474]
### Expected behavior
Rsyslog shall not crash

### Actual behavior
This only happens when I have two input setups with imfile, with one of the input listens to a folder where log files are created with symlinks (for example, /var/log/containers/*.log from docker-k8s setup), and the other input with a regular file (or wildcards) that needs to use start_regex for multiline processing. 

Rsyslog crashes right away if a symlink based log file is created to the watching folder. if the symlink was not created before rsyslog starts, rsyslog won't crash at start up time, but it still crashes once a symlink based log created.

### Steps to reproduce the behavior
create a rsyslog config with the following content
```
module(load = "imfile")
module(load = "omstdout")

input(
  type="imfile"
  File="/tmp/logs/*.log"
  Tag="symlinks"
  ruleset="ruleset_stdout"
  addmetadata="on"
  escapelf="off"
  discardTruncatedMsg="on"
 )

input(
  type="imfile"
  File="/tmp/abc.log"
  startmsg.regex="^[A-Z]`"
  readTimeout = "15"
  Tag="abc"
  ruleset="ruleset_stdout"
  addmetadata="on"
  escapelf="off"
  discardTruncatedMsg="on"
)

ruleset(name="ruleset_stdout") {
  action(type="omstdout")
}
```

then prepare the logs with the following commands:
```
mkdir -p /tmp/logs
touch /tmp/abc.log
echo "test" > /tmp/test.log
ln -s /tmp/test.log /tmp/logs/test.log
```

then start rsyslog with this config
```
/sbin/rsyslogd -n -f rsyslog.conf -i /tmp/rsyslog.pid
```

Rsyslog crashes right away with 
```
Segmentation fault
```

with strace
```
--- SIGTTOU {si_signo=SIGTTOU, si_code=SI_USER, si_pid=70, si_uid=0} ---
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
gettimeofday({1550266802, 884767}, NULL) = 0
socket(AF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 5
connect(5, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = -1 ENOENT (No such file or directory)
close(5)                                = 0
select(1, NULL, NULL, NULL, {600, 0} <unfinished ...>
+++ killed by SIGSEGV (core dumped) +++
./run_rsyslog.sh: line 5:    68 Segmentation fault      strace /sbin/rsyslogd -n -f /tmp/rsyslog.conf
```

gdb
```
# gdb rsyslogd core
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/rsyslogd...Reading symbols from /usr/lib/debug/usr/sbin/rsyslogd.debug...done.
done.
[New LWP 82]
[New LWP 81]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/sbin/rsyslogd -n -f /tmp/rsyslog.conf'.
Program terminated with signal 11, Segmentation fault.
#0  strmReadMultiLine_isTimedOut (pThis=0x0) at stream.c:1025
1025		       && (getTime(NULL) > pThis->lastRead + pThis->readTimeout) );
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 elfutils-libelf-0.172-2.el7.x86_64 elfutils-libs-0.172-2.el7.x86_64 glibc-2.17-260.el7.x86_64 libattr-2.4.46-13.el7.x86_64 libcap-2.22-9.el7.x86_64 libestr-0.1.11-1.el7.x86_64 libgcc-4.8.5-36.el7.x86_64 libgcrypt-1.5.3-14.el7.x86_64 libgpg-error-1.12-3.el7.x86_64 libselinux-2.5-14.1.el7.x86_64 libuuid-2.23.2-59.el7.x86_64 lz4-1.7.5-2.el7.x86_64 pcre-8.32-17.el7.x86_64 systemd-libs-219-62.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  strmReadMultiLine_isTimedOut (pThis=0x0) at stream.c:1025
#1  0x00007fcf28b18bc2 in poll_timeouts (edge=<optimized out>) at imfile.c:899
#2  0x00007fcf28b1486d in fs_node_walk (node=<optimized out>, f_usr=f_usr@entry=0x7fcf28b18b90 <poll_timeouts>) at imfile.c:1055
#3  0x00007fcf28b14879 in fs_node_walk (node=<optimized out>, f_usr=f_usr@entry=0x7fcf28b18b90 <poll_timeouts>) at imfile.c:1056
#4  0x00007fcf28b14879 in fs_node_walk (node=<optimized out>, f_usr=f_usr@entry=0x7fcf28b18b90 <poll_timeouts>) at imfile.c:1056
#5  0x00007fcf28b17cb9 in do_inotify () at imfile.c:2300
#6  0x00007fcf28b1838f in runInput (pThrd=<optimized out>) at imfile.c:2477
#7  0x000055d8e5b294e6 in thrdStarter (arg=0x55d8e7aee6e0) at ../threads.c:239
#8  0x00007fcf2c059dd5 in start_thread () from /usr/lib64/libpthread.so.0
#9  0x00007fcf2af1bead in clone () from /usr/lib64/libc.so.6
(gdb) f 1
#1  0x00007fcf28b18bc2 in poll_timeouts (edge=<optimized out>) at imfile.c:899
899				if(strmReadMultiLine_isTimedOut(act->pStrm)) {
(gdb) p *act
$1 = {prev = 0x0, next = 0x7fcf24000b10, edge = 0x55d8e7aebfa0, name = 0x7fcf24008b50 "/tmp", basename = 0x7fcf24008b70 "tmp", source_name = 0x0, wd = 2, timeoutBase = 0, in_move = 0, ino = 8635600298,
  pStrm = 0x0, nRecords = 0, ratelimiter = 0x0, multiSub = {maxElem = 0, nElem = 0, ppMsgs = 0x0}, is_symlink = 0}
(gdb) i locals
act = 0x7fcf24008ac0
edge = <optimized out>
(gdb) p *act->edge
$2 = {parent = 0x55d8e7aec810, node = 0x55d8e7aec010, next = 0x55d8e7aebc60, name = 0x55d8e7aebff0 "abc.log", path = 0x55d8e7aec030 "/tmp/abc.log", active = 0x7fcf24008ac0, is_file = 1, ninst = 1,
  instarr = 0x55d8e7aec050}
```

### Environment
- rsyslog version:
```
rsyslogd  8.1901.0 (aka 2019.01) compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Number of Bits in RainerScript integers: 64
```

It's not limited to this version. I have tested it with 8.38, it crashes the same way.
however, 8.32 seems like have no issue.

- platform: Centos7 (or within the centos7 container from rsyslog-docker), ubuntu 16.4
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
looks like this is closed by #3496
