### ISSUE TITLE
omkafka: segfault in version 8.38.0

### ISSUE THREAD

**Issue by hxwang1024** [rsyslog/rsyslog#3542]
omkafka maybe segfault in version 8.38.0, when I run mutlithreading .

I hav try to run rsyslog in mutlithreading .

**Comment by hxwang1024** [comment]
rsyslogd: omkafka: Failed to produce to topic 'abcdef11c4b98d4183bb724c26b1ad96f3__demo' (rd_kafka_producev)partition 4: -184/Local: Queue full - MSG '10.107.23.23 [13/Mar/2019:11:03:47 +0800] 10.39.45.34 - - [13/Mar/2019:11:03:47 +0800] "GET /index.html HTTP/1.1" [13/Mar/2019:11:03:47 +0800] 10.39.45.34 - - [13/Mar/2019:11:03:47 +0800] "GET /index.html HTTP/1.1" [13/Mar/2019:11:03:47 +0800] 10.39.45.34 - - [13/Mar/2019:11:03:47 +0800] "GET /index.html HTTP/1.1" 200 612 "-" "-" "-"'  [v8.38.0 try http://www.rsyslog.com/e/2424 ]
Segmentation fault

**Comment by hxwang1024** [comment]
how to core dump rsyslog.

I have set core file size is unlimited.

[qqqq@123456 output]$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 769826
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
......

**Comment by hxwang1024** [comment]
![](file:///Users/wanghongxiang/Library/Caches/BaiduMacHi/Share/images/04b9a037e956b5f8391f48218c5b397c.jpg)

**Comment by hxwang1024** [comment]
![04b9a037e956b5f8391f48218c5b397c](https://user-images.githubusercontent.com/33044973/54264104-46bd9880-45ad-11e9-9581-79e2e7ef109e.jpg)

**Comment by alorbach** [comment]
can you try the latest version of winsyslog to rule out this is a existing bug / issue already fixed?

**Comment by hxwang1024** [comment]
> can you try the latest version of rsyslog to rule out this is a existing bug / issue already fixed?

why rsyslog can not core dump ?

**Comment by davidelang** [comment]
On Wed, 13 Mar 2019, hxwang1024 wrote:

> why rsyslog can not core dump ?

You probably don't have something set right, there's nothing in rsyslog to 
prevent you from doing a core dump, but systemd makes it hard to set core dump 
filename and size limits.

David Lang

**Comment by hxwang1024** [comment]
> can you try the latest version of rsyslog to rule out this is a existing bug / issue already fixed?

there is same problem in latest verion 8.1901.0

![image](https://user-images.githubusercontent.com/33044973/54331550-71fbc280-4655-11e9-8c3b-d547c740129b.png)


after 3~5min， I continue test rsyslog.
![image](https://user-images.githubusercontent.com/33044973/54331574-88a21980-4655-11e9-8e9e-c81f599b4a85.png)


![image](https://user-images.githubusercontent.com/33044973/54331598-9b1c5300-4655-11e9-9766-e14dbe9f7bc1.png)


rsyslogd: omkafka: Failed to produce to topic 'mytopic' (rd_kafka_producev)partition 0: -184/Local: Queue full - KEY '(null)' -MSG '[14/Mar/2019:12:29:31 +0800] 127.0.0.1 - - [14/Mar/2019:12:29:31 +0800] "GET /index.html HTTP/1.1" 200 17 "-" "-" "-"'  [v8.1903.0 try https://www.rsyslog.com/e/2424 ]
rsyslogd: omkafka: Failed to produce to topic 'mytopic' (rd_kafka_producev)partition 0: -184/Local: Queue full - KEY '(null)' -MSG '[14/Mar/2019:12:30:21 +0800] 127.0.0.1 - - [14/Mar/2019:12:30:21 +0800] "GET /index.html HTTP/1.1" 200 17 "-" "-" "-"'  [v8.1903.0 try https://www.rsyslog.com/e/2424 ]
rsyslogd: omkafka: Failed to produce to topic 'mytopic' (rd_kafka_producev)partition 0: -184/Local: Queue full - KEY '(null)' -MSG '[14/Mar/2019:12:30:21 +0800] 127.0.0.1 - - [14/Mar/2019:12:30:21 +0800] "GET /index.html HTTP/1.1" 200 17 "-" "-" "-"'  [v8.1903.0 try https://www.rsyslog.com/e/2424 ]
rsyslogd: omkafka: Failed to produce to topic 'mytopic' (rd_kafka_producev)partition 0: -184/Local: Queue full - KEY '(null)' -MSG '[14/Mar/2019:12:30:21 +0800] 127.0.0.1 - - [14/Mar/2019:12:30:21 +0800] "GET /index.html HTTP/1.1" 200 17 "-" "-" "-"'  [v8.1903.0 try https://www.rsyslog.com/e/2424 ]
rsyslogd: omkafka: Failed to produce to topic 'mytopic' (rd_kafka_producev)partition 0: -184/Local: Queue full - KEY '(null)' -MSG '[14/Mar/2019:12:30:21 +0800] 127.0.0.1 - - [14/Mar/2019:12:30:21 +0800] "GET /index.html HTTP/1.1" 200 17 "-" "-" "-"'  [v8.1903.0 try https://www.rsyslog.com/e/2424 ]
rsyslogd: omkafka: Failed to produce to topic 'mytopic' (rd_kafka_producev)partition 0: -184/Local: Queue full - KEY '(null)' -MSG '[14/Mar/2019:12:31:04 +0800] 127.0.0.1 - - [14/Mar/2019:12:31:04 +0800] "GET /index.html HTTP/1.1" 200 17 "-" "-" "-"'  [v8.1903.0 try https://www.rsyslog.com/e/2424 ]
rsyslogd: omkafka: Failed to produce to topic 'mytopic' (rd_kafka_producev)partition 0: -184/Local: Queue full - KEY '(null)' -MSG '[14/Mar/2019:12:31:04 +0800] 127.0.0.1 - - [14/Mar/2019:12:31:04 +0800] "GET /index.html HTTP/1.1" 200 17 "-" "-" "-"'  [v8.1903.0 try https://www.rsyslog.com/e/2424 ]
rsyslogd: omkafka: Failed to produce to topic 'mytopic' (rd_kafka_producev)partition 0: -184/Local: Queue full - KEY '(null)' -MSG '[14/Mar/2019:12:31:04 +0800] 127.0.0.1 - - [14/Mar/2019:12:31:04 +0800] "GET /index.html HTTP/1.1" 200 17 "-" "-" "-"'  [v8.1903.0 try https://www.rsyslog.com/e/2424 ]
Segmentation fault (core dumped)

**Comment by hxwang1024** [comment]
Mar 14 13:31:30 instance-001 rsyslogd: writeRemoteData:Reg: worker thread 15b98f0 terminated, now 3 active worker threads [v8.1903.0 try https://www.rsyslog.com/e/2439 ]
Mar 14 13:31:30 instance-001 rsyslogd: writeRemoteData:Reg: worker thread 1597350 terminated, now 2 active worker threads [v8.1903.0 try https://www.rsyslog.com/e/2439 ]
Mar 14 13:31:30 instance-001 rsyslogd: writeRemoteData:Reg: worker thread 1597120 terminated, now 1 active worker threads [v8.1903.0 try https://www.rsyslog.com/e/2439 ]
Mar 14 13:32:10 instance-001 rsyslogd: writeRemoteData:Reg: high activity - starting 1 additional worker thread(s), currently 1 active worker threads. [v8.1903.0 try https://www.rsyslog.com/e/2439 ]
Mar 14 13:32:10 instance-001 kernel: rs:writeRemoteD[26687]: segfault at 0 ip 00007f24fb064bf7 sp 00007f24e54e4878 error 6 in libc-2.17.so[7f24faf0f000+1c2000]
Mar 14 13:32:10 instance-001 abrt-hook-ccpp: Process 26308 (rsyslogd) of user 0 killed by SIGSEGV - dumping core
Mar 14 13:32:13 instance-001 abrt-hook-ccpp: Failed to create core_backtrace: waitpid failed: No child processes
Mar 14 13:32:13 instance-001 abrt-server: Executable '/root/third/rsyslog/sbin/rsyslogd' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Mar 14 13:32:13 instance-001 abrt-server: 'post-create' on '/var/spool/abrt/ccpp-2019-03-14-13:32:10-26308' exited with 1
Mar 14 13:32:13 instance-001 abrt-server: Deleting problem directory '/var/spool/abrt/ccpp-2019-03-14-13:32:10-26308'

**Comment by hxwang1024** [comment]
Mar 14 13:32:10 instance-001 **rsyslogd: writeRemoteData:Reg: high activity - starting 1 additional worker thread(s), currently 1 active worker threads. [**v8.1903.0 try https://www.rsyslog.com/e/2439 ]
Mar 14 13:32:10 instance-001 kernel: rs:writeRemoteD[26687]: segfault at 0 ip 00007f24fb064bf7 sp 00007f24e54e4878 error 6 in libc-2.17.so[7f24faf0f000+1c2000]

![图片](https://user-images.githubusercontent.com/33044973/54343871-b2ba0280-467a-11e9-952e-40d1a333445f.png)

**Comment by hxwang1024** [comment]
core dump file bt info:

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Core was generated by `/home/test/rsyslog/output/sbin/rsyslogd -f /home/test/rsyslog/output/conf/r'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fbdb1522e20 in __memcpy_sse2_unaligned () from /bin/gcc/lib/libc.so.6
(gdb) bt
#0  0x00007fbdb1522e20 in __memcpy_sse2_unaligned () from /bin/gcc/lib/libc.so.6
#1  0x000000000047dc39 in tplToString (pTpl=0x1d30b10, pMsg=0x7fbd086a2ba0, iparam=0x1d29b50,
    ttNow=0x7fbcfa7fbb70) at ../template.c:233
#2  0x0000000000477701 in prepareDoActionParams (pAction=0x1d363a0, pWti=0x1d299e0,
    pMsg=0x7fbd086a2ba0, ttNow=0x7fbcfa7fbb70) at ../action.c:991
#3  0x0000000000478cee in processMsgMain (pAction=0x1d363a0, pWti=0x1d299e0, pMsg=0x7fbd086a2ba0,
    ttNow=0x7fbcfa7fbb70) at ../action.c:1516
#4  0x00000000004794ec in doSubmitToActionQ (pAction=0x1d363a0, pWti=0x1d299e0,
    pMsg=0x7fbd086a2ba0) at ../action.c:1693
#5  0x000000000046de54 in execAct (stmt=0x1d35ff0, pMsg=0x7fbd086a2ba0, pWti=0x1d299e0)
    at ruleset.c:209
#6  0x000000000046eda8 in scriptExec (root=0x1d350a0, pMsg=0x7fbd086a2ba0, pWti=0x1d299e0)
    at ruleset.c:599
#7  0x000000000046f055 in processBatch (pBatch=0x1d29a10, pWti=0x1d299e0) at ruleset.c:660
#8  0x000000000040fdae in msgConsumer (notNeeded=0x0, pBatch=0x1d29a10, pWti=0x1d299e0)
    at rsyslogd.c:713
#9  0x0000000000469b0a in ConsumerReg (pThis=0x1d36060, pWti=0x1d299e0) at queue.c:2044
#10 0x0000000000465310 in wtiWorker (pThis=0x1d299e0) at wti.c:374
#11 0x000000000046411d in wtpWorker (arg=0x1d299e0) at wtp.c:422
#12 0x00007fbdb31f11c3 in start_thread () from /bin/gcc/lib/libpthread.so.0
#13 0x00007fbdb157b12d in clone () from /bin/gcc/lib/libc.so.6
(gdb)

**Comment by rgerhards** [comment]
can you run rsyslog under valgrind control and post the result?

**Comment by hxwang1024** [comment]
==36513== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==36513==  Access not within mapped region at address 0x0
==36513==    at 0x4C2BE47: memcpy@@GLIBC_2.14 (vg_replace_strmem.c:1034)
==36513==    by 0x47DC38: tplToString (template.c:233)
==36513==    by 0x477700: prepareDoActionParams (action.c:991)
==36513==    by 0x478CED: processMsgMain (action.c:1516)
==36513==    by 0x4794EB: doSubmitToActionQ (action.c:1693)
==36513==    by 0x46DE53: execAct (ruleset.c:209)
==36513==    by 0x46EDA7: scriptExec (ruleset.c:599)
==36513==    by 0x46F054: processBatch (ruleset.c:660)
==36513==    by 0x40FDAD: msgConsumer (rsyslogd.c:713)
==36513==    by 0x469B09: ConsumerReg (queue.c:2044)
==36513==    by 0x46530F: wtiWorker (wti.c:374)
==36513==    by 0x46411C: wtpWorker (wtp.c:422)
==36513==  If you believe this happened as a result of a stack
==36513==  overflow in your program's main thread (unlikely but
==36513==  possible), you can try to increase the size of the
==36513==  main thread stack using the --main-stacksize= flag.
==36513==  The main thread stack size used in this run was 8388608.

**Comment by hxwang1024** [comment]
how to fix bug  in rsyslog version 8.38.0?

**Comment by rgerhards** [comment]
Was the valgrind run with the old or the current version?

**Comment by hxwang1024** [comment]
> Was the valgrind run with the old or the current version?

valgrind version: 3.14.0
rsyslogd: 8.38.0

**Comment by hxwang1024** [comment]
rsyslog: 8.38.0
valgrind: 3.14.0


valgrind memcheck log:

......

==36513== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==36513==  Access not within mapped region at address 0x0
==36513==    at 0x4C2BE47: memcpy@@GLIBC_2.14 (vg_replace_strmem.c:1034)
==36513==    by 0x47DC38: tplToString (template.c:233)
==36513==    by 0x477700: prepareDoActionParams (action.c:991)
==36513==    by 0x478CED: processMsgMain (action.c:1516)
==36513==    by 0x4794EB: doSubmitToActionQ (action.c:1693)
==36513==    by 0x46DE53: execAct (ruleset.c:209)
==36513==    by 0x46EDA7: scriptExec (ruleset.c:599)
==36513==    by 0x46F054: processBatch (ruleset.c:660)
==36513==    by 0x40FDAD: msgConsumer (rsyslogd.c:713)
==36513==    by 0x469B09: ConsumerReg (queue.c:2044)
==36513==    by 0x46530F: wtiWorker (wti.c:374)
==36513==    by 0x46411C: wtpWorker (wtp.c:422)
==36513==  If you believe this happened as a result of a stack
==36513==  overflow in your program's main thread (unlikely but
==36513==  possible), you can try to increase the size of the
==36513==  main thread stack using the --main-stacksize= flag.
==36513==  The main thread stack size used in this run was 8388608.

.....




[cid:c73a9b9a-41be-489d-9688-c45c35d085df]


how to fix the bug in rsyslog version 8.38.0.

I have find the problem in rsyslog latest version 8.1903.0.


________________________________

**Comment by rgerhards** [comment]
> rsyslog: 8.38.0

Is there any specific reason that you always revert back to the old and unsupported version?

**Comment by hxwang1024** [comment]
> > rsyslog: 8.38.0
> 
> Is there any specific reason that you always revert back to the old and unsupported version?

I find the same problem in rsyslog latest version 8.1903.0.

**Comment by rgerhards** [comment]
> I find the same problem in rsyslog latest version 8.1903.0.

That doesn't really help me. If I want to debug this, I need you on the supported version. Else I never know we are talking about the same thing.

**Comment by hxwang1024** [comment]
[root@instance001 rsyslog]# ./sbin/rsyslogd -version
rsyslogd  8.1903.0 (aka 2019.01) compiled with:
	PLATFORM:				x86_64-unknown-linux-gnu
	PLATFORM (lsb_release -d):		Description:	CentOS Linux release 7.6.1810 (Core)
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Config file:				/etc/rsyslog.conf
	PID file:				/var/run/rsyslogd.pid
	Number of Bits in RainerScript integers: 64

**Comment by rgerhards** [comment]
hehe... yeah, I now you can post the version info from the different version ;-) The key point is that you actually use it. Can you redo the valgrind test with it so that source locations are correct? Do you intend to use the new version for further testing?

**Comment by hxwang1024** [comment]
![image](https://user-images.githubusercontent.com/33044973/54591028-4701dc00-4a64-11e9-861e-def3eb3319be.png)


[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000004c2e223 in _vgr20180ZZ_libcZdsoZa_memcpyZAZAGLIBCZu2Zd14 (dst=0x0, src=<optimized out>,
(gdb) bt
#0  0x0000000004c2e223 in _vgr20180ZZ_libcZdsoZa_memcpyZAZAGLIBCZu2Zd14 (dst=0x0, src=<optimized out>,
    len=<optimized out>) at ../shared/vg_replace_strmem.c:1022
#1  0x000000000045f29d in tplToString (pTpl=0x81c64a0, pMsg=pMsg@entry=0x1268e1c0,
    iparam=iparam@entry=0xb039ae0, ttNow=ttNow@entry=0xe742970) at ../template.c:231
#2  0x0000000000459c89 in prepareDoActionParams (ttNow=0xe742970, pMsg=0x1268e1c0, pWti=0xb039960,
    pWti@entry=0xb039ab0, pAction=0x81d1850, pAction@entry=0x1) at ../action.c:993
#3  processMsgMain (pAction=pAction@entry=0x81d1850, pWti=pWti@entry=0xb039960,
    pMsg=pMsg@entry=0x1268e1c0, ttNow=ttNow@entry=0xe742970) at ../action.c:1516
#4  0x000000000045a154 in doSubmitToActionQ (pAction=0x81d1850, pWti=0xb039960, pMsg=0x1268e1c0)
    at ../action.c:1693
#5  0x0000000000452b05 in execAct (stmt=0x81d0210, pWti=0xb039960, pMsg=0x1268e1c0) at ruleset.c:209
#6  scriptExec (root=<optimized out>, pMsg=pMsg@entry=0x1268e1c0, pWti=pWti@entry=0xb039960)
    at ruleset.c:599
#7  0x0000000000453665 in processBatch (pBatch=0xb039990, pWti=0xb039960) at ruleset.c:660
#8  0x000000000040e85c in msgConsumer (notNeeded=<optimized out>, pBatch=0xb039990, pWti=0xb039960)
    at rsyslogd.c:696
#9  0x000000000044ef7c in ConsumerReg (pThis=0x81d3190, pWti=0xb039960) at queue.c:2106
#10 0x000000000044bf7e in wtiWorker (pThis=pThis@entry=0xb039960) at wti.c:428
#11 0x000000000044a997 in wtpWorker (arg=0xb039960) at wtp.c:427
#12 0x0000000005053dd5 in start_thread () from /lib64/libpthread.so.0
#13 0x0000000005fb6ead in clone () from /lib64/libc.so.6


rsyslogt latest version 8.1903.0

**Comment by hxwang1024** [comment]
![image](https://user-images.githubusercontent.com/33044973/54591289-e6bf6a00-4a64-11e9-901d-5cc587994176.png)

**Comment by rgerhards** [comment]
can you create a debug log? see https://www.rsyslog.com/doc/master/troubleshooting/howtodebug.html?highlight=debug%20log

I probably need the last 10,000 lines before the segfault, best the complete log. With just the tail it may be I do not see the real cause.

**Comment by rgerhards** [comment]
**full** config pls in addition to debug log. Stack trace is now useful.

**Comment by hxwang1024** [comment]
> **full** config pls in addition to debug log. Stack trace is now useful.

I have send rsyslog debug log by mail.

**Comment by rgerhards** [comment]
@hxwang1024 thx - pls also send the config.

Did rsyslog segfault like in the other cases when the debug log was active? I ask, because the log looks a bit strange when I compare it to the backtrace / valgrind report.

**Comment by rgerhards** [comment]
@hxwang1024 I really need your full config (or full debug log) to make sense out of the debug log you sent.

**Comment by hxwang1024** [comment]
> @hxwang1024 I really need your full config (or full debug log) to make sense out of the debug log you sent.

So sorry,  too busy the last few days. I have send full config to your mail.
Look forward to your reply.

**Comment by hxwang1024** [comment]
@rgerhards If you have any question, you can test rsyslog with my full config.

**Comment by rgerhards** [comment]
busy... how do you test rsyslog w/ wrk? Is it a syslog sender, doesn't look so...

**Comment by hxwang1024** [comment]
> busy... how do you test rsyslog w/ wrk? Is it a syslog sender, doesn't look so...

wrk->nginx->rsyslog

**Comment by rgerhards** [comment]
Apologies for the very late follow-up. This is probably no longer relevant for the original reporter, but I want to leave the resolution here for people finding this issue through search.

We do not close old issues just because they are old; we are working through the backlog and closing only when there is concrete evidence.

The useful public evidence here is the backtrace showing the crash in template expansion:

```text
tplToString()
prepareDoActionParams()
processMsgMain()
```

That failure pattern matches a later core template/action parameter lifetime fix:

```text
785299709954d5ee41da1657e262bf641dc83f84
bugfix core: potential segfault in template engine
```

That change resets the action parameter state (`param`, `lenBuf`, and `lenStr`) after releasing prepared action parameters, avoiding reuse of stale template/action parameter buffers. The commit is in current `main`.

There is no public reproducer or complete config left in this issue that can be retested today; the follow-up config/debug data was sent privately at the time. Given the matching template-engine fix and the age of the report, I am closing this as resolved/no longer actionable in this issue.

If this still reproduces with a current rsyslog version, please open a new issue with the current version, full config, and a fresh backtrace or sanitizer/valgrind output so we can investigate that case directly.
