### ISSUE TITLE
Crash when using property parameter controlcharacters="escape"

### ISSUE THREAD

**Issue by hakman** [rsyslog/rsyslog#367]
Using controlcharacters="escape" in a template triggers a crash. This should happen for any log line containing a control character. I will provide a possible fix in a PR soon.

Stack trace:

```
(gdb) run
Starting program: /home/ubuntu/rsyslogd -n
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff0edc700 (LWP 9547)]
[New Thread 0x7ffff06db700 (LWP 9548)]
[New Thread 0x7fffefeda700 (LWP 9549)]
[New Thread 0x7fffef6d9700 (LWP 9550)]
*** Error in `/home/ubuntu/rsyslogd': munmap_chunk(): invalid pointer: 0x00007fffd8092c22 ***

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffef6d9700 (LWP 9550)]
0x00007ffff6bf4cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6bf4cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6bf80d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6c31394 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff6d3fb28 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff6c3c0f7 in malloc_printerr (action=<optimized out>, str=0x7ffff6d3fea8 "munmap_chunk(): invalid pointer", ptr=<optimized out>) at malloc.c:4996
#4  0x000000000041cecf in MsgGetProp (pMsg=pMsg@entry=0x7fffe40cff40, pTpe=pTpe@entry=0x6df9e0, pProp=pProp@entry=0x6dfa00, pPropLen=pPropLen@entry=0x7fffef6d89c4, 
    pbMustBeFreed=pbMustBeFreed@entry=0x7fffef6d89c2, ttNow=ttNow@entry=0x7fffef6d8a90) at msg.c:3773
#5  0x000000000043f9bc in tplToString (pTpl=0x6de830, pMsg=pMsg@entry=0x7fffe40cff40, iparam=iparam@entry=0x7fffd804a320, ttNow=ttNow@entry=0x7fffef6d8a90) at ../template.c:194
#6  0x000000000043b5cf in prepareDoActionParams (pWti=0x6b09e0, ttNow=0x7fffef6d8a90, pMsg=0x7fffe40cff40, pAction=0x6ddcf0) at ../action.c:933
#7  processMsgMain (pAction=pAction@entry=0x6ddcf0, pWti=pWti@entry=0x6b09e0, pMsg=0x7fffe40cff40, ttNow=ttNow@entry=0x7fffef6d8a90) at ../action.c:1300
#8  0x000000000043bd27 in doSubmitToActionQ (pAction=0x6ddcf0, pWti=0x6b09e0, pMsg=<optimized out>) at ../action.c:1449
#9  0x0000000000434d27 in execAct (stmt=0x6dfaa0, pWti=0x6b09e0, pMsg=0x7fffe40cff40) at ruleset.c:202
#10 scriptExec (root=<optimized out>, pMsg=pMsg@entry=0x7fffe40cff40, pWti=pWti@entry=0x6b09e0) at ruleset.c:454
#11 0x0000000000434dc5 in execPRIFILT (pWti=<optimized out>, pMsg=<optimized out>, stmt=<optimized out>) at ruleset.c:314
#12 scriptExec (root=<optimized out>, pMsg=pMsg@entry=0x7fffe40cff40, pWti=pWti@entry=0x6b09e0) at ruleset.c:472
#13 0x00000000004354e4 in processBatch (pBatch=0x6b0a10, pWti=0x6b09e0) at ruleset.c:508
#14 0x0000000000443cbc in msgConsumer (notNeeded=<optimized out>, pBatch=0x6b0a10, pWti=0x6b09e0) at rsyslogd.c:575
#15 0x0000000000431cfb in ConsumerReg (pThis=0x6b03b0, pWti=0x6b09e0) at queue.c:1897
#16 0x000000000042e00e in wtiWorker (pThis=pThis@entry=0x6b09e0) at wti.c:334
#17 0x000000000042d1b8 in wtpWorker (arg=0x6b09e0) at wtp.c:389
#18 0x00007ffff79ab182 in start_thread (arg=0x7fffef6d9700) at pthread_create.c:312
#19 0x00007ffff6cb847d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) 
```

**Comment by rgerhards** [comment]
fixed, but closing issue was forgotten. Fix: https://github.com/rsyslog/rsyslog/pull/369
