### ISSUE TITLE
rsyslog 8.1904 crashed 

### ISSUE THREAD

**Issue by fduan001** [rsyslog/rsyslog#4546]
### Environment
- rsyslog version: 
- platform:  
- for configuration questions/issues, include rsyslog.conf and included config files

`(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at /usr/src/debug/glibc/2.27-r0/git/sysdeps/unix/sysv/linux/raise.c:51
#1  0x0000003b77a35641 in __GI_abort () at /usr/src/debug/glibc/2.27-r0/git/stdlib/abort.c:79
#2  0x0000003b77a2d41a in __assert_fail_base (fmt=0x3b77b79320 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0x3b782136d2 "mutex->__data.__owner == 0", file=file@entry=0x3b782136b5 "../nptl/pthread_mutex_lock.c",
    line=line@entry=79, function=function@entry=0x3b78213840 <__PRETTY_FUNCTION__.8858> "__pthread_mutex_lock")
    at /usr/src/debug/glibc/2.27-r0/git/assert/assert.c:92
#3  0x0000003b77a2d492 in __GI___assert_fail (assertion=assertion@entry=0x3b782136d2 "mutex->__data.__owner == 0",
    file=file@entry=0x3b782136b5 "../nptl/pthread_mutex_lock.c", line=line@entry=79,
    function=function@entry=0x3b78213840 <__PRETTY_FUNCTION__.8858> "__pthread_mutex_lock")
    at /usr/src/debug/glibc/2.27-r0/git/assert/assert.c:101
#4  0x0000003b78209c20 in __GI___pthread_mutex_lock (mutex=mutex@entry=0x69f860)
    at /usr/src/debug/glibc/2.27-r0/git/nptl/pthread_mutex_lock.c:79
#5  0x000000000041be4c in iminternalRemoveMsg (ppMsg=ppMsg@entry=0x7fff1cf99850)
    at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/tools/iminternal.c:138
#6  0x0000000000410f32 in processImInternal () at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/tools/rsyslogd.c:1660
#7  0x000000000040e70f in mainloop () at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/tools/rsyslogd.c:1920
#8  main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/tools/rsyslogd.c:2107
`
`(gdb) f 4
#4  0x0000003b78209c20 in __GI___pthread_mutex_lock (mutex=mutex@entry=0x69f860)
    at /usr/src/debug/glibc/2.27-r0/git/nptl/pthread_mutex_lock.c:79
79            assert (mutex->__data.__owner == 0);
(gdb) p mutex
$3 = (pthread_mutex_t *) 0x69f860
(gdb) p *mutex
$4 = {__data = {__lock = 1, __count = 0, __owner = 5591, __nusers = 4294966788, __kind = 0, __spins = 0, __elision = 0, __list = {
      __prev = 0x0, __next = 0x0}},
  __size = "\001\000\000\000\000\000\000\000\327\025\000\000\004\376\377\377", '\000' <repeats 23 times>, __align = 1}`

`(gdb) info threads
  Id   Target Id         Frame
* 1    LWP 14905         0x0000003b78209c20 in __GI___pthread_mutex_lock (mutex=mutex@entry=0x69f860)
    at /usr/src/debug/glibc/2.27-r0/git/nptl/pthread_mutex_lock.c:79
  2    LWP 14907         0x0000003b782105a4 in __libc_read (fd=3, buf=buf@entry=0x7f61dd2d5da0, nbytes=nbytes@entry=8096)
    at /usr/src/debug/glibc/2.27-r0/git/sysdeps/unix/sysv/linux/read.c:27
  3    LWP 14906         0x0000003b77ae86a9 in __GI___poll (fds=fds@entry=0x7f61d8000b60, nfds=1, timeout=timeout@entry=-1)
    at /usr/src/debug/glibc/2.27-r0/git/sysdeps/unix/sysv/linux/poll.c:29
  4    LWP 14908         0x0000003b77aea657 in __GI___select (nfds=nfds@entry=0, readfds=readfds@entry=0x0,
    writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7f61dcef4d50)
    at /usr/src/debug/glibc/2.27-r0/git/sysdeps/unix/sysv/linux/select.c:41
  5    LWP 14909         0x0000003b77af279f in epoll_wait (epfd=epfd@entry=8, events=events@entry=0x7f61dcaf1400,
    maxevents=maxevents@entry=10, timeout=timeout@entry=-1)
    at /usr/src/debug/glibc/2.27-r0/git/sysdeps/unix/sysv/linux/epoll_wait.c:30
  6    LWP 5591          0x0000003b77a34827 in kill () at ../sysdeps/unix/syscall-template.S:78
  7    LWP 21029         0x0000003b7820d20c in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x8c04b4)
    at /usr/src/debug/glibc/2.27-r0/git/sysdeps/unix/sysv/linux/futex-internal.h:88
  8    LWP 14910         __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  9    LWP 14912         0x0000003b7820d20c in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x8bc2b4)
    at /usr/src/debug/glibc/2.27-r0/git/sysdeps/unix/sysv/linux/futex-internal.h:88
`

`#0  0x0000003b77a34827 in kill () at ../sysdeps/unix/syscall-template.S:78
#1  0x000000000041bd6c in iminternalAddMsg (pMsg=<optimized out>)
    at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/tools/iminternal.c:111
#2  0x000000000040faf5 in logmsgInternalSubmit (flags=1,
    msg=0x7f61ce7fa800 "file '/var/log/lmd.log'[1] write error - see https://www.rsyslog.com/solving-rsyslog-write-errors/ for help OS error: No space left on device [v8.1904.0 try https://www.rsyslog.com/e/2027 ]", lenMsg=189, pri=43, iErr=-2027)
    at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/tools/rsyslogd.c:910
#3  logmsgInternal (iErr=-2027, pri=<optimized out>, msg=<optimized out>, flags=0)
    at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/tools/rsyslogd.c:942
#4  0x00000000004407ac in doLogMsg (iErrno=iErrno@entry=28, iErrCode=iErrCode@entry=-2027, severity=severity@entry=3,
    msg=msg@entry=0x7f61ce7fb060 "file '/var/log/lmd.log'[1] write error - see https://www.rsyslog.com/solving-rsyslog-write-errors/ for help OS error") at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/runtime/errmsg.c:128
#5  0x000000000044096b in LogError (iErrno=iErrno@entry=28, iErrCode=iErrCode@entry=-2027,
    fmt=fmt@entry=0x47c6b8 "file '%s'[%d] write error - see https://www.rsyslog.com/solving-rsyslog-write-errors/ for help OS error")
    at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/runtime/errmsg.c:159
#6  0x00000000004492f7 in doWriteCall (pLenBuf=<synthetic pointer>, pBuf=<optimized out>, pThis=0x7f61c40330e0)
    at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/runtime/stream.c:1447
#7  strmPhysWrite (pThis=0x7f61c40330e0, pBuf=<optimized out>, lenBuf=<optimized out>)
    at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/runtime/stream.c:1737
#8  0x000000000044b01f in strmFlush (pThis=0x7f61c40330e0)
    at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/runtime/stream.c:1900
#9  0x0000000000417203 in commitTransaction (pWrkrData=<optimized out>, pParams=0x7f61ce7fba90, nParams=1)
    at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/tools/omfile.c:1065
#10 0x000000000045ae77 in actionCallCommitTransaction (nparams=<optimized out>, iparams=<optimized out>, pWti=<optimized out>,
    pThis=<optimized out>) at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/action.c:1211
#11 doTransaction (nparams=1, iparams=0x7f61ce7fba90, pWti=0x8c1550, pThis=0x918100)
    at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/action.c:1256
#12 actionTryCommit (pThis=0x918100, pWti=0x8c1550, iparams=0x7f61ce7fba90, nparams=1)
    at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/action.c:1298
#13 0x000000000045b448 in actionTryRemoveHardErrorsFromBatch (new_nMsgs=<synthetic pointer>, new_iparams=0x7f61b4019e70,
    pWti=0x8c1550, pThis=0x918100) at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/action.c:1424
#14 actionCommit (pThis=pThis@entry=0x918100, pWti=pWti@entry=0x8c1550)
    at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/action.c:1491
#15 0x000000000045cadc in actionCommitAllDirect (pWti=pWti@entry=0x8c1550)
    at /usr/src/debug/rsyslog/8.1904.0-r7/rsyslog-8.1904.0/action.c:1556
#16 0x00000000004557ca in processBatch (pBatch=0x8c1580, pWti=0x8c1550)`

**Comment by davidelang** [comment]
when you run out of disk space, bad things will happen, including causing 
rsyslog to queue messages, which will use more ram (up to the configured max 
queue size) and that could cause the system to kill it.

David Lang
