### ISSUE TITLE
rsyslog crashed when receive the SIGNAL 15

### ISSUE THREAD

**Issue by john1jxm** [rsyslog/rsyslog#4549]
### Expected behavior
rsyslogd exit gracefully
### Actual behavior
rsyslogd crashed
### Steps to reproduce the behavior
don't know
### Environment
rsyslog-8.33.1

call statck info:
(gdb) bt
#0  0x77d92f5c in raise () from /repo/xianminj/BBD_R2101/rootfs/mtk/fs.install/lib/libc.so.0
#1  0x77d8b874 in abort () from /repo/xianminj/BBD_R2101/rootfs/mtk/fs.install/lib/libc.so.0
#2  0x0040e380 in rsyslogdDoDie (sig=15) at rsyslogd.c:1697
#3  <signal handler called>
#4  0x77e59e6c in pthread_cond_timedwait () from /repo/xianminj/BBD_R2101/rootfs/mtk/fs.install/lib/libpthread.so.0
#5  0x00491020 in wtpShutdownAll (pThis=0xb82b00, tShutdownCmd=wtpState_SHUTDOWN, ptTimeout=0x7fd06d50) at wtp.c:262
#6  0x00497fe8 in tryShutdownWorkersWithinQueueTimeout (pThis=0xb82810) at queue.c:1181
#7  0x00498960 in qqueueShutdownWorkers (pThis=0xb82810) at queue.c:1368
#8  0x0049d07c in qqueueDestruct (ppThis=0x4fdd14 <pMsgQueue>) at queue.c:2684
#9  0x0040e838 in deinitAll () at rsyslogd.c:1881
#10 0x0040ed6c in main (argc=3, argv=0x7fd07054) at rsyslogd.c:1989

**Comment by davidelang** [comment]
8.33 is several years old, can you try to reproduce this with 8.2012 or 8.2102?

David Lang

**Comment by rgerhards** [comment]
Apologies for the very late reply. This is probably no longer relevant to the original reporter, but I am adding the conclusion for people who arrive here via search while we work through the backlog. We do not close rsyslog issues lightly, and we are not closing this merely because of age.

Triage result: not reproducible / needs reporter info.

Reasoning: The SIGTERM crash report was against 8.33.1. A maintainer asked for current reproduction details, but none were added.

If this still reproduces on a current rsyslog release and maintained platform, please open a new issue with the current version, complete configuration, logs, and a minimal reproducer so we can investigate it as a fresh current problem.
