### ISSUE TITLE
rsyslogd crashed

### ISSUE THREAD

**Issue by Rampa33** [rsyslog/rsyslog#4565]
### Environment
rsyslogd  8.1907.0 (aka 2019.07) compiled with:
	PLATFORM:				x86_64-openwrt-linux-gnu
	PLATFORM (lsb_release -d):		Description:	Ubuntu 14.04.1 LTS
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	No
	64bit Atomic operations supported:	No
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			No
	Config file:				/etc/rsyslog.conf
	PID file:				/var/run/rsyslogd.pid
	Number of Bits in RainerScript integers: 64

-----------------------------------------------------------

gdb: warning: Couldn't determine a path for the index cache directory.
[New LWP 3298]
[New LWP 3336]
[New LWP 3337]
[New LWP 3339]
[New LWP 3335]
[New LWP 3340]
[New LWP 6190]
[New LWP 6186]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Core was generated by `/usr/sbin/rsyslogd -n'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f96bfae7cc9 in raise () from /lib/libc.so.6
[Current thread is 1 (Thread 0x7f96c10e0700 (LWP 3298))]

====================== CURRENT THREAD =========================

#0  0x00007f96bfae7cc9 in raise () from /lib/libc.so.6
No symbol table info available.
#1  0x00007f96bfaead68 in abort () from /lib/libc.so.6
No symbol table info available.
#2  0x00007f96bfae105f in __assert_fail_base () from /lib/libc.so.6
No symbol table info available.
#3  0x00007f96bfae10f2 in __assert_fail () from /lib/libc.so.6
No symbol table info available.
#4  0x00007f96c0a9c5a0 in pthread_mutex_lock () from /lib/libpthread.so.0
No symbol table info available.
#5  0x000000000041c11c in iminternalRemoveMsg (ppMsg=ppMsg@entry=0x7ffe29dc5d70) at iminternal.c:138
        iRet = RS_RET_OK
        pThis = 0x40f4f8 <_start>
        llCookie = 0x0
#6  0x0000000000411992 in processImInternal () at rsyslogd.c:1680
        pMsg = 0x0
        repMsg = 0x40f4f8 <_start>
#7  0x000000000040f0fd in mainloop () at rsyslogd.c:1945
        tTime = 1615908393
        tTime = <optimized out>
#8  main (argc=<optimized out>, argv=<optimized out>) at rsyslogd.c:2134
        log_dflt = <optimized out>

======================= SHARED LIBS ===========================

**Comment by Rampa33** [comment]
notify @rgerhards  @davidelang

**Comment by davidelang** [comment]
once you have duplicated this with a current version, please provide us with 
your config and some infoon what was happening at the time of the crash.

a core file combined with the debug info cn provide info, but that takes a long 
time to go through blindly, and we are all voluneteers, so the more infowe have 
tostart with the better.

David Lang

**Comment by Rampa33** [comment]
Thanks David and Rainer for a quick response. Let me upgrade and get back if the issue is seen again
