### ISSUE TITLE
rsyslog 8.11 relp crashes when enabling keepalive

### ISSUE THREAD

**Issue by lemsx1** [rsyslog/rsyslog#459]
Rsyslog rsyslog-8.11.0-2.el6.x86_64 (RPM)
librelp librelp-1.2.5-2.el6.x86_64

Server imrelp:
```
# Provides reliable TCP syslog reception
module(load="imrelp")
input(type="imrelp" port="14504" ... keepalive="on")
```
Client omrelp:
```
:omrelp:server-ip-here:14504
```
Run server:
```
valgrind --log-fd=1 rsyslogd -dn -i /var/run/syslog14504.pid -f /etc/rsyslog.14504.conf
```
Output:
```
1771.458255332:imrelp.c       : librelp: done epoll_wait, nEvents:1
1771.459989153:imrelp.c       : new connect on RELP socket #3
==6520== Thread 2:
==6520== Invalid read of size 8
==6520==    at 0x6E4E8EA: relpTcpAcceptConnReq (tcp.c:684)
==6520==    by 0x6E4C2FB: relpSessAcceptAndConstruct (relpsess.c:191)
==6520==    by 0x6E4A641: engineEventLoopRun (relp.c:589)
==6520==    by 0x6E4A879: relpEngineRun (relp.c:950)
==6520==    by 0x6C421A0: runInput (imrelp.c:636)
==6520==    by 0x14CDE2: thrdStarter (threads.c:212)
==6520==    by 0x504A9D0: start_thread (pthread_create.c:301)
==6520==    by 0x617F8FC: clone (clone.S:115)
==6520==  Address 0x8 is not stack'd, malloc'd or (recently) free'd
==6520== 
==6520== 
==6520== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==6520==  Access not within mapped region at address 0x8
==6520==    at 0x6E4E8EA: relpTcpAcceptConnReq (tcp.c:684)
==6520==    by 0x6E4C2FB: relpSessAcceptAndConstruct (relpsess.c:191)
==6520==    by 0x6E4A641: engineEventLoopRun (relp.c:589)
==6520==    by 0x6E4A879: relpEngineRun (relp.c:950)
==6520==    by 0x6C421A0: runInput (imrelp.c:636)
==6520==    by 0x14CDE2: thrdStarter (threads.c:212)
==6520==    by 0x504A9D0: start_thread (pthread_create.c:301)
==6520==    by 0x617F8FC: clone (clone.S:115)
==6520==  If you believe this happened as a result of a stack
==6520==  overflow in your program's main thread (unlikely but
==6520==  possible), you can try to increase the size of the
==6520==  main thread stack using the --main-stacksize= flag.
==6520==  The main thread stack size used in this run was 10485760.
==6520== 
==6520== HEAP SUMMARY:
==6520==     in use at exit: 908,447 bytes in 1,237 blocks
==6520==   total heap usage: 1,988 allocs, 751 frees, 1,032,159 bytes allocated
==6520== 
==6520== LEAK SUMMARY:
==6520==    definitely lost: 0 bytes in 0 blocks
==6520==    indirectly lost: 0 bytes in 0 blocks
==6520==      possibly lost: 576 bytes in 2 blocks
==6520==    still reachable: 907,871 bytes in 1,235 blocks
==6520==         suppressed: 0 bytes in 0 blocks
==6520== Rerun with --leak-check=full to see details of leaked memory
==6520== 
==6520== For counts of detected and suppressed errors, rerun with: -v
==6520== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 29 from 9)
Killed
```

GNU dbg:
```
(gdb) bt
#0  0x00007f200a3d48ea in EnableKeepAlive (ppThis=0x7f2004002150, 
    sock=<value optimized out>, pSrv=0x7f200d86a3a0) at tcp.c:684
#1  relpTcpAcceptConnReq (ppThis=0x7f2004002150, sock=<value optimized out>, 
    pSrv=0x7f200d86a3a0) at tcp.c:713
#2  0x00007f200a3d22fc in relpSessAcceptAndConstruct (ppThis=0x7f2009a9ec08, 
    pSrv=0x7f200d86a3a0, sock=0) at relpsess.c:191
#3  0x00007f200a3d0642 in handleConnectionRequest (pThis=0x7f200d86a2b0)
    at relp.c:589
#4  engineEventLoopRun (pThis=0x7f200d86a2b0) at relp.c:770
#5  0x00007f200a3d087a in relpEngineRun (pThis=0x7f200d86a2b0) at relp.c:950
#6  0x00007f200a5de1a1 in runInput (pThrd=<value optimized out>)
    at imrelp.c:636
#7  0x00007f200c459de3 in thrdStarter (arg=0x7f200d86ff80) at ../threads.c:212
#8  0x00007f200bdc79d1 in start_thread (arg=0x7f2009a9f700)
    at pthread_create.c:301
#9  0x00007f200acdd8fd in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:115
(gdb) quit
```

**Comment by lemsx1** [comment]
The following fixes the problem:

```diff
diff -burN librelp-1.2.5.orig/src/tcp.c librelp-1.2.5/src/tcp.c
--- librelp-1.2.5.orig/src/tcp.c	2014-03-20 04:02:05.000000000 -0400
+++ librelp-1.2.5/src/tcp.c	2015-07-28 13:49:31.818395751 -0400
@@ -681,7 +681,7 @@
 			  RELP_RET_WRN_NO_KEEPALIVE);
 	}
 
-	pThis->pEngine->dbgprint("KEEPALIVE enabled for socket %d\n", sock);
+	//pThis->pEngine->dbgprint("KEEPALIVE enabled for socket %d\n", sock);
 
 done:
   	return;
```

**Comment by lemsx1** [comment]
So, this is really a librelp problem

**Comment by alorbach** [comment]
Yes, solved thanks to your fix ;).
