### ISSUE TITLE
rsyslog  can not output java "Caused by: java.sql.SQLException" log 

### ISSUE THREAD

**Issue by Blue-Skies-firststar** [rsyslog/rsyslog#4608]
my  CentOS release 6.8  and  rsyslog33  and   logback-core-1.1.2 
Cannot output java logs  that for example   to the rsyslog  log server

-- Cause: java.sql.SQLException: ORA-00001: unique constraint
	at com.ctc.bms.unity.common.aop.DaoAspect.proceed(DaoAspect.java:56) ~[app/:na]
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_20]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_20]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627) [spring.jar:2.5.6.SEC01]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616) [spring.jar:2.5.6.SEC01]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:64) [spring.jar:2.5.6.SEC01]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171) [spring.jar:2.5.6.SEC01]
#######################################################################################
cat /etc/rsyslog.conf
$template RemoteLogs,"/logs/%programname%/%PROGRAMNAME%_%$year%-%$month%-%$day%.log"
$template myFormat,"%procid%,%source%:%msg%\n"
local0.*        ?RemoteLogs;myFormat

######################################################################################
cat  logback.xml

	
	<appender name="all_log" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <layout class="ch.qos.logback.classic.PatternLayout">
            <Pattern>%date{yyyy-MM-dd HH:mm:ss:SSS}|-%-5level-|UserAgent=[%X{req.userAgent}],SourceIP=[%X{req.xForwardedFor}],%msg%n</Pattern>
        </layout>
        <File>${log.dir}/all.log</File>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
	    	<FileNamePattern>${log.dir}/all.%d{yyyy-MM-dd}.log</FileNamePattern>	
	    	<maxHistory>30</maxHistory>
        </rollingPolicy>
	</appender>
	
	
	<appender name="all_remote_log" class="ch.qos.logback.classic.net.SyslogAppender">
    	<syslogHost>${log.syslogHost}</syslogHost>
		<port>${log.syslogPort}</port>
		<facility>local0</facility>
                <suffixPattern>mylogr %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n</suffixPattern>
	</appender>

**Comment by rgerhards** [comment]
Apologies for the very late reply. This is probably no longer relevant to the original reporter, but I am adding the conclusion for people who arrive here via search while we work through the backlog. We do not close rsyslog issues lightly, and we are not closing this merely because of age.

Triage result: not reproducible / needs reporter info.

Reasoning: This is a very old CentOS 6 / rsyslog33 support report with no retained config, reproducer, or current-version evidence.

If this still reproduces on a current rsyslog release and maintained platform, please open a new issue with the current version, complete configuration, logs, and a minimal reproducer so we can investigate it as a fresh current problem.
