### ISSUE TITLE
rsyslog-8.2104

### ISSUE THREAD

**Issue by john1jxm** [rsyslog/rsyslog#4635]
### Expected behavior
nerver crash
### Actual behavior
crashed sometime
### Steps to reproduce the behavior
only run rsyslogd

### Environment
rsyslog-8.2104
- platform:   linux run on embbed device
- configuration
module(load="imuxsock")
module(load="imklog")
$template FileFormat,"[%syslogseverity-text%] <%PRI%>1 %TIMESTAMP:::date-rfc3339% %HOSTNAME% %APP-NAME% %PROCID% %MSGID% %STRUCTURED-DATA% %msg%\n"
$outchannel messages_rotation,/logs/messages, 2097152,/usr/sbin/syslog_rotation_script.sh /logs/messages
auth,authpriv,user.notice;kern,syslog,daemon.notice :omfile:$messages_rotation;FileFormat
$outchannel customer_rotation,/logs/customer, 2097152,/usr/sbin/syslog_rotation_script.sh /logs/customer
local0. :omfile:$customer_rotation;FileFormat

core dump:
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
Core was generated by `rsyslogd -f /tmp/rsyslog.conf'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x774d066c in ?? ()
(gdb) set sysroot /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install
Reading symbols from /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/libpthread.so.0...(no debugging symbols found)...done.
Loaded symbols for /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/libpthread.so.0
Reading symbols from /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/libm.so.0...(no debugging symbols found)...done.
Loaded symbols for /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/libm.so.0
Reading symbols from /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/libz.so.1...(no debugging symbols found)...done.
Loaded symbols for /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/libz.so.1
Reading symbols from /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/libdl.so.0...(no debugging symbols found)...done.
Loaded symbols for /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/libdl.so.0
Reading symbols from /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/librt.so.0...(no debugging symbols found)...done.
Loaded symbols for /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/librt.so.0
Reading symbols from /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/libestr.so.0...(no debugging symbols found)...done.
Loaded symbols for /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/libestr.so.0
Reading symbols from /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/libfastjson.so.4...(no debugging symbols found)...done.
Loaded symbols for /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/libfastjson.so.4
Reading symbols from /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/libc.so.0...(no debugging symbols found)...done.
Loaded symbols for /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/libc.so.0
Reading symbols from /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/ld-uClibc.so.0...(no debugging symbols found)...done.
Loaded symbols for /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/ld-uClibc.so.0
Reading symbols from /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/usr/lib/rsyslog/lmnet.so...done.
Loaded symbols for /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/usr/lib/rsyslog/lmnet.so
Reading symbols from /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/usr/lib/rsyslog/imudp.so...done.
Loaded symbols for /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/usr/lib/rsyslog/imudp.so
Reading symbols from /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/usr/lib/rsyslog/imuxsock.so...done.
Loaded symbols for /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/usr/lib/rsyslog/imuxsock.so
Reading symbols from /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/usr/lib/rsyslog/imklog.so...done.
Loaded symbols for /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/usr/lib/rsyslog/imklog.so
(gdb) bt
#0  0x774d066c in malloc () from /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/libc.so.0
#1  0x0046022c in msgBaseConstruct (ppThis=0x76f9f3dc) at msg.c:841
#2  0x004604d0 in msgConstructWithTime (ppThis=0x76f9f3dc, stTime=0x76f9f5ec, ttGenTime=39585) at msg.c:917
#3  0x774204b0 in SubmitMsg (pRcv=0x8b92d0 "<31>Jan  1 10:59:45 syslog[4197]: DEBUG : /sys/class/net/eth1.0/statistics/tx_window_errors=0", lenRcv=94, pLstn=0x879408,
    cred=0x76fa1aa0, ts=0x76fa1aac) at imuxsock.c:872
#4  0x774216e8 in readSocket (pLstn=0x879408) at imuxsock.c:1130
#5  0x77423dd0 in runInput (pThrd=0x884a28) at imuxsock.c:1548
#6  0x004bcb30 in thrdStarter (warning: GDB can't find the start of the function at 0x775a70a2.

    GDB is unable to find the start of the function at 0x775a70a2
and thus can't determine the size of that function's stack frame.
This means that GDB may be unable to access that stack frame, or
the frames below it.
    This problem is most likely caused by an invalid program counter or
stack pointer.
    However, if you think GDB should simply search farther back
from 0x775a70a2 for code which looks like the beginning of a
function, you can increase the range of the search using the `set
heuristic-fence-post' command.
arg=0x884a28) at ../threads.c:243
#7  0x775a70a4 in ?? () from /repo/xianminj/BBD_R2102_A/rootfs/mtk/fs.install/lib/libpthread.so.0

**Comment by wxiaoguang** [comment]
It must be caused by this issue: https://github.com/rsyslog/rsyslog/issues/4625

**Comment by rgerhards** [comment]
Apologies for the late reply. This may no longer be relevant to the original reporter, but I am adding the answer for people who arrive here via search while we work through the backlog. We do not close old issues lightly, and we do not close them just because of age.

This is an old crash report against rsyslog 8.2104 on an embedded system, but the issue does not include a stack trace, core details, debug log, or steps that let us reproduce the crash on current code. Without that retained evidence, there is no concrete fix we can make from this issue now.

Closing as not reproducible with the available information. If a similar crash appears on a current rsyslog release, please open a new issue with the current version, full config, backtrace/core details, and any debug log leading up to the crash.
