### ISSUE TITLE
The imtcp module could cause segmentation fault issues during shutdown

### ISSUE THREAD

**Issue by TheGOro** [rsyslog/rsyslog#4776]
### Expected behavior
Rsyslog terminates correctly, without producing coredumps.
### Actual behavior
In some cases, Rsyslog may not able to terminate properly, during shutdown or reboot of its hosting machine, due to segmentation fault issues.
### Root cause
Most of the `tcpsrv` worker threads, that the `imtcp` module creates for each configured input, are not stopped properly during graceful termination. The `rsyslog` main thread meanwhile starts to release their underlying `tcpsrv` "objects" as part of the module de-initialization procedure. As a result of that, these worker threads could receive input and the handling of that (either in the Run loop or its cleanup stage) leads to memory access violation.
```shell
gdb /usr/sbin/rsyslogd core.dbghost-ax3h17dz.1642094690.in:imtcp.29969
```
```gdb
Core was generated by `/usr/sbin/rsyslogd -n'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  Ctl (pNsdpoll=0x7fc5dc000be0, pNsd=0x0, id=0, pUsr=0x1aa7570, mode=1, op=2) at nsdpoll_ptcp.c:200
200                     dbgprintf("removing nsdpoll entry %d/%p, sock %d\n", id, pUsr, pSock->sock);
[Current thread is 1 (Thread 0x7fc60222a700 (LWP 29977))]
```
```gdb
(gdb) bt
#0  Ctl (pNsdpoll=0x7fc5dc000be0, pNsd=0x0, id=0, pUsr=0x1aa7570, mode=1, op=2) at nsdpoll_ptcp.c:200
#1  0x00007fc605ccaea2 in DoRun (pThis=pThis@entry=0x1ac06f0, ppPoll=ppPoll@entry=0x7fc602229b58) at tcpsrv.c:960
#2  0x00007fc605ccb099 in Run (pThis=0x1ac06f0) at tcpsrv.c:1000
#3  0x00007fc6060d69b5 in RunServerThread (myself=0x1aa99b0) at imtcp.c:929
#4  0x00007fc6093fca1a in start_thread (arg=0x7fc60222a700) at pthread_create.c:477
#5  0x00007fc607ee8d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) p pSock
$1 = (nsd_ptcp_t *) 0x0
(gdb) frame 1
#1  0x00007fc605ccaea2 in DoRun (pThis=pThis@entry=0x1ac06f0, ppPoll=ppPoll@entry=0x7fc602229b58) at tcpsrv.c:960
960                     CHKiRet(nspoll.Ctl(pPoll, pThis->ppLstn[i], i, pThis->ppLstn, NSDPOLL_IN, NSDPOLL_DEL));
(gdb) p *pThis
$2 = {objData = {pObjInfo = 0x1ac0960, pszName = 0x1a44010 "\a"}, bUseKeepAlive = 1, iKeepAliveIntvl = 15, iKeepAliveProbes = 3, iKeepAliveTime = 60, pNS = 0x0, iDrvrMode = 0, DrvrChkExtendedKeyUsage = 0, DrvrPrioritizeSan = 0, DrvrTlsVerifyDepth = 0, gnutlsPriorityString = 0x0, pszLstnPortFileName = 0x0,
  pszDrvrAuthMode = 0x0, pszDrvrPermitExpiredCerts = 0x0, pszDrvrCAFile = 0x0, pszDrvrKeyFile = 0x0, pszDrvrCertFile = 0x0, pszDrvrName = 0x0, pszInputName = 0x1aacc40 "@u\252\001", pszOrigin = 0x1aacc80 "0\314\252\001", pRuleset = 0x0, pPermPeers = 0x0, bEmitMsgOnClose = 0 '\000', bUsingEPoll = 1 '\001',
  bUseFlowControl = 1 '\001', bSPFramingFix = 0 '\000', iLstnCurr = 1, ppLstn = 0x1aa7570, ppLstnPort = 0x1aa7620, iLstnMax = 20, iSessMax = 200, dfltTZ = "\000\000\000\000\000\000\000", pLstnPorts = 0x1ac0850, addtlFrameDelim = -1, maxFrameSize = 200000, bDisableLFDelim = 0, discardTruncatedMsg = 0,
  bPreserveCase = 1 '\001', ratelimitInterval = 5, ratelimitBurst = 10000, pSessions = 0x0, pUsr = 0x0, pIsPermittedHost = 0x7fc6060d6440 <isPermittedHost>, pRcvData = 0x7fc6060d6460 <doRcvData>, OpenLstnSocks = 0x7fc6060d6960 <doOpenLstnSocks>, pOnListenDeinit = 0x0, OnDestruct = 0x0,
  pOnRegularClose = 0x7fc6060d6480 <onRegularClose>, pOnErrClose = 0x7fc6060d64a0 <onErrClose>, pOnSessAccept = 0x0, OnSessConstructFinalize = 0x0, pOnSessDestruct = 0x0, OnMsgReceive = 0x0}
(gdb) p i
$3 = 0
(gdb) p *pThis.ppLstn[0]
$4 = {objData = {pObjInfo = 0x1aa7090, pszName = 0x1a44010 "\a"}, pDrvrData = 0x0, Drvr = {ifVersion = 0, ifIsLoaded = 0, Construct = 0x0, Destruct = 0x0, Abort = 0x0, Rcv = 0x0, Send = 0x0, Connect = 0x0, AcceptConnReq = 0x0, GetRemoteHName = 0x0, GetRemoteIP = 0x0, SetMode = 0x0, SetAuthMode = 0x0,
    SetPermitExpiredCerts = 0x0, SetPermPeers = 0x0, CheckConnection = 0x0, GetSock = 0x0, SetSock = 0x0, GetRemAddr = 0x0, EnableKeepAlive = 0xc1, SetKeepAliveIntvl = 0x0, SetKeepAliveProbes = 0x1a44010, SetKeepAliveTime = 0x0, SetGnutlsPriorityString = 0x0, LstnInit = 0x0, SetCheckExtendedKeyUsage = 0x0,
    SetPrioritizeSAN = 0x0, SetTlsVerifyDepth = 0x0, SetTlsCAFile = 0x0, SetTlsKeyFile = 0x0, SetTlsCertFile = 0x0}, pszDrvrAuthMode = 0x0, pUsr = 0x0, pNS = 0x0}
```
The segmentation fault occured in a `tcpsrv` thread, that is started by the `imtcp` module. It happened because the tcp part of the `netstrm_t` struct is now uninitialized and in fact the `lmnsd_ptcp` module itself got released at this point.
```gdb
(gdb) info threads
  Id   Target Id                         Frame
* 1    Thread 0x7fc60222a700 (LWP 29977) Ctl (pNsdpoll=0x7fc5dc000be0, pNsd=0x0, id=0, pUsr=0x1aa7570, mode=1, op=2) at nsdpoll_ptcp.c:200
  2    Thread 0x7fc600a24700 (LWP 29982) 0x00007fc6094035ac in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x1aadbd4) at ../sysdeps/nptl/futex-internal.h:183
  3    Thread 0x7fc5fa3f8700 (LWP 30414) 0x00007fc6094035ac in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7fc5e002f1b0) at ../sysdeps/nptl/futex-internal.h:183
  4    Thread 0x7fc5fbbfe700 (LWP 29983) 0x00007fc6094035ac in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7fc5e00015b4) at ../sysdeps/nptl/futex-internal.h:183
  5    Thread 0x7fc5fb3fc700 (LWP 30056) 0x00007fc6094035ac in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7fc5e000b984) at ../sysdeps/nptl/futex-internal.h:183
  6    Thread 0x7fc5fb7fd700 (LWP 30055) 0x00007fc6094035ac in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7fc5e00062b0) at ../sysdeps/nptl/futex-internal.h:183
  7    Thread 0x7fc5fa7f9700 (LWP 30413) 0x00007fc6094035ac in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7fc5e0011ef4) at ../sysdeps/nptl/futex-internal.h:183
  8    Thread 0x7fc601e29700 (LWP 29976) 0x00007fc609407034 in __libc_read (fd=10, buf=buf@entry=0x7fc601e26c00, nbytes=nbytes@entry=8192) at ../sysdeps/unix/sysv/linux/read.c:26
  9    Thread 0x7fc5f9ff7700 (LWP 30415) 0x00007fc6094035ac in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7fc5e0031470) at ../sysdeps/nptl/futex-internal.h:183
  10   Thread 0x7fc609a3d240 (LWP 29969) 0x00007fc6094038ee in futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7ffcd5566220, clockid=<optimized out>, expected=0, futex_word=0x1ae5bc0) at ../sysdeps/nptl/futex-internal.h:320
(gdb) thread 10
[Switching to thread 10 (Thread 0x7fc609a3d240 (LWP 29969))]
#0  0x00007fc6094038ee in futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7ffcd5566220, clockid=<optimized out>, expected=0, futex_word=0x1ae5bc0) at ../sysdeps/nptl/futex-internal.h:320
320       int err = lll_futex_clock_wait_bitset (futex_word, expected,
(gdb) bt
#0  0x00007fc6094038ee in futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7ffcd5566220, clockid=<optimized out>, expected=0, futex_word=0x1ae5bc0) at ../sysdeps/nptl/futex-internal.h:320
#1  __pthread_cond_wait_common (abstime=0x7ffcd5566220, clockid=<optimized out>, mutex=0x1ae5b70, cond=0x1ae5b98) at pthread_cond_wait.c:520
#2  __pthread_cond_timedwait (cond=cond@entry=0x1ae5b98, mutex=mutex@entry=0x1ae5b70, abstime=abstime@entry=0x7ffcd5566220) at pthread_cond_wait.c:656
#3  0x0000000000465135 in thrdTerminateNonCancel (pThis=0x1ae5b70) at ../threads.c:135
#4  0x0000000000465595 in thrdTerminate (pThis=pThis@entry=0x1ae5b70) at ../threads.c:184
#5  0x000000000046561d in thrdDestruct (pThis=0x1ae5b70) at ../threads.c:84
#6  0x0000000000440998 in llDestroyElt (pList=pList@entry=0x6abb60 <llThrds>, pElt=0x1ae5d60) at linkedlist.c:78
#7  0x0000000000440a08 in llDestroy (pThis=pThis@entry=0x6abb60 <llThrds>) at linkedlist.c:109
#8  0x0000000000465630 in thrdTerminateAll () at ../threads.c:197
#9  0x0000000000410222 in deinitAll () at rsyslogd.c:2022
#10 main (argc=2, argv=0x7ffcd55668f8) at rsyslogd.c:2156
(gdb) frame 8
#8  0x0000000000465630 in thrdTerminateAll () at ../threads.c:197
197             llDestroy(&llThrds);
(gdb) l
192     /* terminate all known threads gracefully.
193      */
194     rsRetVal thrdTerminateAll(void)
195     {
196             DEFiRet;
197             llDestroy(&llThrds);
198             RETiRet;
199     }
200
201
(gdb) p llThrds
$5 = {iNumElts = 1, pEltDestruct = 0x4655b0 <thrdDestruct>, pKeyDestruct = 0x0, cmpOp = 0x0, pKey = 0x0, pRoot = 0x0, pLast = 0x0}
(gdb) frame 6
#6  0x0000000000440998 in llDestroyElt (pList=pList@entry=0x6abb60 <llThrds>, pElt=0x1ae5d60) at linkedlist.c:78
78                      pList->pEltDestruct(pElt->pData);
(gdb) p *pElt
$6 = {pNext = 0x0, pKey = 0x0, pData = 0x1ae5b70}
(gdb) p *(thrdInfo_t*)pElt.pData
$7 = {mutThrd = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 1, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 12 times>, "\001", '\000' <repeats 26 times>, __align = 0}, condThrdTerm = {__data = {{__wseq = 2, __wseq32 = {__low = 2,
          __high = 0}}, {__g1_start = 0, __g1_start32 = {__low = 0, __high = 0}}, __g_refs = {2, 0}, __g_size = {0, 0}, __g1_orig_size = 0, __wrefs = 8, __g_signals = {0, 0}}, __size = "\002", '\000' <repeats 15 times>, "\002", '\000' <repeats 19 times>, "\b\000\000\000\000\000\000\000\000\000\000", __align = 2},
  bIsActive = 1, bShallStop = 1, pUsrThrdMain = 0x7fc603645df0 <runInput>, pAfterRun = 0x7fc603641af0 <afterRun>, thrdID = 140488411879168, bNeedsCancel = 0 '\000', name = 0x1a5b440 "imfile"}
```
The main thread released all of the module threads except the `imfile` which is currently in the line , but we still have a `tcpsrv` thread, created by the `imtcp` module, which should not be possible.

Note that, in order to get such clear traces you have to disable module unloading in the rsyslog configuration:
```
global(debug.unloadModules="off")
```

### Steps to reproduce the behavior

1. Ensure that you have the `imtcp` module listed in the configuration with at least two inputs. Example config excerpt:
```ini
module(
    load="imtcp"
    KeepAlive="on"
    KeepAlive.Interval="15"
    KeepAlive.Probes="3"
    KeepAlive.Time="60"
)

input(
    type="imtcp"
    ruleset="general_ruleset"
    address="127.0.0.1"
    port="20513"
)
input(
    type="imtcp"
    ruleset="general_ruleset"
    address="127.0.0.1"
    port="20514"
)
```
2. Start `rsyslogd`:
```shell
source /etc/sysconfig/syslog; /usr/sbin/rsyslog-service-prepare; /usr/sbin/rsyslogd -n >/dev/null
```
3. Generate sustained load for the input module using `tcpflood`:
```shell
./tcpflood -t127.0.0.1 -p20513 -c10 -Y -m10000000
```
4. Initiate graceful termination of `ryslogd`:
```shell
kill -15 $(pgrep rsyslogd)
```
#### Automated reproduction
We used the following, simplistic bash script, for reproduction and verification:
```shell
#!/usr/bin/env bash

function main() {
    source /etc/sysconfig/syslog
    /usr/sbin/rsyslog-service-prepare
    local runs=0
    local occurrences=0
    while [ $active == "yes" ]; do
        /usr/sbin/rsyslogd -n >/dev/null &
        pid_rsyslog=$!
        sleep 5
        /usr/src/packages/SOURCES/rsyslog/tests/tcpflood -t127.0.0.1 -p20513 -c10 -Y -m10000000 > /dev/null &
        sleep 3
        kill -15 $(pgrep rsyslogd) &
        wait $pid_rsyslog
        result=$?
        if [ $result == 139 ]; then
          occurrences=$(($occurrences + 1))
        fi
        runs=$(($runs + 1))
    done

    echo "RESULTS: run(s): ${runs}, occurence(s): ${occurrences}"
}

function signal_handler() {
    echo "Terminating the test execution..."
    active="no"
}

trap 'signal_handler' INT

active="yes"
main
```
This assumes that you have the `tcpflood` compiled and available at `/usr/src/packages/SOURCES/rsyslog/tests/tcpflood`.

Fault frequency in our environment is around 20%
`RESULTS: run(s): 256, occurence(s): 53`

### Environment
- rsyslog version: 8.2110.0
- platform: SUSE Linux Enterprise Server 15 SP3

**Comment by TheGOro** [comment]
PR #4777 addresses this issue.
