### ISSUE TITLE
does it really memory leak in gtlsGlblInit while fail in tls negotiate?

### ISSUE THREAD

**Issue by YanAnzouyijun** [rsyslog/rsyslog#4913]
while i reset the remote frequently, the asan reports there are a lot of memory leak
### Expected behavior
no mem leak in asan
### Actual behavior
the asan reports there are a lot of memory leak
### Steps to reproduce the behavior
mem leak 1:
Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0xffff9e000230 in __interceptor_calloc (/usr/lib64/libasan.so.6+0xa5230)
    #1 0xffff92d2d1c4 in gnutls_dh_params_init (/usr/lib64/libgnutls.so.30+0x511c4)
    #2 0xffff99ada8d0 in gtlsGlblInit /usr/src/debug/rsyslog-8.2110.0-7.h7..aarch64/runtime/nsd_gtls.c:749
    #3 0xffff99ada8d0 in nsd_gtlsClassInit /usr/src/debug/rsyslog-8.2110.0-7.h7..aarch64/runtime/nsd_gtls.c:2322
    #4 0xffff99ada8d0 in nsd_gtlsClassInit /usr/src/debug/rsyslog-8.2110.0-7.h7..aarch64/runtime/nsd_gtls.c:2314
    #5 0xffff99adabb0 in modInit /usr/src/debug/rsyslog-8.2110.0-7.h7..aarch64/runtime/nsd_gtls.c:2348
    #6 0xaaaada3b5e0c in doModInit /usr/src/debug/rsyslog-8.2110.0-7.h7..aarch64/runtime/modules.c:584
    #7 0xaaaada3b9598 in Load /usr/src/debug/rsyslog-8.2110.0-7.h7..aarch64/runtime/modules.c:1263
    #8 0xaaaada3b2264 in UseObj /usr/src/debug/rsyslog-8.2110.0-7.h7..aarch64/runtime/obj.c:1231
    #9 0xffff99f6846c  (<unknown module>)
    #10 0xaaaada32df9c in TCPSendInit /usr/src/debug/rsyslog-8.2110.0-7.h7..aarch64/tools/omfwd.c:812
    #11 0xaaaada32ec1c in doTryResume /usr/src/debug/rsyslog-8.2110.0-7.h7..aarch64/tools/omfwd.c:1006
    #12 0xaaaada3f9b40 in actionPrepare ../action.c:1078
    #13 0xaaaada3ff83c in actionPrepare ../action.c:1669
    #14 0xaaaada3ff83c in processMsgMain ../action.c:1656
    #15 0xaaaada400568 in doSubmitToActionQ ../action.c:1828
    #16 0xaaaada3ea5f4 in execAct /usr/src/debug/rsyslog-8.2110.0-7.h7..aarch64/runtime/ruleset.c:209
    #17 0xaaaada3ea5f4 in scriptExec /usr/src/debug/rsyslog-8.2110.0-7.h7..aarch64/runtime/ruleset.c:599
    #18 0xaaaada3ebe60 in processBatch /usr/src/debug/rsyslog-8.2110.0-7.h7..aarch64/runtime/ruleset.c:660

memleak 2:
Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0xffff9e000074 in malloc (/usr/lib64/libasan.so.6+0xa5074)
    #1 0xffff92e346f4  (/usr/lib64/libgnutls.so.30+0x1586f4)
    #2 0xffff92e34814  (/usr/lib64/libgnutls.so.30+0x158814)
    #3 0xffff92e2bb1c  (/usr/lib64/libgnutls.so.30+0x14fb1c)
    #4 0xffff92d2da78 in gnutls_dh_params_generate2 (/usr/lib64/libgnutls.so.30+0x51a78)
    #5 0xffff99ada8ec in gtlsGlblInit /usr/src/debug/rsyslog-8.2110.0-7.h7.aarch64/runtime/nsd_gtls.c:750
    #6 0xffff99ada8ec in nsd_gtlsClassInit /usr/src/debug/rsyslog-8.2110.0-7.h7.aarch64/runtime/nsd_gtls.c:2322
    #7 0xffff99ada8ec in nsd_gtlsClassInit /usr/src/debug/rsyslog-8.2110.0-7.h7.aarch64/runtime/nsd_gtls.c:2314
    #8 0xffff99adabb0 in modInit /usr/src/debug/rsyslog-8.2110.0-7.h7.aarch64/runtime/nsd_gtls.c:2348
    #9 0xaaaada3b5e0c in doModInit /usr/src/debug/rsyslog-8.2110.0-7.h7.aarch64/runtime/modules.c:584
    #10 0xaaaada3b9598 in Load /usr/src/debug/rsyslog-8.2110.0-7.h7.aarch64/runtime/modules.c:1263
    #11 0xaaaada3b2264 in UseObj /usr/src/debug/rsyslog-8.2110.0-7.h7.aarch64/runtime/obj.c:1231
    #12 0xffff99f6846c  (<unknown module>)
    #13 0xaaaada32df9c in TCPSendInit /usr/src/debug/rsyslog-8.2110.0-7.h7.aarch64/tools/omfwd.c:812
    #14 0xaaaada32ec1c in doTryResume /usr/src/debug/rsyslog-8.2110.0-7.h7.aarch64/tools/omfwd.c:1006
    #15 0xaaaada3f9b40 in actionPrepare ../action.c:1078
    #16 0xaaaada3ff83c in actionPrepare ../action.c:1669
    #17 0xaaaada3ff83c in processMsgMain ../action.c:1656

and  i found that the function gtlsGlblExit do not release the dh_params malloc in function gtlsGlblInit.
/* globally de-initialize GnuTLS */
static rsRetVal
gtlsGlblExit(void)
{
	DEFiRet;
	gnutls_global_deinit();
	RETiRet;
}

### Environment
- rsyslog version: 8.2110.0
- platform: centos

**Comment by YanAnzouyijun** [comment]
https://github.com/rsyslog/rsyslog/pull/4929

**Comment by YanAnzouyijun** [comment]
this issue has been resolved
