### ISSUE TITLE
Segmentation fault in close journal

### ISSUE THREAD

**Issue by t-feng** [rsyslog/rsyslog#4953]
### Expected behavior
No Segmentation fault

### Actual behavior
Core was generated by `/usr/sbin/rsyslogd -n -i/var/run/rsyslogd.pid'.
Program terminated with signal SIGSEGV, Segmentation fault.

### Steps to reproduce the behavior
NO, I found core file during daliy work

### Environment
- rsyslog version: rsyslog-8.2110.0
- platform: openEuler-x86_64
- for configuration questions/issues, include rsyslog.conf and included config files

```
# Where to place auxiliary files
global(workDirectory="/var/lib/rsyslog")

# Use default timestamp format
module(load="builtin:omfile" Template="RSYSLOG_TraditionalFileFormat")

#### MODULES ####

module(load="imuxsock"    # provides support for local system logging (e.g. via logger command)
       SysSock.Use="off") # Turn off message reception via local log socket;
                          # local messages are retrieved through imjournal now.
module(load="imjournal"             # provides access to the systemd journal
       StateFile="/run/log/imjournal.state") # File to store the position in the journal
#module(load="imklog") # reads kernel messages (the same are read from journald)
#module(load="immark") # provides --MARK-- message capability

$imjournalRatelimitInterval 0

# Include all config files in /etc/rsyslog.d/
include(file="/etc/rsyslog.d/*.conf" mode="optional")
#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  -/var/log/maillog


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log
```

**Comment by t-feng** [comment]
I dig this issue, and got the following info:
```
(gdb) bt
#0  0x00005626ed0d8804 in ratelimitDestruct (ratelimit=0x0) at ratelimit.c:406
#1  0x00007f9b5b220c5b in afterRun () at imjournal.c:1004
#2  0x00005626ed0e1060 in thrdDestruct (pThis=0x5626ed320c60) at ../threads.c:92
#3  0x00005626ed0bae14 in llDestroyElt (pElt=0x5626ed320d10, pList=0x5626ed1294e0 <llThrds>) at linkedlist.c:78
#4  llDestroy (pThis=pThis@entry=0x5626ed1294e0 <llThrds>) at linkedlist.c:109
#5  0x00005626ed0e10b0 in thrdTerminateAll () at ../threads.c:197
#6  0x00005626ed08813e in deinitAll () at rsyslogd.c:2039
#7  main (argc=3, argv=0x7ffee1684cf8) at rsyslogd.c:2173
(gdb) info threads
  Id   Target Id                           Frame
* 1    Thread 0x7f9b5b23ac40 (LWP 4165665) 0x00005626ed0d8804 in ratelimitDestruct (ratelimit=0x0) at ratelimit.c:406
(gdb)

```

**Comment by t-feng** [comment]
```
(gdb) f 0
#0  0x00005626ed0d8804 in ratelimitDestruct (ratelimit=0x0) at ratelimit.c:406
406             if(ratelimit->pMsg != NULL) {
(gdb) p ratelimit
$1 = (ratelimit_t *) 0x0
```
