### ISSUE TITLE
Segmentation fault in custom docker container

### ISSUE THREAD

**Issue by qx10** [rsyslog/rsyslog#4956]
### Expected behavior

No Segmentation fault

### Actual behavior

Core was generated by `/usr/sbin/rsyslogd -n`.
Program terminated with signal SIGSEGV, Segmentation fault.

### Steps to reproduce the behavior

No. Because rsyslog runs in custom docker container with more than one process. But on another machine with similar configuration all OK. 

### Environment
- rsyslog version: 8.2206
- platform: 
-- Ubuntu 20.04.4 LTS in container
-- Debian 10 on host (EC2 instance with kernel 4.19.0-17-cloud-amd64) 

### Configs
- /etc/rsyslog.conf

```
module(load="mmrm1stspace")
module(load="imudp")
input(type="imudp" port="5140")
module(load="imtcp")
input(type="imtcp" port="5140")
$RepeatedMsgReduction off
$FileOwner root
$FileGroup root
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser root
$PrivDropToGroup root
global(workDirectory="/var/spool/rsyslog")
global(parser.permitSlashInProgramName="on")
action(name="internal-mmrm1stspace" type="mmrm1stspace")
global(maxMessageSize="64k")
main_queue(
  queue.size="70000"
  queue.discardSeverity="0"
)
$IncludeConfig /etc/rsyslog.d/*.conf

```
- /etc/rsyslog.d/00-rsyslog-internal.conf

```
# Message format templates for selflogging
# %timereported% %$myhostname% [%SYSLOGSEVERITY-TEXT%] %syslogtag%: %msg%
template(name="LocalMessage" type="list") {
  property(name="timereported")
  constant(value=" ")
  property(name="$myhostname")
  constant(value=" [")
  property(name="syslogseverity-text" caseconversion="upper")
  constant(value="] ")
  property(name="syslogtag")
  property(name="msg" spifno1stsp="on")
  property(name="msg" droplastlf="on")
  constant(value="\n")
}
# Message format templates for debug logging
# %timereported% %$myhostname% %syslogfacility-text%.%syslogseverity-text% %syslogtag%: %msg%
template(name="LocalDebugMessage" type="list") {
  property(name="timereported")
  constant(value=" ")
  property(name="syslogfacility-text")
  constant(value=".")
  property(name="syslogseverity-text")
  constant(value=" ")
  property(name="$myhostname")
  constant(value=" ")
  property(name="syslogtag")
  property(name="msg" spifno1stsp="on")
  property(name="msg" droplastlf="on")
  constant(value="\n")
}
# internal-syslog action logs self messages to $LOG_DIR/rsyslogd.log
#  RSYSLOG_DISABLED_FACILITIES = ['syslog','cron','authpriv']
#  local rsyslog have syslog facility
if ($syslogfacility-text == ['syslog','cron','authpriv']) then {
  action(
    name="internal-syslog"
    type="omfile"
    File="/var/log/container/rsyslogd.log"
    template="LocalMessage"
    flushOnTXEnd="on"
    DirCreateMode="0755"
    FileCreateMode="0644"
  )
  stop
}
# use DEBUG=true to enable debug non-internal-syslog messages
```
- /etc/rsyslog.d/43-ngx_lua_jwt_auth.conf

```
module(load="mmnormalize")                                                                                                                                                                                         
# message template to host rsyslog                                                                                                                                                                                 
template(name="HostRemoteMessageRFC5424" type="list") {                                                                                                                                                            
  constant(value="<")                                                                                                                                                                                              
  property(name="$!localpri")                                                                                                                                                                                      
  constant(value=">1")                                                                                                                                                                                             
  constant(value=" ")
  property(name="timereported" dateFormat="rfc3339") 
  constant(value=" ")
  property(name="$myhostname")
  constant(value=" ")
  constant(value="office-proxy-external")
  constant(value=" ")
  property(name="app-name")
  constant(value=" ")
  constant(value="-")
  constant(value=" ")
  property(name="structured-data")
  property(name="$!json-message" spifno1stsp="on")
  property(name="$!json-message" droplastlf="on")
  constant(value="\n")
}
# simple JSON constructor from $!all-json text property
#  $!all-json can be used only in templates
template(name="_alljson" type="list") {
  property(name="$!all-json")
}
# this template construct an error message in case json parser failed
template(name="_json-error" type="list") {
  constant(value="***JSON_PARSE_ERROR***: ")
  property(name="msg" droplastlf="on")
}
if ($app-name == "ngx_lua_jwt_auth" and $msg startswith 'AUTH') then {
  action(type="mmnormalize" ruleBase="/etc/rsyslog.d/mmnormalize.rules")
  # add msg property to resulting message
  set $!alljson = exec_template("_alljson");
  set $.!alljsonstr-parse-res = parse_json($!alljson, "\$!json-message");
  # json parse error handling in some case
  if ($.!alljsonstr-parse-res == 0) then {
    # add raw msg as well
    set $!json-message!msg = $msg;
  } else {
    # script error - $!alljson is not JSON apparently, so enable and watch debug
    set $!json-message!msg = exec_template("_json-error");
    set $!json-message!severity = 'emerg';
  }
 # PRI = facility * 8 + severity
  # https://tools.ietf.org/html/rfc5424#section-6.2.1
  set $!localpri = 32 + $syslogseverity;
  action (
    type="omfwd"
    Target="localhost"
    Port="514"
    Protocol="tcp"
    template="HostRemoteMessageRFC5424"
  )
  stop
}
```
- /etc/rsyslog.d/50-default.conf

```
# RFC5424 template redefined to use standard fields in containers
# RFC5424:  "<\%PRI%>1 %TIMESTAMP:::date-rfc3339% %HOSTNAME%    %APP-NAME%       %PROCID%           %MSGID%   %STRUCTURED-DATA% %msg%\n\"
# usecase:  "<\%PRI%>1 %TIMESTAMP:::date-rfc3339% %$myhostname% %FACTER_task_id% %application_name% %SERVICE% %structured-data% %msg%\n\"
template(name="RemoteMessageRFC5424" type="list") {
  constant(value="<")
  property(name="pri")
  constant(value=">1")
  constant(value=" ")
  property(name="timereported" dateFormat="rfc3339")
  constant(value=" ")
  property(name="$myhostname")
  constant(value=" ")
  constant(value="office-proxy-external")
  constant(value=" ")
  property(name="app-name")
  constant(value=" ")
  constant(value="-")
  constant(value=" ")
  property(name="structured-data")
  property(name="msg" spifno1stsp="on")
  property(name="msg" droplastlf="on")
  constant(value="\n")
}
# logs to host - the rest not filtered above
action(
  type="omfwd"
  name="to-localhost"
  Target="localhost"
  Port="514"
  Protocol="tcp"
  template="RemoteMessageRFC5424"
)
stop
```
- /etc/rsyslog.d/mmnormalize.rules
```version=2
rule=ngx_jwt_auth,allow:%spaces:whitespace%AUTH - %connection:number% ALLOW to %url:string% for %email:string% from %ip:string%
rule=ngx_jwt_auth,deny:%spaces:whitespace%AUTH - %connection:number% DENY to %url:string% for %email:string% from %ip:string%
rule=ngx_jwt_auth,allow:AUTH - %connection:number% ALLOW to %url:string% for %email:string% from %ip:string%
rule=ngx_jwt_auth,deny:AUTH - %connection:number% DENY to %url:string% for %email:string% from %ip:string%
# annotations
annotate=ngx_jwt_auth:+service="office-proxy"
```

**Comment by qx10** [comment]
I used gdb for dig some information.

```
(gdb) core /core.184
[New LWP 207]
[New LWP 184]
[New LWP 200]
[New LWP 201]
[New LWP 204]
[New LWP 205]
[New LWP 206]
[New LWP 203]
[New LWP 202]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/rsyslogd -n'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f46016aae39 in ln_v2_parseString () from /lib/liblognorm.so.5
[Current thread is 1 (Thread 0x7f45fb7fd700 (LWP 207))]
```

```
(gdb) bt
#0  0x00007f46016aae39 in ln_v2_parseString () from /lib/liblognorm.so.5
#1  0x00007f46016a295f in ln_normalizeRec () from /lib/liblognorm.so.5
#2  0x00007f46016a29e4 in ln_normalizeRec () from /lib/liblognorm.so.5
#3  0x00007f46016a29e4 in ln_normalizeRec () from /lib/liblognorm.so.5
#4  0x00007f46016a29e4 in ln_normalizeRec () from /lib/liblognorm.so.5
#5  0x00007f46016a29e4 in ln_normalizeRec () from /lib/liblognorm.so.5
#6  0x00007f46016a30cf in ln_normalize () from /lib/liblognorm.so.5
#7  0x00007f46016dc700 in ?? () from /usr/lib/rsyslog/mmnormalize.so
#8  0x000055c4b31ee9f6 in ?? ()
#9  0x000055c4b31f02ff in ?? ()
#10 0x000055c4b31f072c in ?? ()
#11 0x000055c4b31e7b13 in ?? ()
#12 0x000055c4b31e7b6d in ?? ()
#13 0x000055c4b31e87e4 in ?? ()
#14 0x000055c4b31996ec in ?? ()
#15 0x000055c4b31e3524 in ?? ()
#16 0x000055c4b31e00a1 in wtiWorker ()
#17 0x000055c4b31de7f6 in ?? ()
#18 0x00007f4601ecd609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#19 0x00007f46019d3133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

```
(gdb) info threads
  Id   Target Id                       Frame 
* 1    Thread 0x7f45fb7fd700 (LWP 207) 0x00007f46016aae39 in ln_v2_parseString () from /lib/liblognorm.so.5
  2    Thread 0x7f460171c540 (LWP 184) 0x00007f46019c90e6 in __pselect (nfds=0, readfds=0x0, writefds=0x0, exceptfds=0x0, timeout=<optimized out>, sigmask=<optimized out>)
    at ../sysdeps/unix/sysv/linux/pselect.c:48
  3    Thread 0x7f4601406700 (LWP 200) 0x00007f46019c699f in __GI___poll (fds=0x7f45ec000b80, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  4    Thread 0x7f4601005700 (LWP 201) 0x00007f46019d346e in epoll_wait (epfd=11, events=0x7f4601002340, maxevents=10, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  5    Thread 0x7f4600402700 (LWP 204) futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f46016eaf18) at ../sysdeps/nptl/futex-internal.h:183
  6    Thread 0x7f45fbfff700 (LWP 205) futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f46016eaf80) at ../sysdeps/nptl/futex-internal.h:183
  7    Thread 0x7f45fbbfe700 (LWP 206) futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f46016eafe8) at ../sysdeps/nptl/futex-internal.h:183
  8    Thread 0x7f4600803700 (LWP 203) futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f46016eaeb0) at ../sysdeps/nptl/futex-internal.h:183
  9    Thread 0x7f4600c04700 (LWP 202) 0x00007f46019d346e in epoll_wait (epfd=10, events=0x7f4600c02c90, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
```
