### ISSUE TITLE
How to enable debug symbols for GDB?

### ISSUE THREAD

**Issue by rudhranandhanr** [rsyslog/rsyslog#4973]
### Environment
- rsyslog version:8.2004
- platform: linux
- for configuration questions/issues, include rsyslog.conf and included config files

configurations:
./configure --enable-openssl=yes --disable-largefile --enable-share=yes --prefix=/usr/local --host=armv7-cortex_a9_v011-linux-gnueabi --disable-libgcrypt OPENSSL_LIBS="-L/home/rurajend/Source/core_analysis/sums_new/build/CSeriesM6/lib" OPENSSL_CFLAGS="-I/home/rurajend/Source/core_analysis/sums_new/build/CSeriesM6/include/openssl" LIBESTR_LIBS="-L/home/rurajend/Source/core_analysis/sums_new/build/CSeriesM6/lib" LIBESTR_CFLAGS="-I/home/rurajend/Source/core_analysis/sums_new/build/CSeriesM6/include/libestr" LIBFASTJSON_LIBS="-L/home/rurajend/Source/core_analysis/sums_new/build/CSeriesM6/lib" LIBFASTJSON_CFLAGS="-I/home/rurajend/Source/core_analysis/sums_new/build/CSeriesM6/include/libfastjson" CURL_LIBS="-L/home/rurajend/Source/core_analysis/sums_new/build/CSeriesM6/lib" CURL_CFLAGS="-I/home/rurajend/Source/core_analysis/sums_new/build/CSeriesM6/include/curl" ZLIB_CFLAGS="-I/home/rurajend/Source/core_analysis/sums_new/build/CSeriesM6/include/zlib" ZLIB_LIBS="-L/home/rurajend/Source/core_analysis/sums_new/build/CSeriesM6/lib" CFLAGS="-g -fPIE -I/home/rurajend/Source/core_analysis/sums_new/build/CSeriesM6/include/zlib -I/home/rurajend/Source/core_analysis/sums_new/build/CSeriesM6/include" LDFLAGS="-L/home/rurajend/Source/core_analysis/sums_new/build/CSeriesM6/lib -lssl -lcrypto -lestr -lfastjson -lz" ac_cv_func_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes ac_cv_func_lstat_dereferences_slashed_symlink=yes ac_cv_func_stat_empty_string_bug=no enable_debug=yes enable_debug_symbols=yes enable_valgrind=yes enable_diagtools=yes enable_rtinst=yes

GDB OUTPUT:
 /opt/crosstool/armv7-cortex_a9_v010-linux-gnueabi/bin/armv7-cortex_a9_v010-linux-gnueabi-gdb -ex 'set solib-search-path build/CSeriesM6/lib' -ex 'file ./build/CSeriesM6/apps/open-src/rsyslog/opkg_staging/usr/local/bin/rsyslogd' -ex 'core-file ~/rsyslog_stress/var/core/dumps/1660438900_rsyslogd_core.26314'
GNU gdb (crosstool-NG 1.24.0) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=x86_64-build_pc-linux-gnu --target=armv7-cortex_a9_v010-linux-gnueabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Reading symbols from ./build/CSeriesM6/apps/open-src/rsyslog/opkg_staging/usr/local/bin/rsyslogd...done.
warning: exec file is newer than core file.
[New LWP 26314]
Core was generated by `/usr/local/bin/rsyslogd -n'.
Program terminated with signal SIGABRT, Aborted.
#0  0x7688b428 in ?? ()
(gdb) bt
#0  0x7688b428 in ?? ()
#1  0x7e8c5770 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) bt full
#0  0x7688b428 in ?? ()
No symbol table info available.
#1  0x7e8c5770 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) q

**Comment by rgerhards** [comment]
https://stackoverflow.com/questions/89603/how-does-the-debugging-option-g-change-the-binary-executable
