### ISSUE TITLE
rsyslog randomly crashes on restart

### ISSUE THREAD

**Issue by Alix82** [rsyslog/rsyslog#4982]
### Expected behavior
should not crash on restart.

### Actual behavior
with 'systemctl restart rsyslog' rsyslog randomly crashes on what seems to be a race condition 

(gdb) thread apply all bt

Thread 2 (Thread 0x7efd2f9608c0 (LWP 15883)):
#0  strgenDestruct (ppThis=ppThis@entry=0xc033e0) at strgen.c:172
#1  0x000000000043605b in destroyMasterStrgenList () at strgen.c:251
#2  strgenClassExit () at strgen.c:262
#3  0x000000000042d83a in rsrtExit () at rsyslog.c:264
#4  0x000000000040fef4 in deinitAll () at rsyslogd.c:2076
#5  main (argc=3, argv=0x7ffc576d88a8) at rsyslogd.c:2155

Thread 1 (Thread 0x7efd1b7fd700 (LWP 16490)):
#0  0x00007efd2bfafc20 in ?? ()
#1  <signal handler called>
#2  __lll_unlock_wake () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:371
#3  0x00007efd2f329a96 in __pthread_mutex_unlock_usercnt (mutex=mutex@entry=0xc83c18, decr=decr@entry=1) at pthread_mutex_unlock.c:59
#4  0x00007efd2f329b4a in __GI___pthread_mutex_unlock (mutex=mutex@entry=0xc83c18) at pthread_mutex_unlock.c:326
#5  0x0000000000442785 in mutexCancelCleanup (arg=arg@entry=0xc83c18) at srutils.c:522
#6  0x000000000044f572 in wtpWorker (arg=0xc83d60) at wtp.c:442
#7  0x00007efd2f32671a in start_thread (arg=0x7efd1b7fd700) at pthread_create.c:457
#8  0x00007efd2e3bd17d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

(gdb)frame 4
(gdb) p *mutex
{__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = -1, __spins = 0, __elision = 0, __list = {__prev = 0x0, 
      __next = 0x0}}, __size = '\000' <repeats 16 times>, "\377\377\377\377", '\000' <repeats 19 times>, __align = 0}

As you can see from the above, the mutex is no longer valid. Please note that increasing the debug level somehow avoids the crash, so it is a race condition subject to timing.

### Environment
- rsyslog version: 8.2106, but the issue also reproduces on the latest released version

Any ideas?

**Comment by Cropi** [comment]
Hello,

May I ask you to provide the configuration file you are using? So it's easier to reproduce.

**Comment by Alix82** [comment]
Closing the issue opening a new one with more complete description and fix (#5219)

**Comment by Alix82** [comment]
,ì
