### ISSUE TITLE
Segfault in MsgGetProp attempting to retrieve a long syslogtag while formatting by the template during the heavy load

### ISSUE THREAD

**Issue by kjchernov** [rsyslog/rsyslog#5110]
### Expected behavior
No segfault

### Actual behavior
Segfault at msg.c:4294

### Steps to reproduce the behavior
Unknown

### Environment
```
# rsyslogd -v
rsyslogd  8.2302.0 (aka 2023.02) compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/syslogd.pid
        Number of Bits in RainerScript integers: 64

template(name="rfc3164" type="string" string="<%PRI%>%TIMESTAMP:::date-rfc3339% %HOSTNAME% %syslogtag:1:32%%msg:::sp-if-no-1st-sp%%msg%")

action(type="omfwd" name="some-remote" action.resumeretrycount="-1" template="rfc3164" target="hostname" port="514" protocol="tcp" queue.size="200000" queue.type="FixedArray" queue.timeoutenqueue="0" queue.dequeuebatchsize="5000")
```

### Description

rsyslogd is receiving 60k-140k/sec messages from imptcp into a fixedarray queue in ruleset. Sometimes (I did not manage to find any corellation between this issue and load increase/queue drops) the action workers segfaults:
```[Tue Apr  4 12:34:45 2023] rs:some-remote[57075]: segfault at 0 ip 000055973032bd0e sp 00007f80337fd9a0 error 4 in rsyslogd[5597302e7000+a9000]```

The stack:
```
 (gdb) bt
 #0  MsgGetProp (pMsg=pMsg@entry=0x7f4d8fbffd00, pTpe=pTpe@entry=0x558ef556b340, pProp=pProp@entry=0x558ef556b360, pPropLen=pPropLen@entry=0x7f52fcfe9acc, pbMustBeFreed=pbMustBeFreed@entry=0x7f52fcfe9aca, 
     ttNow=ttNow@entry=0x7f52fcfe9ba0) at msg.c:4294
 #1  0x0000558ef38d1250 in tplToString (pTpl=0x558ef556aad0, pMsg=pMsg@entry=0x7f4d8fbffd00, iparam=0x7f52e4c73990, ttNow=ttNow@entry=0x7f52fcfe9ba0) at ../template.c:208
 #2  0x0000558ef38cb849 in prepareDoActionParams (ttNow=0x7f52fcfe9ba0, pMsg=0x7f4d8fbffd00, pWti=<optimized out>, pAction=0x558ef5575f40) at ../action.c:1125
 #3  processMsgMain (pAction=pAction@entry=0x558ef5575f40, pWti=pWti@entry=0x558ef5685eb0, pMsg=0x7f4d8fbffd00, ttNow=ttNow@entry=0x7f52fcfe9ba0) at ../action.c:1678
 #4  0x0000558ef38cb984 in processBatchMain (pVoid=0x558ef5575f40, pBatch=0x558ef5685ee0, pWti=0x558ef5685eb0) at ../action.c:1722
 #5  0x0000558ef38bf4ca in ConsumerReg (pThis=0x558ef55764b0, pWti=0x558ef5685eb0) at queue.c:2158
 #6  0x0000558ef38bc0d5 in wtiWorker (pThis=pThis@entry=0x558ef5685eb0) at wti.c:430
 #7  0x0000558ef38baad9 in wtpWorker (arg=0x558ef5685eb0) at wtp.c:435
 #8  0x00007f53240e2dd5 in start_thread () from /usr/lib64/libpthread.so.0
 #9  0x00007f5322ca2ead in clone () from /usr/lib64/libc.so.6
```

The locals:
```
(gdb) info locals
 iFrom = <optimized out>
 iTo = <optimized out>
 pSb = 0x0
 pRes = 0x0
 bufLen = 32
 pBufStart = 0x7f52e51b9ff0 ""
 pBuf = 0x7f52e51b9ff0 ""
 iLen = 32
 iOffs = <optimized out>
 datefmt = <optimized out>
 bDateInUTC = <optimized out>
 pmatch = {{rm_so = 124, rm_eo = 21902}, {rm_so = -434704112, rm_eo = 32594}, {rm_so = -469762016, rm_eo = 32594}, {rm_so = -1225127936, rm_eo = -737466148}, {rm_so = -434704128, rm_eo = 32594}, {rm_so = 0, 
     rm_eo = 0}, {rm_so = -469759216, rm_eo = 32594}, {rm_so = -178822432, rm_eo = 21902}, {rm_so = -178822296, rm_eo = 21902}, {rm_so = 0, rm_eo = 0}}
```

The message:
```
 (gdb) print *pMsg
 $1 = {objData = {pObjInfo = 0x558ef551ff10, pszName = 0x0}, flowCtlType = eFLOWCTL_LIGHT_DELAY, mut = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, 
       __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, iRefCount = 2, bParseSuccess = 0 '\000', iSeverity = 6, iFacility = 1, offAfterPRI = 4, offMSG = 354, 
   iProtocolVersion = 1, msgFlags = 32, iLenRawMsg = 822, iLenMSG = 468, iLenTAG = 35, iLenHOSTNAME = 18, iLenPROGNAME = 35, 
   pszRawMsg = 0x7f4b19171cb0 "<14>1 2023-04-04T01:33:47.000000+03:00 xxxxxxxx.xxx.local Microsoft-Windows-Security-Auditing - - [NXLOG@14506 EventTimeWritten=\"2023-04-04 01:33:47\" EventType=\"AUDIT_SUCCESS\" FileName=\"Security\" Even"..., pszHOSTNAME = 0x7f4d8fbffeb5 "xxxxxxxx.xxx.local", pszRcvdAt3164 = 0x0, pszRcvdAt3339 = 0x0, pszRcvdAt_MySQL = 0x0, pszRcvdAt_PgSQL = 0x0, 
   pszTIMESTAMP3164 = 0x7f4d8fbfff08 "Apr  4 01:33:47", pszTIMESTAMP3339 = 0x7f4d8fbfff18 "2023-04-04T01:33:47.000000+03:00", pszTIMESTAMP_MySQL = 0x0, pszTIMESTAMP_PgSQL = 0x0, 
   pszStrucData = 0x7f508da93020 "[NXLOG@14506 EventTimeWritten=\"2023-04-04 01:33:47\" EventType=\"AUDIT_SUCCESS\" FileName=\"Security\" EventID=\"4672\" CategoryNumber=\"12548\" RecordNumber=\"37834899\" EventReceivedTime=\"2023-04-04 01:33:49\" "..., lenStrucData = 255, pCSAPPNAME = 0x7f508ee3e8f0, pCSPROCID = 0x7f4b1c787470, pCSMSGID = 0x7f4b1c7874b0, pInputName = 0x558ef5536530, pRcvFromIP = 0x7f52fa32b320, 
   rcvFrom = {pRcvFrom = 0x7f52fa32b2c0, pfrominet = 0x7f52fa32b2c0}, pRuleset = 0x558ef55e3610, ttGenTime = 1680561229, tRcvdAt = {timeType = 2 '\002', month = 4 '\004', day = 4 '\004', wday = 2 '\002', 
     hour = 1 '\001', minute = 33 '!', second = 49 '1', secfracPrecision = 6 '\006', OffsetMinute = 0 '\000', OffsetHour = 3 '\003', OffsetMode = 43 '+', year = 2023, secfrac = 301203, inUTC = 0 '\000'}, 
   tTIMESTAMP = {timeType = 2 '\002', month = 4 '\004', day = 4 '\004', wday = 2 '\002', hour = 1 '\001', minute = 33 '!', second = 47 '/', secfracPrecision = 6 '\006', OffsetMinute = 0 '\000', 
     OffsetHour = 3 '\003', OffsetMode = 43 '+', year = 2023, secfrac = 0, inUTC = 0 '\000'}, json = 0x0, localvars = 0x0, szRawMsg = '\000' <repeats 100 times>, 
   szHOSTNAME = "xxxxxxxx.xxx.local", '\000' <repeats 13 times>, PROGNAME = {ptr = 0x7f4b28f6e0b0 "Microsoft-Windows-Security-Auditing", szBuf = "\260\340\366(K\177\000\000\000\000\000\000\000\000\000"}, TAG = {
     pszTAG = 0x7f4b28f6e080 "Microsoft-Windows-Security-Auditing", szBuf = "\200\340\366(K\177", '\000' <repeats 25 times>}, pszTimestamp3164 = "Apr  4 01:33:47", 
   pszTimestamp3339 = "2023-04-04T01:33:47.000000+03:00", pszTIMESTAMP_SecFrac = "\000\000\000\000\000\000", pszRcvdAt_SecFrac = "\000\000\000\000\000\000", pszTIMESTAMP_Unix = '\000' <repeats 11 times>, 
   pszRcvdAt_Unix = '\000' <repeats 11 times>, dfltTZ = "\000\000\000\000\000\000\000", pszUUID = 0x0}
```

The template:
```
 (gdb) print *pTpe
 $2 = {pNext = 0x558ef556b4b0, eEntryType = FIELD, fieldName = 0x558ef556b490 "syslogtag", lenFieldName = 9, bComplexProcessing = 1 '\001', data = {constant = {pConstant = 0x4 <Address 0x4 out of bounds>, 
       iLenConstant = 0}, field = {msgProp = {id = 4 '\004', name = 0x0, nameLen = 0}, iFromPos = 1, iToPos = 32, iFieldNr = 0, re = {buffer = 0x0, allocated = 0, used = 0, syntax = 0, fastmap = 0x0, 
         translate = 0x0, re_nsub = 0, can_be_null = 0, regs_allocated = 0, fastmap_accurate = 0, no_sub = 0, not_bol = 0, not_eol = 0, newline_anchor = 0}, has_regex = 0, iMatchToUse = 0, iSubMatchToUse = 0, 
       typeRegex = TPL_REGEX_BRE, nomatchAction = TPL_REGEX_NOMATCH_USE_DFLTSTR, has_fields = 0, field_delim = 0 '\000', eDateFormat = tplFmtDefault, eCaseConv = tplCaseConvNo, options = {bDropCC = 0, 
         bSpaceCC = 0, bEscapeCC = 0, bCompressSP = 0, bDropLastLF = 0, bSecPathDrop = 0, bSecPathReplace = 0, bSPIffNo1stSP = 0, bCSV = 0, bJSON = 0, bJSONf = 0, bJSONr = 0, bJSONfr = 0, bMandatory = 0, 
         bFromPosEndRelative = 0, bFixedWidth = 0, bDateInUTC = 0, dataType = 0, onEmpty = 0}}}}
```

The property to receive from MsgGetProp:
```
(gdb) print *pProp
 $12 = {id = 4 '\004', name = 0x0, nameLen = 0}
```

I did run the code on paper step-by-step, using the data provided by the gdb, and everything should have worked fine, but it didn't.

It looks like after calling `getTAG(pMsg, &pRes, &bufLen, LOCK_MUTEX)` the pRes was not set at all (or set to NULL). And from the first view the only way it could have happen is due to race condition of some sort.

I applied the following patch to see if the pRes was really NULL:
```
diff --git a/runtime/msg.c b/runtime/msg.c
index 488f7240c..53d5f6748 100644
--- a/runtime/msg.c
+++ b/runtime/msg.c
@@ -4018,6 +4018,13 @@ uchar *MsgGetProp(smsg_t *__restrict__ const pMsg, struct templateEntry *__restr
                        return UCHAR_CONSTANT("**INVALID PROPERTY NAME**");
        }
 
+       if (!pRes) {
+               LogMsg(0, RS_RET_PARAM_ERROR, LOG_WARNING, "msg: pRes is null for property id '%d'", pProp->id);
+               *pbMustBeFreed = 0;
+               *pPropLen = sizeof("**NULL PROPERTY VALUE**") - 1;
+               return UCHAR_CONSTANT("**NULL PROPERTY VALUE**");
+       }
+
        /* If we did not receive a template pointer, we are already done... */
        if(pTpe == NULL || !pTpe->bComplexProcessing) {
                *pPropLen = (bufLen == -1) ? (int) ustrlen(pRes) : bufLen;
```

And some time later that error appeared in my logs, but no segfault:
```
Apr  4 16:25:27 xxxxxxxx rsyslogd: msg: pRes is null for property id '4' [v8.2302.0 try https://www.rsyslog.com/e/1000 ]
```

And then I started to lock the message each time I'm getting it's tag:
```
diff --git a/runtime/msg.c b/runtime/msg.c
index 488f7240c..f15bbb91c 100644
--- a/runtime/msg.c
+++ b/runtime/msg.c
@@ -2545,12 +2545,15 @@ tryEmulateTAG(smsg_t *const pM, const sbool bLockMutex)
 void ATTR_NONNULL(2,3)
 getTAG(smsg_t * const pM, uchar **const ppBuf, int *const piLen, const sbool bLockMutex)
 {
+	if(bLockMutex == LOCK_MUTEX)
+		MsgLock(pM);
+
 	if(pM == NULL) {
 		*ppBuf = UCHAR_CONSTANT("");
 		*piLen = 0;
 	} else {
 		if(pM->iLenTAG == 0)
-			tryEmulateTAG(pM, bLockMutex);
+			tryEmulateTAG(pM, MUTEX_ALREADY_LOCKED);
 		if(pM->iLenTAG == 0) {
 			*ppBuf = UCHAR_CONSTANT("");
 			*piLen = 0;
@@ -2559,6 +2562,9 @@ getTAG(smsg_t * const pM, uchar **const ppBuf, int *const piLen, const sbool bLo
 			*piLen = pM->iLenTAG;
 		}
 	}
+
+	if(bLockMutex == LOCK_MUTEX)
+		MsgUnlock(pM);
 }
```

After that, no more error messages received, as well as no segfaults.

**Comment by rgerhards** [comment]
Thx for the excellent bug report, analysis and patch. The patch looks very good, I'll just do some additional verification.

**Comment by rgerhards** [comment]
Looks indeed very sound. A small note on potential mutex optimization (not done for good reason) is in the PR: https://github.com/rsyslog/rsyslog/pull/5118
