### ISSUE TITLE
rsyslogd v8.24.0 hung for a while

### ISSUE THREAD

**Issue by dongbiao830415** [rsyslog/rsyslog#5153]
### Actual behavior

The A program hangs because of the call to the vsyslog function 。

#0  0x00007fa1ed16036b in send () from /lib64/libc.so.6
#1  0x00007fa1ed159361 in __vsyslog_chk () from /lib64/libc.so.6
#2  0x00007fa1ed15958f in vsyslog () from /lib64/libc.so.6
#3  ..........................

### Steps to reproduce the behavior
Non-stop pressure testing of our B programs，B program also calls the vsyslog function，also hung up。All processes that actually call the vsyslog function hang。

One of the threads in rsyslogd is also hung:
#0  0x00007fa1ed16036b in send () from /lib64/libc.so.6
#1  0x00007fa1ed159361 in __vsyslog_chk () from /lib64/libc.so.6
#2  0x00007fa1ed15958f in syslog () from /lib64/libc.so.6
#3  0x000000000044b978 in logmsgInternalSubmit (flags=1, msg=<optimized out>, lenMsg=<optimized out>, pri=46, iErr=-2177) at rsyslogd.c:873
#4  logmsgInternal (iErr=iErr@entry=-2177, pri=pri@entry=46, msg=msg@entry=0x7fa1e8d5d3a0 "imuxsock[pid 1667]: begin to drop messages due to rate-limiting", flags=flags@entry=0) at rsyslogd.c:906
#5  0x000000000043bd1d in withinRatelimit (ratelimit=ratelimit@entry=0x7fa1d400c1e0, tt=<optimized out>) at ratelimit.c:176
#6  0x000000000043be70 in ratelimitMsg (ratelimit=0x7fa1d400c1e0, pMsg=0x7fa1d4003700, ppRepMsg=0x7fa1e8d5d808) at ratelimit.c:218
#7  0x000000000043c165 in ratelimitAddMsg (ratelimit=ratelimit@entry=0x7fa1d400c1e0, pMultiSub=pMultiSub@entry=0x0, pMsg=0x7fa1d4003700) at ratelimit.c:255
#8  0x00007fa1ea9696bf in SubmitMsg (ts=<optimized out>, cred=<optimized out>, pLstn=0x257dc60, lenRcv=<optimized out>, pRcv=0x7fa1d400cf10 "<135>Jun  5 11:53:12 smartlb: debug: 3") at imuxsock.c:981
#9  readSocket (pLstn=0x257dc60) at imuxsock.c:1077
#10 0x00007fa1ea969fde in runInput (pThrd=<optimized out>) at imuxsock.c:1503
#11 0x0000000000443ea6 in thrdStarter (arg=0x25c6d70) at ../threads.c:226
#12 0x00007fa1ede50e25 in start_thread () from /lib64/libpthread.so.0
#13 0x00007fa1ed15f34d in clone () from /lib64/libc.so.6

### Environment
rsyslog version: v8.24.0
platform: Centos7

**Comment by rgerhards** [comment]
The version you are using is very old and no longer supported by the community. It is also very probable that the problem stems back to long-solved issues. As such, please update to the currently supported version and retry. Report back if the problem persists.

The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

If you insist on using an outdated version, you can also contact your distro or consider [rsyslog professional services](https://www.rsyslog.com/professional-services/enterprise-support/).
