### ISSUE TITLE
test failure because of a double-free 

### ISSUE THREAD

**Issue by asarubbo** [rsyslog/rsyslog#5225]
Our [Gentoo Tinderbox](https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/) reported a test failure at [bug 914169](https://bugs.gentoo.org/914169)

By looking at test-suite.log I can see:

```
==13043==ERROR: AddressSanitizer: attempting double-free on 0x606000000020 in thread T0:
    #0 0x5559cb3ec896 in free (/var/tmp/portage/app-admin/rsyslog-8.2308.0/work/rsyslog-8.2308.0/tools/rsyslogd+0x129896)
    #1 0x7fc47e881ba3  (/lib64/libc.so.6+0x81ba3)
    #2 0x7fc47e882104 in dlsym (/lib64/libc.so.6+0x82104)
    #3 0x7fc47eca8c88  (/usr/lib64/libfaketime.so.1+0x2c88)
    #4 0x7fc47ecadcee in clock_gettime (/usr/lib64/libfaketime.so.1+0x7cee)
    #5 0x5559cb40fefa in __sanitizer::MonotonicNanoTime() (/var/tmp/portage/app-admin/rsyslog-8.2308.0/work/rsyslog-8.2308.0/tools/rsyslogd+0x14cefa)
    #6 0x5559cb35acc3 in __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView>>::PopulateFreeArray(__sanitizer::AllocatorStats*, unsigned long, __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView>>::RegionInfo*, unsigned long) (/var/tmp/portage/app-admin/rsyslog-8.2308.0/work/rsyslog-8.2308.0/tools/rsyslogd+0x97cc3)
    #7 0x5559cb35a90b in __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView>>::GetFromAllocator(__sanitizer::AllocatorStats*, unsigned long, unsigned int*, unsigned long) (/var/tmp/portage/app-admin/rsyslog-8.2308.0/work/rsyslog-8.2308.0/tools/rsyslogd+0x9790b)
    #8 0x5559cb35a534 in __sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView>>>::Refill(__sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView>>>::PerClass*, __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView>>*, unsigned long) (/var/tmp/portage/app-admin/rsyslog-8.2308.0/work/rsyslog-8.2308.0/tools/rsyslogd+0x97534)
    #9 0x5559cb35a1d6 in __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView>>, __sanitizer::LargeMmapAllocatorPtrArrayDynamic>::Allocate(__sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView>>>*, unsigned long, unsigned long) (/var/tmp/portage/app-admin/rsyslog-8.2308.0/work/rsyslog-8.2308.0/tools/rsyslogd+0x971d6)
    #10 0x5559cb359f30 in __sanitizer::QuarantineCache<__asan::QuarantineCallback>::Enqueue(__asan::QuarantineCallback, void*, unsigned long) (/var/tmp/portage/app-admin/rsyslog-8.2308.0/work/rsyslog-8.2308.0/tools/rsyslogd+0x96f30)
    #11 0x5559cb359dbc in __asan::Allocator::QuarantineChunk(__asan::AsanChunk*, void*, __sanitizer::BufferedStackTrace*) (/var/tmp/portage/app-admin/rsyslog-8.2308.0/work/rsyslog-8.2308.0/tools/rsyslogd+0x96dbc)
    #12 0x5559cb3ec8fb in free (/var/tmp/portage/app-admin/rsyslog-8.2308.0/work/rsyslog-8.2308.0/tools/rsyslogd+0x1298fb)
    #13 0x7fc47e881ba3  (/lib64/libc.so.6+0x81ba3)
    #14 0x7fc47e882104 in dlsym (/lib64/libc.so.6+0x82104)
    #15 0x7fc47eca8c88  (/usr/lib64/libfaketime.so.1+0x2c88)
    #16 0x7fc47ece7e6d  (/lib64/ld-linux-x86-64.so.2+0x4e6d)
    #17 0x7fc47ece7f53  (/lib64/ld-linux-x86-64.so.2+0x4f53)
    #18 0x7fc47ecfd76f  (/lib64/ld-linux-x86-64.so.2+0x1a76f)

0x606000000020 is located 0 bytes inside of 51-byte region [0x606000000020,0x606000000053)
freed by thread T0 here:
    #0 0x5559cb3ec896 in free (/var/tmp/portage/app-admin/rsyslog-8.2308.0/work/rsyslog-8.2308.0/tools/rsyslogd+0x129896)
    #1 0x7fc47e881ba3  (/lib64/libc.so.6+0x81ba3)

previously allocated by thread T0 here:
LLVMSymbolizer: error reading file: No such file or directory
    #0 0x5559cb3ecb3e in __interceptor_malloc (/var/tmp/portage/app-admin/rsyslog-8.2308.0/work/rsyslog-8.2308.0/tools/rsyslogd+0x129b3e)
    #1 0x7fc47ece6841 in _dl_exception_create_format (/lib64/ld-linux-x86-64.so.2+0x3841)
    #2 0x7ffecb38fd3f  ([stack]+0x1dd3f)

SUMMARY: AddressSanitizer: double-free (/var/tmp/portage/app-admin/rsyslog-8.2308.0/work/rsyslog-8.2308.0/tools/rsyslogd+0x129896) in free
==13043==ABORTING
```

I didn't look deeply into this issue so I don't know if the bug is in the unittest itself or in the involed libraries/daemons, if so please check for any security implications.
If I can do further, please let me know.

**Comment by rgerhards** [comment]
Sorry for the extremely late reply. But at least we do not close older issues just because of age...
This strongly looks like a libfaketime issue, so we add a suppression.
