### ISSUE TITLE
rsyslogd crashed with SIGABRT with Invalid next size message

### ISSUE THREAD

**Issue by aravindmani-1** [rsyslog/rsyslog#5350]
### Expected behavior
It is expected to not to crash.

### Actual behavior
Rsyslog process crashed with SIGABRT while processing logs in execSet function 

### Steps to reproduce the behavior
N/A. Issue was observed only once.

### Backtrace
        (gdb) bt
        #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        #1  0x00007eff621a7535 in __GI_abort () at abort.c:79
        #2  0x00007eff621fe648 in __libc_message (action=action@entry=do_abort,
            fmt=fmt@entry=0x7eff623082a0 "%s\n") at ../sysdeps/posix/libc_fatal.c:181
        #3  0x00007eff62204d6a in malloc_printerr (
            str=str@entry=0x7eff6230a038 "free(): invalid next size (normal)")
            at malloc.c:5359
        #4  0x00007eff6220677c in _int_free (av=0x7eff54000020, p=0x7eff5402ddb0,
            have_lock=<optimized out>) at malloc.c:4329
        #5  0x0000555a0ec442de in execSet (pWti=0x555a0fb29470, pMsg=0x7eff58007ff0,
            stmt=0x555a0fb06f20) at ruleset.c:229
        #6  scriptExec (root=<optimized out>, pMsg=pMsg@entry=0x7eff58007ff0,
            pWti=pWti@entry=0x555a0fb29470) at ruleset.c:602
        #7  0x0000555a0ec43f71 in execPROPFILT (pWti=<optimized out>,
            pMsg=<optimized out>, stmt=<optimized out>) at ruleset.c:312
        #8  scriptExec (root=<optimized out>, pMsg=pMsg@entry=0x7eff58007ff0,
            pWti=pWti@entry=0x555a0fb29470) at ruleset.c:623
        #9  0x0000555a0ec44341 in execPROPFILT (pWti=<optimized out>,
            pMsg=<optimized out>, stmt=<optimized out>) at ruleset.c:315
        #10 scriptExec (root=<optimized out>, pMsg=pMsg@entry=0x7eff58007ff0,
            pWti=pWti@entry=0x555a0fb29470) at ruleset.c:623
        #11 0x0000555a0ec43f71 in execPROPFILT (pWti=<optimized out>,
            pMsg=<optimized out>, stmt=<optimized out>) at ruleset.c:312
        --Type <RET> for more, q to quit, c to continue without paging--
        #12 scriptExec (root=<optimized out>, pMsg=pMsg@entry=0x7eff58007ff0,
            pWti=pWti@entry=0x555a0fb29470) at ruleset.c:623
        #13 0x0000555a0ec44b1a in processBatch (pBatch=0x555a0fb294a0,
            pWti=0x555a0fb29470) at ruleset.c:660
        #14 0x0000555a0ebfa94c in msgConsumer (notNeeded=<optimized out>,
            pBatch=0x555a0fb294a0, pWti=0x555a0fb29470) at rsyslogd.c:714
        #15 0x0000555a0ec3ffc0 in ConsumerReg (pThis=0x555a0fb28fb0,
            pWti=0x555a0fb29470) at queue.c:2111
        #16 0x0000555a0ec3cdd2 in wtiWorker (pThis=pThis@entry=0x555a0fb29470)
            at wti.c:429
        #17 0x0000555a0ec3b67a in wtpWorker (arg=0x555a0fb29470) at wtp.c:431
        #18 0x00007eff62617fa3 in start_thread (arg=<optimized out>)
            at pthread_create.c:486
        #19 0x00007eff6227e06f in clone ()
            at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
        (gdb)

### Environment

- rsyslog version: 
rsyslogd  8.1901.0 (aka 2019.01) compiled with:
        PLATFORM:                               x86_64-pc-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Number of Bits in RainerScript integers: 64
- platform:
Linux S5232F 5.10.0-8-2-amd64 # 1 SMP Debian 5.10.46-5 (2021-09-23) x86_64 GNU/Linux

- for configuration questions/issues, include rsyslog.conf and included config files
[rsyslog_conf.txt](https://github.com/rsyslog/rsyslog/files/14718867/rsyslog_conf.txt)

**GDB full traces and variables:** 
[rsyslog_crash.txt](https://github.com/rsyslog/rsyslog/files/14718876/rsyslog_crash.txt)

Issue was seen only once and there was no issue reported when i used valgrind rsyslogd -dn -f /etc/rsyslog.conf

**Comment by aravindmani-1** [comment]
> The version you are using is very old and no longer supported by the community. It is also very probable that the problem stems back to long-solved issues. As such, please update to the currently supported version and retry. Report back if the problem persists.
> 
> The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/
> 
> If you insist on using an outdated version, you can also contact your distro or consider [rsyslog professional services](https://www.rsyslog.com/professional-services/enterprise-support/).

Thanks @rgerhards
