### ISSUE TITLE
*** glibc detected *** rsyslogd: double free or corruption

### ISSUE THREAD

**Issue by philipseidel** [rsyslog/rsyslog#880]
I am getting a segmentation fault running rsyslogd 8.16.0 on RHEL5.

`# cat /etc/redhat-release`
Red Hat Enterprise Linux Server release 5.11 (Tikanga)

`# uname -a`
Linux localhost 2.6.18-408.el5 #1 SMP Fri Dec 11 14:03:08 EST 2015 x86_64 x86_64 x86_64 GNU/Linux

```
*** glibc detected *** rsyslogd: double free or corruption (!prev): 0x00002acbb75edc30 ***
======= Backtrace: =========
/lib64/libc.so.6[0x2acba9a044af]
/lib64/libc.so.6(cfree+0x4b)[0x2acba9a087ab]
rsyslogd(msgDestruct+0x34)[0x2acba8497124]
rsyslogd[0x2acba84b211f]
rsyslogd[0x2acba84b2793]
rsyslogd(wtiWorker+0xaa)[0x2acba84ad7aa]
rsyslogd[0x2acba84ad260]
/lib64/libpthread.so.0[0x2acba8b4f83d]
/lib64/libc.so.6(clone+0x6d)[0x2acba9a67fdd]
======= Memory map: ========
2acba8478000-2acba8502000 r-xp 00000000 08:01 1769495                    /sbin/rsyslogd
2acba8701000-2acba8704000 r--p 00089000 08:01 1769495                    /sbin/rsyslogd
2acba8704000-2acba870c000 rw-p 0008c000 08:01 1769495                    /sbin/rsyslogd
2acba870c000-2acba870d000 rw-p 2acba870c000 00:00 0
2acba870d000-2acba8729000 r-xp 00000000 08:01 2457922                    /lib64/ld-2.5.so
2acba8729000-2acba872b000 rw-p 2acba8729000 00:00 0
2acba8929000-2acba892a000 r--p 0001c000 08:01 2457922                    /lib64/ld-2.5.so
2acba892a000-2acba892b000 rw-p 0001d000 08:01 2457922                    /lib64/ld-2.5.so
2acba892b000-2acba893f000 r-xp 00000000 08:01 2457945                    /lib64/libz.so.1.2.3
2acba893f000-2acba8b3e000 ---p 00014000 08:01 2457945                    /lib64/libz.so.1.2.3
2acba8b3e000-2acba8b3f000 rw-p 00013000 08:01 2457945                    /lib64/libz.so.1.2.3
2acba8b49000-2acba8b5f000 r-xp 00000000 08:01 2457943                    /lib64/libpthread-2.5.so
2acba8b5f000-2acba8d5f000 ---p 00016000 08:01 2457943                    /lib64/libpthread-2.5.so
2acba8d5f000-2acba8d60000 r--p 00016000 08:01 2457943                    /lib64/libpthread-2.5.so
2acba8d60000-2acba8d61000 rw-p 00017000 08:01 2457943                    /lib64/libpthread-2.5.so
2acba8d61000-2acba8d65000 rw-p 2acba8d61000 00:00 0
2acba8d65000-2acba8d67000 r-xp 00000000 08:01 2457942                    /lib64/libdl-2.5.so
2acba8d67000-2acba8f67000 ---p 00002000 08:01 2457942                    /lib64/libdl-2.5.so
2acba8f67000-2acba8f68000 r--p 00002000 08:01 2457942                    /lib64/libdl-2.5.so
2acba8f68000-2acba8f69000 rw-p 00003000 08:01 2457942                    /lib64/libdl-2.5.so
2acba8f69000-2acba8f6a000 rw-p 2acba8f69000 00:00 0
2acba8f6a000-2acba8f71000 r-xp 00000000 08:01 2457944                    /lib64/librt-2.5.so
2acba8f71000-2acba9171000 ---p 00007000 08:01 2457944                    /lib64/librt-2.5.so
2acba9171000-2acba9172000 r--p 00007000 08:01 2457944                    /lib64/librt-2.5.so
2acba9172000-2acba9173000 rw-p 00008000 08:01 2457944                    /lib64/librt-2.5.so
2acba9173000-2acba9175000 r-xp 00000000 08:01 1489945                    /usr/lib64/libestr.so.0.0.0
2acba9175000-2acba9375000 ---p 00002000 08:01 1489945                    /usr/lib64/libestr.so.0.0.0
2acba9375000-2acba9376000 rw-p 00002000 08:01 1489945                    /usr/lib64/libestr.so.0.0.0
2acba9376000-2acba9380000 r-xp 00000000 08:01 1489940                    /usr/lib64/libjson-c.so.2.0.1
2acba9380000-2acba957f000 ---p 0000a000 08:01 1489940                    /usr/lib64/libjson-c.so.2.0.1
2acba957f000-2acba9580000 rw-p 00009000 08:01 1489940                    /usr/lib64/libjson-c.so.2.0.1
2acba9580000-2acba9581000 rw-p 2acba9580000 00:00 0
2acba9581000-2acba9584000 r-xp 00000000 08:01 1489949                    /usr/lib64/liblogging-stdlog.so.0.0.0
2acba9584000-2acba9784000 ---p 00003000 08:01 1489949                    /usr/lib64/liblogging-stdlog.so.0.0.0
2acba9784000-2acba9785000 rw-p 00003000 08:01 1489949                    /usr/lib64/liblogging-stdlog.so.0.0.0
2acba9785000-2acba9792000 r-xp 00000000 08:01 2457940                    /lib64/libgcc_s-4.1.2-20080825.so.1
2acba9792000-2acba9992000 ---p 0000d000 08:01 2457940                    /lib64/libgcc_s-4.1.2-20080825.so.1
2acba9992000-2acba9993000 rw-p 0000d000 08:01 2457940                    /lib64/libgcc_s-4.1.2-20080825.so.1
2acba9993000-2acba9ae2000 r-xp 00000000 08:01 2457938                    /lib64/libc-2Aborted (core dumped)

# core dump
(gdb) info thread
  11 Thread 0x2acba9ced590 (LWP 16517)  0x00002acba9a61172 in select () from /lib64/libc.so.6
  10 Thread 16518  0x00002acba9a61172 in select () from /lib64/libc.so.6
  9 Thread 16519  0x00002acba8b56aab in read () from /lib64/libpthread.so.0
  8 Thread 16520  0x00002acba9a683c8 in epoll_wait () from /lib64/libc.so.6
  7 Thread 16521  0x00002acba9a683c8 in epoll_wait () from /lib64/libc.so.6
  6 Thread 16522  0x00002acba8b56654 in __lll_lock_wait () from /lib64/libpthread.so.0
  5 Thread 16523  0x00002acba8b54019 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  4 Thread 16524  0x00002acba8b54019 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  3 Thread 16525  0x00002acba8b54019 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  2 Thread 16527  0x00002acba8b54019 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
* 1 Thread 0x2acbaf5ce940 (LWP 16526)  0x00002acba99c2fc5 in raise () from /lib64/libc.so.6

(gdb) thread apply all bt full

Thread 11 (Thread 0x2acba9ced590 (LWP 16517)):
#0  0x00002acba9a61172 in select () from /lib64/libc.so.6
No symbol table info available.
#1  0x00002acba84c42b7 in mainloop (argc=<value optimized out>, argv=<value optimized out>) at rsyslogd.c:1505
        tvSelectTimeout = {tv_sec = 588, tv_usec = 680000}
#2  main (argc=<value optimized out>, argv=<value optimized out>) at rsyslogd.c:1639
No locals.

Thread 10 (Thread 16518):
#0  0x00002acba9a61172 in select () from /lib64/libc.so.6
No symbol table info available.
#1  0x00002acba9ef9342 in runInput (pThrd=<value optimized out>) at imuxsock.c:1448
        iRet = RS_RET_TERMINATE_WHEN_IDLE
        maxfds = 4
        nfds = 5
        i = -514
        fd = <value optimized out>
        pReadfds = 0x2acbb75d8670
#2  0x00002acba84bb9fd in thrdStarter (arg=0x2acbb75d7990) at ../threads.c:212
        iRet = <value optimized out>
        pThis = 0x5
        thrdName = "in:imuxsock", '\000' <repeats 20 times>
        sigSet = {__val = {1048576, 0 <repeats 15 times>}}
#3  0x00002acba8b4f83d in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#4  0x00002acba9a67fdd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 9 (Thread 16519):
#0  0x00002acba8b56aab in read () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00002acbaa0fe7d8 in readklog (pModConf=0x2acbb759c360) at /usr/include/bits/unistd.h:35
        q = <value optimized out>
        len = 0
        i = <value optimized out>
        bufRcv = '\000' <repeats 131072 times>
        errmsg = '\000' <repeats 1784 times>"\300, \027\000\000\000\000\000\000Hz\316\251\313*\000\000@\000\000\000\000\000\000\000Hz\316\251\313*\000\000\240_\034\254\313*\000\000\230\027\000\000\000\000\000\000!\000\000\000\000\000\000\000\t", '\000' <repeats 75 times>, "f", '\000' <repeats 15 times>, "\004", '\000' <repeats 12 times>, "%.\000\000\300\362\242\000\000\000\000\000\000\000\000\340y\316\251\313*\000\000\000\000\000\000\000\000\000\000\340y\316\251\313*\000\000\264\352\017\252\313*\000\000\t\000\000\000\000\000\000\000\003\000\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000p\034\254\313*\000\000\376m\240\251\313*\000\000\t\000\000\000\000\000\000\000\264\352\017\252\313*\000"
        p = 0x2acbb75d7b80 ""
        iMaxLine = 4096
        pRcv = 0x2acbac1a5800 ""
#2  klogLogKMsg (pModConf=0x2acbb759c360) at bsd.c:311
No locals.
#3  0x00002acbaa0fdc05 in runInput (pThrd=0x2acbb75d7b80) at imklog.c:283
        iRet = -512
#4  0x00002acba84bb9fd in thrdStarter (arg=0x2acbb75d7b80) at ../threads.c:212
        iRet = <value optimized out>
        pThis = 0x5
        thrdName = "in:imklog", '\000' <repeats 22 times>
        sigSet = {__val = {1048576, 0 <repeats 15 times>}}
#5  0x00002acba8b4f83d in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#6  0x00002acba9a67fdd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 8 (Thread 16520):
#0  0x00002acba9a683c8 in epoll_wait () from /lib64/libc.so.6
No symbol table info available.
#1  0x00002acbaa303f06 in rcvMainLoop (pWrkr=0x2acbaa506700) at imudp.c:795
        iRet = -1396934416
        nfds = 1
        efd = 12
        i = 1
        frominetPrev = {ss_family = 0, __ss_align = 0, __ss_padding = '\000' <repeats 111 times>}
        bIsPermitted = 1
        udpEPollEvt = 0x2acbb75dd130
        currEvt = {{events = 1, data = {ptr = 0x2acbb75981b0, fd = -1218870864, u32 = 3076096432, u64 = 47054442824112}}, {
            events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {
            events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {
            events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {
            events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {
            events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}}
        errStr = '\000' <repeats 439 times>, "1", '\000' <repeats 40 times>, "(\000\000\000\060\000\000\000\200o\274\254\313*\000\000
---Type <return> to continue, or q <return> to quit---
\300n\274\254\313*", '\000' <repeats 178 times>, "0m\274\254\313*\000\000\000\000\000\000\000\000\000\000\257o\274\254\313*\000\000\220o\274\254\313*\000\000\220o\274\254\313*\000\000\001\000\000\000\000\000\000\000\240n\274\254\313*\000\000\036M0\252\313*\000\000\037\000\000\000\000\000\000\000\060m\274\254\313*\000\000\250\262\247\251\313*\000\000\001\200\255\373\000\000\000\000\220o\274\254\313*\000\000\220o\274\254\313*\000\000\220o\274\254\313*\000\000\220o\274\254\313*\000\000\231o\274\254\313*\000\000\257o\274\254\313*\000\000\220o\274\254\313*\000\000\257o\274\254\313*", '\000' <repeats 46 times>, "\004\000\000\000\070\251r\250\313*\000\000\000\000\274\254\313*\000\000\000\000\000\000\000\000\000\000\207\360\226|\000\000\000\000\bo\274\254\313*", '\000' <repeats 26 times>"\260, \303\316\251\313*\000\000\377\377\377\377", '\000' <repeats 12 times>...
        lstn = 0x2acbb75981b0
        nLstn = <value optimized out>
#2  0x00002acbaa3046d8 in wrkr (myself=0x2acbaa506700) at imudp.c:1184
        pWrkr = 0xc
        thrdName = "imudp(w1)\000\377\377\377\377\377\377\320\251\234\255\313*\000\000P\242\234\255\313*\000"
#3  0x00002acbaa3047ef in runInput (pThrd=0x2acbb75d7d70) at imudp.c:1209
        i = 1
        wrkrThrdAttr = {__size = '\000' <repeats 17 times>, "\020", '\000' <repeats 16 times>, "@", '\000' <repeats 20 times>,
          __align = 0}
#4  0x00002acba84bb9fd in thrdStarter (arg=0x2acbb75d7d70) at ../threads.c:212
        iRet = <value optimized out>
        pThis = 0xc
        thrdName = "in:imudp", '\000' <repeats 23 times>
        sigSet = {__val = {1048576, 0 <repeats 15 times>}}
#5  0x00002acba8b4f83d in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#6  0x00002acba9a67fdd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 7 (Thread 16521):
#0  0x00002acba9a683c8 in epoll_wait () from /lib64/libc.so.6
No symbol table info available.
#1  0x00002acbaa50b7ad in runInput (pThrd=<value optimized out>) at imptcp.c:1862
        nEvents = 1
        events = {{events = 1, data = {ptr = 0x2acbb000cf70, fd = -1342124176, u32 = 2952843120, u64 = 47054319570800}}, {
            events = 1, data = {ptr = 0x2acbb0002740, fd = -1342167232, u32 = 2952800064, u64 = 47054319527744}}, {events = 1,
            data = {ptr = 0x2acbb0002740, fd = -1342167232, u32 = 2952800064, u64 = 47054319527744}}, {events = 0, data = {
              ptr = 0x0, fd = 0, u32 = 0, u64 = 0}} <repeats 125 times>}
#2  0x00002acba84bb9fd in thrdStarter (arg=0x2acbb75d7f60) at ../threads.c:212
        iRet = <value optimized out>
        pThis = 0x8
        thrdName = "in:imptcp", '\000' <repeats 22 times>
        sigSet = {__val = {1048576, 0 <repeats 15 times>}}
#3  0x00002acba8b4f83d in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#4  0x00002acba9a67fdd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 6 (Thread 16522):
#0  0x00002acba8b56654 in __lll_lock_wait () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00002acba8b51f4a in _L_lock_1034 () from /lib64/libpthread.so.0
No symbol table info available.
#2  0x00002acba8b51e0c in pthread_mutex_lock () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x00002acba84aefeb in qqueueMultiEnqObjNonDirect (pThis=0x2acbb75a4f30, pMultiSub=0x2acbad9c9750) at queue.c:2804
        iCancelStateSave = <value optimized out>
        i = <value optimized out>
        localRet = <value optimized out>
        iRet = <value optimized out>
#4  0x00002acba84c2375 in multiSubmitMsg2 (pMultiSub=0x2acbad9c9750) at rsyslogd.c:863
        pQueue = 0xfffffffffffffffc
        pRuleset = <value optimized out>
        iRet = <value optimized out>
#5  0x00002acbaa30416e in processSocket (pWrkr=0x2acbaa5066c0) at imudp.c:594
        errStr = "'M0\252\313*\000\000\001\000\000\000\000\000\000\000p\236\234\255\313*\000\000QZ\235\251\313*\000\000P\231\234\255\313*\000\000\000\000\000\000\000\000\000\000\060\236\234\255\313*", '\000' <repeats 42 times>"\360, \237\234\255\313*\000\000\036M0\252\313*\000\000\200\236\234\255\313*", '\000' <repeats 34 times>"\377, \377\377\377\377\377\377\377\000\000\000\000\t\000\000\000%M0\252\313*\000\000\000\000\000\000\000\000\000\000\070\235\234\255\313*", '\000' <repeats 62 times>, "\n\000\000\000\067\235\234\255\313*", '\000' <repeats 42 times>, " ", '\000' <repeats 22 times>, "d", '\000' <repeats 112 times>, "\001", '\000' <repeats 11 times>, "\001\000\000\000&M0\252\313*", '\000' <repeats 561 times>
        mh = {msg_name = 0x2acbad9c9f80, msg_namelen = 128, msg_iov = 0x2acbad9c9740, msg_iovlen = 1, msg_control = 0x0,
          msg_controllen = 0, msg_flags = 0}
        iRet = -4
        iNbrTimeUsed = 1
        ttGenTime = 1457979941
        frominet = {ss_family = 2, __ss_align = 0,
          __ss_padding = "\016", '\000' <repeats 91 times>, "\004\000\000\000\060\000\000\000\060\000\000\000\320\240\234\255\313*\000"}
        stTime = {timeType = 2 '\002', month = 3 '\003', day = 14 '\016', hour = 11 '\v', minute = 25 '\031', second = 41 ')',
          secfracPrecision = 6 '\006', OffsetMinute = 0 '\000', OffsetHour = 7 '\a', OffsetMode = 45 '-', year = 2016,
          secfrac = 175916, inUTC = 0 '\000'}
        multiSub = {maxElem = 1024, nElem = 1, ppMsgs = 0x2acbad9c7660}
        pMsgs = {0x2acbb0017a00, 0x2acbb0017a00, 0x2acbb75f05d0, 0x2acbb75f0890, 0x2acbb75f0b50, 0x2acbb75f0ea0, 0x2acbb0017f40,
          0x2acbb0018330, 0x2acbb0018730, 0x2acbb0018b10, 0x2acbb0018ef0, 0x2acbb0019240, 0x2acbb0019590, 0x2acbb0019a10,
          0x0 <repeats 1010 times>}
        iov = {{iov_base = 0x2acbb759ca70, iov_len = 4096}}
#6  rcvMainLoop (pWrkr=0x2acbaa5066c0) at imudp.c:802
        iRet = -1382242064
        nfds = 1
        efd = 13
        i = 0
        frominetPrev = {ss_family = 0, __ss_align = 0, __ss_padding = '\000' <repeats 111 times>}
        bIsPermitted = 1
        udpEPollEvt = 0x2acbb75dd320
        currEvt = {{events = 1, data = {ptr = 0x2acbb75981b0, fd = -1218870864, u32 = 3076096432, u64 = 47054442824112}}, {
            events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {
            events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {
            events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {
            events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {
            events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}}
        errStr = '\000' <repeats 439 times>, "0", '\000' <repeats 40 times>, "(\000\000\000\060\000\000\000\320\240\234\255\313*\000\000\020\240\234\255\313*", '\000' <repeats 178 times>"\200, \236\234\255\313*\000\000\000\000\000\000\000\000\000\000\377\240\234\255\313*\000\000\340\240\234\255\313*\000\000\340\240\234\255\313*\000\000\001\000\000\000\000\000\000\000\360\237\234\255\313*\000\000\036M0\252\313*\000\000\037\000\000\000\000\000\000\000\200\236\234\255\313*\000\000\250\262\247\251\313*\000\000\001\200\255\373\000\000\000\000\340\240\234\255\313*\000\000\340\240\234\255\313*\000\000\340\240\234\255\313*\000\000\340\240\234\255\313*\000\000\351\240\234\255\313*\000\000\377\240\234\255\313*\000\000\340\240\234\255\313*\000\000\377\240\234\255\313*", '\000' <repeats 46 times>, "\004", '\000' <repeats 75 times>"\377, \377\377\377", '\000' <repeats 20 times>, "`T\316\251\313*\000\000\000\000\000\000\000\000\000\000@\000\000\000\000\000\000\000Hz\316\251\313*\000\000\360\237\234\255\313*\000"
        lstn = <value optimized out>
        nLstn = <value optimized out>
#7  0x00002acbaa3046d8 in wrkr (myself=0x2acbaa5066c0) at imudp.c:1184
        pWrkr = 0x2acbb75af840
        thrdName = "imudp(w0)", '\000' <repeats 22 times>
#8  0x00002acba8b4f83d in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#9  0x00002acba9a67fdd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 5 (Thread 16523):
#0  0x00002acba8b54019 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00002acbaa50b428 in wrkr (myself=0x2acbaa70f6e0) at imptcp.c:1610
No locals.
#2  0x00002acba8b4f83d in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x00002acba9a67fdd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 4 (Thread 16524):
#0  0x00002acba8b54019 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00002acbaa50b428 in wrkr (myself=0x2acbaa70f728) at imptcp.c:1610
No locals.
#2  0x00002acba8b4f83d in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x00002acba9a67fdd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 3 (Thread 16525):
#0  0x00002acba8b54019 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00002acba84ad9fc in doIdleProcessing (pThis=0x2acbb75d5900) at wti.c:266
        t = {tv_sec = 0, tv_nsec = 0}
#2  wtiWorker (pThis=0x2acbb75d5900) at wti.c:344
        pWtp = 0x2acbb75d57b0
        pAction = <value optimized out>
        bInactivityTOOccured = 0
        localRet = <value optimized out>
        terminateRet = <value optimized out>
        wrkrInfo = <value optimized out>
        iCancelStateSave = <value optimized out>
        i = <value optimized out>
        j = <value optimized out>
        k = <value optimized out>
#3  0x00002acba84ad260 in wtpWorker (arg=0x2acbb75d5900) at wtp.c:389
        pWti = 0x2acbb75d596c
        pThis = 0x2acbb75d57b0
        sigSet = {__val = {1048576, 0 <repeats 15 times>}}
        pszDbgHdr = <value optimized out>
        thrdName = "rs:main Q:Reg", '\000' <repeats 18 times>
#4  0x00002acba8b4f83d in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00002acba9a67fdd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 2 (Thread 16527):
#0  0x00002acba8b54019 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00002acba84ad9fc in doIdleProcessing (pThis=0x2acbb75993b0) at wti.c:266
        t = {tv_sec = 0, tv_nsec = 0}
#2  wtiWorker (pThis=0x2acbb75993b0) at wti.c:344
        pWtp = 0x2acbb7599260
        pAction = <value optimized out>
        bInactivityTOOccured = 0
        localRet = <value optimized out>
        terminateRet = <value optimized out>
        wrkrInfo = <value optimized out>
        iCancelStateSave = <value optimized out>
        i = <value optimized out>
        j = <value optimized out>
        k = <value optimized out>
#3  0x00002acba84ad260 in wtpWorker (arg=0x2acbb75993b0) at wtp.c:389
        pWti = 0x2acbb759941c
        pThis = 0x2acbb7599260
        sigSet = {__val = {1048576, 0 <repeats 15 times>}}
        pszDbgHdr = <value optimized out>
        thrdName = "rs:action 2 queue:Reg\000\000\000\000\000\000\000\000\000\000"
#4  0x00002acba8b4f83d in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00002acba9a67fdd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 1 (Thread 0x2acbaf5ce940 (LWP 16526)):
#0  0x00002acba99c2fc5 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00002acba99c4a70 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00002acba99fc94b in __libc_message () from /lib64/libc.so.6
No symbol table info available.
#3  0x00002acba9a044af in _int_free () from /lib64/libc.so.6
No symbol table info available.
#4  0x00002acba9a087ab in free () from /lib64/libc.so.6
No symbol table info available.
#5  0x00002acba8497124 in msgDestruct (ppThis=0x2acbaf5cdf68) at msg.c:940
        pThis = 0x2acbb75efa70
        iTrimCtr = 6965
#6  0x00002acba84b211f in DequeueConsumableElements (pThis=0x2acbb75a4f30, pWti=0x2acbb75af9d0) at queue.c:1590
        nDequeued = <value optimized out>
        nDeleted = 2
        pMsg = <value optimized out>
#7  DequeueConsumable (pThis=0x2acbb75a4f30, pWti=0x2acbb75af9d0) at queue.c:1681
        iRet = <value optimized out>
        iQueueSize = <value optimized out>
#8  0x00002acba84b2793 in DequeueForConsumer (pThis=0x4085, pWti=0x408e) at queue.c:1822
No locals.
#9  ConsumerReg (pThis=0x4085, pWti=0x408e) at queue.c:1876
        iCancelStateSave = <value optimized out>
        bNeedReLock = <value optimized out>
        iRet = <value optimized out>
#10 0x00002acba84ad7aa in wtiWorker (pThis=0x2acbb75af9d0) at wti.c:334
        pWtp = 0x2acbb75af870
        pAction = <value optimized out>
        bInactivityTOOccured = 0
        localRet = <value optimized out>
        terminateRet = RS_RET_OK
        wrkrInfo = <value optimized out>
        iCancelStateSave = <value optimized out>
        i = <value optimized out>
        j = <value optimized out>
        k = <value optimized out>
#11 0x00002acba84ad260 in wtpWorker (arg=0x2acbb75af9d0) at wtp.c:389
        pWti = 0x4085
        pThis = 0x2acbb75af870
        sigSet = {__val = {1048576, 0 <repeats 15 times>}}
        pszDbgHdr = <value optimized out>
        thrdName = "rs:remote:Reg", '\000' <repeats 18 times>
#12 0x00002acba8b4f83d in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#13 0x00002acba9a67fdd in clone () from /lib64/libc.so.6
No symbol table info available.
```

**Comment by rgerhards** [comment]
Please upgrade to 8.17.0. There have been several fixes which could be the reason for what you see. If you use mmnormalize, chances are almost 100% that 8.17.0 will fix the issue. Please re-open if the problem persists with 8.17.

**Comment by philipseidel** [comment]
I will give that a try; however, it doesn't appear that that rsyslog-8.17.0 is available in the epel-5 repo.  http://rpms.adiscon.com/v8-stable/epel-5/x86_64/RPMS/.
It appears that this bug only seems to occur when multiple threads are enabled for the imudp module.
